// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import type { Context } from "./types.js";

/** Configuration is read from the environment; hosts inject it from their own settings UI. */
export function context(): Context {
  return {
    config: {

    },
  };
}
