// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { McpServer } from "@modelcontextprotocol/server";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { z } from "zod";
import { operations } from "../ops.js";
import { context } from "./config.js";

export const server = new McpServer({ name: "toolfactory", version: "0.1.0" });

for (const op of operations) {
  server.registerTool(
    op.name,
    {
      description: op.description,
      inputSchema: op.input as z.ZodObject,
      outputSchema: (op.output ?? z.unknown()) as z.ZodType,
      annotations: op.annotations,
      _meta: { "dev.toolfactory": { requires: op.requires ?? [] } },
    },
    async (args: Record<string, unknown>) => {
      const result = await op.handler(args as never, context());
      return {
        resultType: "complete" as const,
        content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
        structuredContent: result as Record<string, unknown>,
      };
    },
  );
}

export async function serve(): Promise<void> {
  await server.connect(new StdioServerTransport());
}

if (process.argv[1] && /toolfactory[\\/]mcp\.[cm]?[jt]s$/.test(process.argv[1])) {
  serve().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
