// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import type { z } from "zod";

/** Host capabilities an operation may declare. Portable: net, fs, shell, secret. */
export type Capability =
  | "net"
  | "fs"
  | "shell"
  | "secret"
  | "browser"
  | "model"
  | "user-input"
  | "channel";

export interface Context {
  /** Configuration values read from the environment, keyed as declared in dev.toolfactory/tool.json. */
  config: Record<string, string | undefined>;
}

export interface Operation<Input extends z.ZodObject = z.ZodObject, Output extends z.ZodType = z.ZodType> {
  name: string;
  description: string;
  input: Input;
  output?: Output;
  requires?: Capability[];
  annotations?: {
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    idempotentHint?: boolean;
    openWorldHint?: boolean;
  };
  handler: (args: z.infer<Input>, context: Context) => Promise<z.infer<Output>> | z.infer<Output>;
}

/** Identity function that pins the generic parameters so handlers are typed. */
export function operation<Input extends z.ZodObject, Output extends z.ZodType>(
  definition: Operation<Input, Output>,
): Operation<Input, Output> {
  return definition;
}
