# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""Registers the generated plugin through a fake `PluginContext` and, when `tool.json`
`tests.examples` supplies one, calls a real handler — everything `hermes plugins doctor --ci`
proves for registration, plus the one call doctor never makes. No Hermes import: needs only this
checkout and Node, which the shim handler spawns.
"""

from __future__ import annotations

import json
import tempfile
from pathlib import Path
from typing import Any

from toolfactory_hermes import register


class _State:
    def __init__(self, data_dir: Path) -> None:
        self.data_dir = data_dir


class FakeCtx:
    """The slice of `hermes_cli.plugins.PluginContext` that `register(ctx)` touches."""

    def __init__(self, data_dir: Path) -> None:
        self.state = _State(data_dir)
        self.registrations: list[dict[str, Any]] = []

    def register_tool(self, **kwargs: Any) -> None:
        self.registrations.append(kwargs)


def test_register_adds_every_declared_tool() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        ctx = FakeCtx(Path(tmp))
        register(ctx)
        assert [r["name"] for r in ctx.registrations] == ["adopt","bootstrap-repo","build","check","coverage","doctor","eject","gate","init","introspect","package","secrets","unadopt","unpublish","validate"]


def test_doctor_handler_returns_the_real_result() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        ctx = FakeCtx(Path(tmp))
        register(ctx)
        handler = next(r["handler"] for r in ctx.registrations if r["name"] == "doctor")
        result = json.loads(handler({}))
        assert "error" not in result
        assert "toolfactory" in result
