// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
// One real OpenClaw agent turn against a scripted OpenAI-compatible model — no LLM key. The
// fixtures in e2e/fixtures.json are projected from dev.toolfactory/ops.json and tool.json's
// tests.examples; OpenClaw's own QA lane drives OpenClaw through this same aimock package.
//
// Three constraints, none of them discoverable, each of which costs a failing run:
//  1. Every openclaw call must be ASYNC. useAimock serves the model inside this Vitest worker, so
//     execFileSync would block the event loop and the child's POST /v1/responses is never answered.
//  2. VITEST and every VITEST_* variable must be stripped from the child environment: with them
//     set the published openclaw CLI writes zero bytes and exits 0. OpenClaw does the same
//     sanitisation before spawning its own CLI (src/auto-reply/reply/commands-openclaw-cli.ts).
//  3. `plugins install --link`, never a copy: a plain install copies this package's whole tree,
//     node_modules/openclaw included, into the state directory.
import { execFile } from "node:child_process";
import { mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { useAimock } from "@copilotkit/aimock/vitest";
import { beforeAll, describe, expect, it } from "vitest";

const execFileAsync = promisify(execFile);
const here = dirname(fileURLToPath(import.meta.url));
const pluginDir = join(here, "..");
const openclaw = join(pluginDir, "node_modules", "openclaw", "openclaw.mjs");
const MODEL = "openai/gpt-5.6-luna";

const aimock = useAimock({ port: 0, fixtures: join(here, "fixtures.json") });

let env: NodeJS.ProcessEnv;

async function oc(args: string[]): Promise<string> {
  const { stdout } = await execFileAsync(process.execPath, [openclaw, ...args], {
    env,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  return stdout;
}

beforeAll(async () => {
  const home = mkdtempSync(join(tmpdir(), "openclaw-e2e-"));
  const configPath = join(home, "openclaw.json");
  const clean = Object.fromEntries(
    Object.entries(process.env).filter(([key]) => key !== "VITEST" && !key.startsWith("VITEST_")),
  );
  env = {
    ...clean,
    HOME: home,
    OPENCLAW_STATE_DIR: home,
    OPENCLAW_CONFIG_PATH: configPath,
    OPENAI_API_KEY: "sk-aimock-dummy",
  };
  // The shape OpenClaw's own e2e fixtures use: one loopback OpenAI-compatible provider, a dummy
  // key, and allowPrivateNetwork, without which OpenClaw refuses a loopback provider URL.
  const config = {
    "plugins": {
      "enabled": true
    },
    "models": {
      "mode": "merge",
      "providers": {
        "openai": {
          "baseUrl": `${aimock().url}/v1`,
          "apiKey": "sk-aimock-dummy",
          "api": "openai-responses",
          "agentRuntime": {
            "id": "openclaw"
          },
          "request": {
            "allowPrivateNetwork": true
          },
          "models": [
            {
              "id": "gpt-5.6-luna",
              "name": "gpt-5.6-luna",
              "api": "openai-responses",
              "agentRuntime": {
                "id": "openclaw"
              },
              "reasoning": false,
              "input": [
                "text"
              ],
              "cost": {
                "input": 0,
                "output": 0,
                "cacheRead": 0,
                "cacheWrite": 0
              },
              "contextWindow": 128000,
              "contextTokens": 96000,
              "maxTokens": 4096
            }
          ]
        }
      }
    },
    "agents": {
      "defaults": {
        "model": {
          "primary": "openai/gpt-5.6-luna"
        },
        "models": {
          "openai/gpt-5.6-luna": {
            "agentRuntime": {
              "id": "openclaw"
            },
            "params": {
              "transport": "sse",
              "openaiWsWarmup": false
            }
          }
        }
      }
    }
  };
  writeFileSync(configPath, JSON.stringify(config, null, 2));
  await oc(["plugins", "install", "--link", pluginDir, "--force", "--accept-capabilities"]);
}, 300_000);

describe("toolfactory in a real OpenClaw agent turn", () => {
  it("registers its tools at runtime", async () => {
    const inspected = JSON.parse(await oc(["plugins", "inspect", "toolfactory", "--runtime", "--json"]));
    expect(inspected.plugin.status).toBe("loaded");
    expect(inspected.plugin.toolNames).toEqual(["adopt","bootstrap-repo","build","check","coverage","doctor","eject","gate","init","introspect","package","unadopt","validate"]);
  });

  it("the model calls doctor and the tool's result reaches the reply", async () => {
    const turn = JSON.parse(
      await oc([
        "agent", "--local", "--agent", "main", "--session-id", `e2e-${Date.now()}`,
        "--model", MODEL, "--thinking", "off", "--timeout", "120", "--json",
        "--message",
        "Call the tool named doctor. Reply with only the exact text returned by that tool.",
      ]),
    );
    expect(turn.meta.agentMeta.terminalReceipt.successfulToolNames).toContain("doctor");
    expect(turn.payloads[0].text).toBe("TOOLFACTORY_OK");
  }, 180_000);
});
