// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["e2e/**/*.e2e.test.ts"],
    testTimeout: 180_000,
    hookTimeout: 300_000,
  },
});
