/**
 * Coverage: one verdict per (operation × selected surface). Degradation is omission plus
 * an explanation, never a stub that fails at call time.
 */
import {
  isPortable,
  type Operation,
  type Project,
  type Surface,
  type SurfaceId,
  type Verdict,
} from "../model.js";

export interface CoverageRow {
  operation: string;
  verdicts: Record<string, Verdict>;
}

export interface Coverage {
  surfaces: SurfaceId[];
  rows: CoverageRow[];
}

export function defaultVerdict(operation: Operation): Verdict {
  return isPortable(operation)
    ? { kind: "native" }
    : {
        kind: "excluded",
        reason: `excluded:requires-${operation.requires.filter((c) => !["net", "fs", "shell", "secret"].includes(c)).join("+")}`,
      };
}

export function computeCoverage(project: Project, surfaces: Surface[]): Coverage {
  const rows = project.operations.map((operation) => ({
    operation: operation.name,
    verdicts: Object.fromEntries(
      surfaces.map((surface) => [
        surface.id,
        surface.verdict ? surface.verdict(operation, project) : defaultVerdict(operation),
      ]),
    ),
  }));
  return { surfaces: surfaces.map((s) => s.id), rows };
}

/** Operations that reach a surface (anything but `excluded`). */
export function includedOperations(project: Project, surface: Surface): Operation[] {
  return project.operations.filter((operation) => {
    const verdict = surface.verdict
      ? surface.verdict(operation, project)
      : defaultVerdict(operation);
    return verdict.kind !== "excluded";
  });
}

export function renderCoverageMarkdown(
  coverage: Coverage,
  manualFiles: string[],
  totalFiles: number,
): string {
  const header = `| operation | ${coverage.surfaces.join(" | ")} |`;
  const divider = `|---|${coverage.surfaces.map(() => "---").join("|")}|`;
  const cell = (verdict: Verdict) =>
    verdict.reason ? `${verdict.kind} (${verdict.reason.replace(/^[a-z]+:/, "")})` : verdict.kind;
  const rows = coverage.rows.map(
    (row) =>
      `| \`${row.operation}\` | ${coverage.surfaces.map((s) => cell(row.verdicts[s] ?? { kind: "excluded" })).join(" | ")} |`,
  );
  const manual =
    manualFiles.length === 0
      ? "All generated files are managed by toolfactory."
      : `${manualFiles.length} of ${totalFiles} managed files adopted as manual (${Math.round((100 * manualFiles.length) / Math.max(totalFiles, 1))}%): ${manualFiles.map((f) => `\`${f}\``).join(", ")}.`;
  return [
    "# Coverage",
    "",
    "Generated by `toolfactory build`. Verdicts per operation and surface: `native` (the surface runs it as-is), `bridged` (through a named bridge), `degraded` (present with a limit), `excluded` (omitted, with the reason).",
    "",
    header,
    divider,
    ...rows,
    "",
    manual,
    "",
  ].join("\n");
}
