/**
 * Python binding: the six language-specific things, as templates against upstream
 * packages only (`mcp` 2.x + pydantic 2, and the standard library for the CLI). The
 * kernel files under `src/<pkg>/toolfactory/` are regenerated on every build; the
 * author's `src/<pkg>/ops.py` is scaffolded once and then owned.
 */
import { stringify as toml } from "smol-toml";
import { projectName } from "../identity/name.js";
import type { PlannedFile, Project } from "../model.js";
import { compact, configProperties, has, pypiName } from "../surfaces/shared.js";

/** Import package: the canonical name with `.` and `-` folded to `_` (PEP 8 / PEP 503). */
export function pythonPackage(project: Project): string {
  return projectName.pythonPackage(project.identity.name);
}

export function kernelDir(project: Project): string {
  return `src/${pythonPackage(project)}/toolfactory`;
}

export function opsPath(project: Project): string {
  return `src/${pythonPackage(project)}/ops.py`;
}

export function cliEntryPoint(project: Project): string {
  return `${pythonPackage(project)}.toolfactory.cli:main`;
}

/** `uv run` syncs the project into `.venv` on first use, so no build step is needed. */
export function kernelCommand(project: Project): { command: string; args: string[] } {
  return {
    command: "uv",
    args: ["run", "--quiet", "python", "-m", `${pythonPackage(project)}.toolfactory.mcp`],
  };
}

/** The CLI counterpart of `kernelCommand`: same module path, `cli` instead of `mcp`. */
export function cliCommand(project: Project): { command: string; args: string[] } {
  return {
    command: "uv",
    args: ["run", "--quiet", "python", "-m", `${pythonPackage(project)}.toolfactory.cli`],
  };
}

const HEADER = "# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

function typesTemplate(): string {
  return `${HEADER}"""The operation contract: what an entry in \`OPERATIONS\` looks like."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from typing import Any, Literal

from pydantic import BaseModel

#: Host capabilities an operation may declare. Portable: net, fs, shell, secret.
Capability = Literal["net", "fs", "shell", "secret", "browser", "model", "user-input", "channel"]


@dataclass(frozen=True)
class Context:
    """Configuration read from the environment, keyed as declared in dev.toolfactory/tool.json."""

    config: dict[str, str | None]


@dataclass(frozen=True)
class Operation:
    """One operation: a pure function of (arguments, context.config, filesystem)."""

    name: str
    description: str
    input: type[BaseModel]
    handler: Callable[[Any, Context], Any]
    output: type[BaseModel] | None = None
    requires: tuple[Capability, ...] = ()
    annotations: dict[str, bool] = field(default_factory=dict)
`;
}

function initTemplate(): string {
  return `${HEADER}"""Generated kernel: the MCP server, the CLI, and the operation contract."""

from .types import Capability, Context, Operation

__all__ = ["Capability", "Context", "Operation"]
`;
}

function configTemplate(project: Project): string {
  const entries = Object.keys(configProperties(project)).map(
    (key) =>
      `            ${JSON.stringify(key)}: os.environ.get(${JSON.stringify(key.toUpperCase())}),\n`,
  );
  const body = entries.length ? `{\n${entries.join("")}        }` : "{}";
  return `${HEADER}"""Configuration is read from the environment; hosts inject it from their own settings UI."""

import os

from .types import Context


def context() -> Context:
    return Context(config=${body})
`;
}

function mcpTemplate(project: Project): string {
  return `${HEADER}"""The kernel MCP server: every operation registered from its pydantic input model."""

import inspect
from typing import Annotated, Any

from mcp.server.mcpserver import MCPServer

from ..ops import OPERATIONS
from .config import context
from .types import Operation

server = MCPServer(
    name=${JSON.stringify(project.identity.name)},
    version=${JSON.stringify(project.identity.version ?? "0.0.0")},
    description=${JSON.stringify(project.identity.description ?? project.identity.name)},
)


def bind(operation: Operation) -> Any:
    """Give the handler the signature of its input model, so the SDK publishes that schema."""
    parameters = [
        inspect.Parameter(
            name,
            inspect.Parameter.KEYWORD_ONLY,
            annotation=Annotated[spec.annotation, spec],
            default=inspect.Parameter.empty if spec.is_required() else spec.default,
        )
        for name, spec in operation.input.model_fields.items()
    ]

    async def call(**arguments: Any) -> Any:
        result = operation.handler(operation.input(**arguments), context())
        return await result if inspect.isawaitable(result) else result

    call.__name__ = operation.name
    call.__signature__ = inspect.Signature(
        parameters,
        return_annotation=operation.output if operation.output else inspect.Signature.empty,
    )
    return call


for operation in OPERATIONS:
    server.add_tool(
        bind(operation),
        name=operation.name,
        description=operation.description,
        annotations=operation.annotations or None,
        meta={"dev.toolfactory": {"requires": list(operation.requires)}},
    )


def serve() -> None:
    server.run("stdio")


if __name__ == "__main__":
    serve()
`;
}

function cliTemplate(project: Project): string {
  const mcpCommand = has(project, "mcp")
    ? `
    mcp = subcommands.add_parser("mcp", help="Serve the operations as an MCP server over stdio")
    mcp.set_defaults(tf_operation=None, tf_schema={})
`
    : "";
  const mcpDispatch = has(project, "mcp")
    ? `    if options.tf_operation is None:
        from .mcp import serve

        serve()
        return
`
    : "";
  return `${HEADER}"""The kernel CLI: one subcommand per operation, built from its input model's schema."""

import argparse
import asyncio
import inspect
import json
from typing import Any

from pydantic import BaseModel

from ..ops import OPERATIONS
from .config import context


def kind(schema: dict[str, Any]) -> str:
    """The JSON Schema type of a property, looking through the optional/nullable union."""
    if "type" in schema:
        return str(schema["type"])
    for variant in schema.get("anyOf", []):
        if variant.get("type") not in (None, "null"):
            return str(variant["type"])
    return "string"


def coerce(value: str, of: str) -> Any:
    if of in ("integer", "number"):
        return int(value) if of == "integer" else float(value)
    if of == "array":
        return [item.strip() for item in value.split(",") if item.strip()]
    if of == "object":
        return json.loads(value)
    return value


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(
        prog=${JSON.stringify(project.identity.name)},
        description=${JSON.stringify(project.identity.description ?? project.identity.name)},
    )
    subcommands = root.add_subparsers(dest="tf_command", required=True)
    for operation in OPERATIONS:
        schema = operation.input.model_json_schema()
        command = subcommands.add_parser(operation.name, help=operation.description)
        command.add_argument(
            "--json", dest="tf_json", metavar="JSON", help="all arguments as one JSON object"
        )
        for name, property in (schema.get("properties") or {}).items():
            of = kind(property)
            hint = {"array": " (comma-separated)", "object": " (JSON)"}.get(of, "")
            help_text = f"{property.get('description', name)}{hint}"
            if of == "boolean":
                command.add_argument(f"--{name}", action="store_true", default=None, help=help_text)
            else:
                command.add_argument(f"--{name}", metavar="VALUE", help=help_text)
        command.set_defaults(tf_operation=operation, tf_schema=schema)
${mcpCommand}    return root


def main(argv: list[str] | None = None) -> None:
    options = parser().parse_args(argv)
${mcpDispatch}    operation = options.tf_operation
    properties: dict[str, Any] = options.tf_schema.get("properties") or {}
    values: dict[str, Any] = json.loads(options.tf_json) if options.tf_json else {}
    for name, property in properties.items():
        given = getattr(options, name, None)
        if given is not None:
            values[name] = given if isinstance(given, bool) else coerce(given, kind(property))
    result = operation.handler(operation.input(**values), context())
    if inspect.isawaitable(result):
        result = asyncio.run(result)
    payload = result.model_dump(mode="json") if isinstance(result, BaseModel) else result
    print(json.dumps(payload, indent=2, default=str))


if __name__ == "__main__":
    main()
`;
}

function opsScaffold(): string {
  return `"""Your tool's operations: pure functions of (arguments, context.config, filesystem).

Declare \`requires\` for anything a host must provide; toolfactory decides per surface
whether that operation is native, bridged, degraded, or excluded.
"""

from pydantic import BaseModel, Field

from .toolfactory import Context, Operation


class EchoInput(BaseModel):
    text: str = Field(description="Text to echo back")


class EchoOutput(BaseModel):
    text: str


def echo(arguments: EchoInput, context: Context) -> EchoOutput:
    return EchoOutput(text=arguments.text)


OPERATIONS = [
    Operation(
        name="echo",
        description="Return the text you pass in.",
        input=EchoInput,
        output=EchoOutput,
        annotations={"readOnlyHint": True},
        handler=echo,
    ),
]
`;
}

/** Generated on every build. */
export function kernel(project: Project): PlannedFile[] {
  const dir = kernelDir(project);
  const files: PlannedFile[] = [
    { kind: "file", path: `${dir}/__init__.py`, content: initTemplate() },
    { kind: "file", path: `${dir}/types.py`, content: typesTemplate() },
    { kind: "file", path: `${dir}/config.py`, content: configTemplate(project) },
  ];
  if (has(project, "mcp"))
    files.push({ kind: "file", path: `${dir}/mcp.py`, content: mcpTemplate(project) });
  if (has(project, "cli"))
    files.push({ kind: "file", path: `${dir}/cli.py`, content: cliTemplate(project) });
  return files;
}

/** The `[project]` table the scaffold and the pypi surface agree on. */
export function projectTable(project: Project): Record<string, unknown> {
  const { identity } = project;
  return compact({
    name: pypiName(project),
    version: identity.version,
    description: identity.description,
    license: identity.license,
    keywords: identity.keywords,
    authors: identity.author?.name
      ? [compact({ name: identity.author.name, email: identity.author.email })]
      : undefined,
    urls:
      identity.homepage || identity.repository
        ? compact({ Homepage: identity.homepage, Repository: identity.repository })
        : undefined,
  });
}

const GITIGNORE = [".venv/", "dist/", "__pycache__/", ".env", ".env.*", "!.env.example", ""].join(
  "\n",
);

/** Written by `init` only when absent; owned by the author afterwards. */
export function scaffold(project: Project): PlannedFile[] {
  const pkg = pythonPackage(project);
  const pyproject = {
    project: {
      ...projectTable(project),
      "requires-python": ">=3.11",
      dependencies: ["mcp>=2,<3", "pydantic>=2"],
      ...(has(project, "cli")
        ? { scripts: { [project.identity.name]: cliEntryPoint(project) } }
        : {}),
    },
    "build-system": { requires: ["hatchling"], "build-backend": "hatchling.build" },
    tool: { hatch: { build: { targets: { wheel: { packages: [`src/${pkg}`] } } } } },
  };
  return [
    {
      kind: "file",
      path: `src/${pkg}/__init__.py`,
      content: `"""${project.identity.description ?? project.identity.name}"""\n`,
    },
    { kind: "file", path: opsPath(project), content: opsScaffold() },
    { kind: "file", path: "pyproject.toml", content: `${toml(pyproject)}\n` },
    { kind: "file", path: ".gitignore", content: GITIGNORE },
  ];
}
