/**
 * Python binding: the six language-specific things, as templates against upstream
 * packages only (`mcp` 2.x + pydantic 2, and the standard library for the CLI). The
 * kernel files under `src/<pkg>/toolfactory/` are regenerated on every build; the
 * author's `src/<pkg>/ops.py` is scaffolded once and then owned.
 */
import { stringify as toml } from "smol-toml";
import { projectName } from "../identity/name.js";
import type { PlannedFile, Project } from "../model.js";
import {
  compact,
  configProperties,
  dataDirEnvName,
  envName,
  has,
  liveCredentials,
  liveExample,
  pypiName,
} from "../surfaces/shared.js";

/** Import package: the canonical name with `.` and `-` folded to `_` (PEP 8 / PEP 503). */
export function pythonPackage(project: Project): string {
  return projectName.pythonPackage(project.identity.name);
}

export function kernelDir(project: Project): string {
  return `src/${pythonPackage(project)}/toolfactory`;
}

export function opsPath(project: Project): string {
  return `src/${pythonPackage(project)}/ops.py`;
}

export const LIVE_TEST_PATH = "tests/test_live.py";
/** What the `live` CI job runs; the author adds `--env-file .env` locally (documented in the file header). */
export const LIVE_TEST_COMMAND = `uv run --with pytest pytest -q ${LIVE_TEST_PATH}`;

const LIVE_GUARD_BEGIN = "# tf:live-guard";
const LIVE_GUARD_END = "# /tf:live-guard";

export function cliEntryPoint(project: Project): string {
  return `${pythonPackage(project)}.toolfactory.cli:main`;
}

/** `uv run` syncs the project into `.venv` on first use, so no build step is needed. */
export function kernelCommand(project: Project): { command: string; args: string[] } {
  return {
    command: "uv",
    args: ["run", "--quiet", "python", "-m", `${pythonPackage(project)}.toolfactory.mcp`],
  };
}

/** The CLI counterpart of `kernelCommand`: same module path, `cli` instead of `mcp`. */
export function cliCommand(project: Project): { command: string; args: string[] } {
  return {
    command: "uv",
    args: ["run", "--quiet", "python", "-m", `${pythonPackage(project)}.toolfactory.cli`],
  };
}

const HEADER = "# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

function typesTemplate(): string {
  return `${HEADER}"""The operation contract: what an entry in \`OPERATIONS\` looks like."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Literal

from pydantic import BaseModel

#: Host capabilities an operation may declare. Portable: net, fs, shell, secret.
Capability = Literal["net", "fs", "shell", "secret", "browser", "model", "user-input", "channel"]


@dataclass(frozen=True)
class Context:
    """Configuration read from the environment, keyed as declared in dev.toolfactory/tool.json."""

    config: dict[str, str | None]
    #: Directory this tool may keep its own state in. Created by the tool, not by the kernel.
    data_dir: Path


@dataclass(frozen=True)
class Operation:
    """One operation: a pure function of (arguments, context.config, filesystem)."""

    name: str
    description: str
    input: type[BaseModel]
    handler: Callable[[Any, Context], Any]
    output: type[BaseModel] | None = None
    requires: tuple[Capability, ...] = ()
    annotations: dict[str, bool] = field(default_factory=dict)

#: Capabilities every surface can satisfy on its own.
PORTABLE: frozenset[str] = frozenset({"net", "fs", "shell", "secret"})


def serves(operation: "Operation", surface: Literal["mcp", "cli"]) -> bool:
    """Whether a surface can run an operation: MCP needs a portable one; a CLI also has a human for user-input."""
    return all(c in PORTABLE or (surface == "cli" and c == "user-input") for c in operation.requires)
`;
}

function initTemplate(): string {
  return `${HEADER}"""Generated kernel: the MCP server, the CLI, and the operation contract."""

from .types import Capability, Context, Operation

__all__ = ["Capability", "Context", "Operation"]
`;
}

function configTemplate(project: Project): string {
  const entries = Object.keys(configProperties(project)).map(
    (key) =>
      `            ${JSON.stringify(key)}: os.environ.get(${JSON.stringify(envName(key))}),\n`,
  );
  const body = entries.length ? `{\n${entries.join("")}        }` : "{}";
  const name = project.identity.name;
  const dataDirEnv = dataDirEnvName(project);
  return `${HEADER}"""Configuration is read from the environment; hosts inject it from their own settings UI."""

import os
from pathlib import Path

from .types import Context


def data_dir() -> Path:
    """Where this tool may keep its own state: ${dataDirEnv} when a host sets it, else the
    platform's own data location (XDG on POSIX, %LOCALAPPDATA% on Windows)."""
    # Hosts that launch the kernel export their own name for it: Agent Plugins clients and
    # OpenClaw set PLUGIN_DATA, Claude Code sets CLAUDE_PLUGIN_DATA.
    configured = (
        os.environ.get(${JSON.stringify(dataDirEnv)})
        or os.environ.get("PLUGIN_DATA")
        or os.environ.get("CLAUDE_PLUGIN_DATA")
    )
    if configured:
        return Path(configured)
    if os.name == "nt":
        base = Path(os.environ.get("LOCALAPPDATA") or Path.home() / "AppData" / "Local")
    else:
        base = Path(os.environ.get("XDG_DATA_HOME") or Path.home() / ".local" / "share")
    return base / ${JSON.stringify(name)}


def context() -> Context:
    return Context(config=${body}, data_dir=data_dir())
`;
}

function mcpTemplate(project: Project): string {
  return `${HEADER}"""The kernel MCP server: every operation registered from its pydantic input model.

Serves over stdio by default; \`serve_http()\` (or the CLI's \`mcp --http [port]\`) serves the
same server over MCP streamable HTTP instead, via \`MCPServer.run(transport="streamable-http", ...)\`.
"""

import argparse
import inspect
import os
from typing import Annotated, Any

from mcp.server.mcpserver import MCPServer

from ..ops import OPERATIONS
from .config import context
from .types import Operation, serves

server = MCPServer(
    name=${JSON.stringify(project.identity.name)},
    version=${JSON.stringify(project.identity.version ?? "0.0.0")},
    description=${JSON.stringify(project.identity.description ?? project.identity.name)},
)


def bind(operation: Operation) -> Any:
    """Give the handler the signature of its input model, so the SDK publishes that schema."""
    parameters = [
        inspect.Parameter(
            name,
            inspect.Parameter.KEYWORD_ONLY,
            annotation=Annotated[spec.annotation, spec],
            default=inspect.Parameter.empty if spec.is_required() else spec.default,
        )
        for name, spec in operation.input.model_fields.items()
    ]

    async def call(**arguments: Any) -> Any:
        result = operation.handler(operation.input(**arguments), context())
        return await result if inspect.isawaitable(result) else result

    call.__name__ = operation.name
    call.__signature__ = inspect.Signature(
        parameters,
        return_annotation=operation.output if operation.output else inspect.Signature.empty,
    )
    return call


#: toolfactory introspects with every operation visible; a served instance lists only what MCP can run.
INTROSPECTING = bool(os.environ.get("TOOLFACTORY_INTROSPECT"))

for operation in OPERATIONS:
    if not INTROSPECTING and not serves(operation, "mcp"):
        continue
    server.add_tool(
        bind(operation),
        name=operation.name,
        description=operation.description,
        annotations=operation.annotations or None,
        meta={"dev.toolfactory": {"requires": list(operation.requires)}},
    )


def serve() -> None:
    server.run("stdio")


def serve_http(host: str = "127.0.0.1", port: int = 3000, path: str = "/mcp") -> None:
    """Serve over MCP streamable HTTP instead of stdio. Opt-in; stdio stays the default transport."""
    server.run("streamable-http", host=host, port=port, streamable_http_path=path, stateless_http=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--http",
        nargs="?",
        const=3000,
        type=int,
        default=None,
        metavar="PORT",
        help="serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
    )
    args = parser.parse_args()
    serve_http(port=args.http) if args.http is not None else serve()


if __name__ == "__main__":
    main()
`;
}

function cliTemplate(project: Project): string {
  const mcpCommand = has(project, "mcp")
    ? `
    mcp = subcommands.add_parser(
        "mcp", help="Serve the operations as an MCP server over stdio, or over streamable HTTP with --http"
    )
    mcp.add_argument(
        "--http",
        nargs="?",
        const=3000,
        type=int,
        default=None,
        metavar="PORT",
        help="serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
    )
    mcp.set_defaults(tf_operation=None, tf_schema={})
`
    : "";
  const mcpDispatch = has(project, "mcp")
    ? `    if options.tf_operation is None:
        if options.http is not None:
            from .mcp import serve_http

            serve_http(port=options.http)
        else:
            from .mcp import serve

            serve()
        return
`
    : "";
  return `${HEADER}"""The kernel CLI: one subcommand per operation, built from its input model's schema."""

import argparse
import asyncio
import inspect
import json
from typing import Any

from pydantic import BaseModel

from ..ops import OPERATIONS
from .types import serves
from .config import context


def kind(schema: dict[str, Any]) -> str:
    """The JSON Schema type of a property, looking through the optional/nullable union."""
    if "type" in schema:
        return str(schema["type"])
    for variant in schema.get("anyOf", []):
        if variant.get("type") not in (None, "null"):
            return str(variant["type"])
    return "string"


def coerce(value: str, of: str) -> Any:
    if of in ("integer", "number"):
        return int(value) if of == "integer" else float(value)
    if of == "array":
        return [item.strip() for item in value.split(",") if item.strip()]
    if of == "object":
        return json.loads(value)
    return value


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(
        prog=${JSON.stringify(project.identity.name)},
        description=${JSON.stringify(project.identity.description ?? project.identity.name)},
    )
    subcommands = root.add_subparsers(dest="tf_command", required=True)
    for operation in OPERATIONS:
        if not serves(operation, "cli"):
            continue
        schema = operation.input.model_json_schema()
        command = subcommands.add_parser(operation.name, help=operation.description)
        command.add_argument(
            "--json", dest="tf_json", metavar="JSON", help="all arguments as one JSON object"
        )
        for name, property in (schema.get("properties") or {}).items():
            of = kind(property)
            hint = {"array": " (comma-separated)", "object": " (JSON)"}.get(of, "")
            help_text = f"{property.get('description', name)}{hint}"
            if of == "boolean":
                command.add_argument(f"--{name}", action="store_true", default=None, help=help_text)
            else:
                command.add_argument(f"--{name}", metavar="VALUE", help=help_text)
        command.set_defaults(tf_operation=operation, tf_schema=schema)
${mcpCommand}    return root


def main(argv: list[str] | None = None) -> None:
    options = parser().parse_args(argv)
${mcpDispatch}    operation = options.tf_operation
    properties: dict[str, Any] = options.tf_schema.get("properties") or {}
    values: dict[str, Any] = json.loads(options.tf_json) if options.tf_json else {}
    for name, property in properties.items():
        given = getattr(options, name, None)
        if given is not None:
            values[name] = given if isinstance(given, bool) else coerce(given, kind(property))
    result = operation.handler(operation.input(**values), context())
    if inspect.isawaitable(result):
        result = asyncio.run(result)
    payload = result.model_dump(mode="json") if isinstance(result, BaseModel) else result
    print(json.dumps(payload, indent=2, default=str))


if __name__ == "__main__":
    main()
`;
}

function opsScaffold(): string {
  return `"""Your tool's operations: pure functions of (arguments, context.config, filesystem).

Declare \`requires\` for anything a host must provide; toolfactory decides per surface
whether that operation is native, bridged, degraded, or excluded.
"""

from pydantic import BaseModel, Field

from .toolfactory import Context, Operation


class EchoInput(BaseModel):
    text: str = Field(description="Text to echo back")


class EchoOutput(BaseModel):
    text: str


def echo(arguments: EchoInput, context: Context) -> EchoOutput:
    return EchoOutput(text=arguments.text)


OPERATIONS = [
    Operation(
        name="echo",
        description="Return the text you pass in.",
        input=EchoInput,
        output=EchoOutput,
        annotations={"readOnlyHint": True},
        handler=echo,
    ),
]
`;
}

/**
 * The T4 live tier: real calls against the real service, kept out of the default `pytest` run
 * by a generated guard over the credentials `tool.json` declares as required and sensitive.
 * The markers hold only the guard; the example test around them is the author's.
 */
export function liveTest(project: Project): PlannedFile[] {
  const credentials = liveCredentials(project).map(envName);
  const example = liveExample(project);
  if (credentials.length === 0 || !example) return [];
  const tuple = `(${credentials.map((name) => JSON.stringify(name)).join(", ")}${credentials.length === 1 ? "," : ""})`;
  const guard = `
CREDENTIALS = ${tuple}
LIVE = all(os.environ.get(name) for name in CREDENTIALS)
`;
  const pkg = pythonPackage(project);
  const template = `"""Live tests: real calls against the real service, so they run only when the credentials
(${credentials.join(", ")}) are in the environment — a plain \`pytest\` run skips them.

Locally: copy .env.example to .env, fill it in, then
    ${LIVE_TEST_COMMAND.replace("uv run ", "uv run --env-file .env ")}
In CI:   the \`live\` job of .github/workflows/ci.yml, from the \`live-tests\` environment.
"""

import asyncio
import inspect
import os

import pytest

from ${pkg}.ops import OPERATIONS
from ${pkg}.toolfactory.config import context

${LIVE_GUARD_BEGIN}${LIVE_GUARD_END}


@pytest.mark.skipif(not LIVE, reason=f"live credentials are not set: {', '.join(CREDENTIALS)}")
def test_${example.name.replace(/[^A-Za-z0-9_]/g, "_")}() -> None:
    operation = next(op for op in OPERATIONS if op.name == ${JSON.stringify(example.name)})
    result = operation.handler(
        operation.input.model_validate_json(${JSON.stringify(JSON.stringify(example.args))}), context()
    )
    if inspect.isawaitable(result):
        result = asyncio.run(result)
    # Replace this with the assertion that proves the real service answered correctly.
    assert result is not None
`;
  return [
    {
      kind: "region",
      path: LIVE_TEST_PATH,
      regions: [{ begin: LIVE_GUARD_BEGIN, end: LIVE_GUARD_END, content: guard }],
      template,
    },
  ];
}

/** Generated on every build. */
export function kernel(project: Project): PlannedFile[] {
  const dir = kernelDir(project);
  const files: PlannedFile[] = [
    { kind: "file", path: `${dir}/__init__.py`, content: initTemplate() },
    { kind: "file", path: `${dir}/types.py`, content: typesTemplate() },
    { kind: "file", path: `${dir}/config.py`, content: configTemplate(project) },
  ];
  files.push({ kind: "file", path: `${dir}/mcp.py`, content: mcpTemplate(project) });
  return files;
}

/** The CLI surface's file. */
export function cli(project: Project): PlannedFile[] {
  return [{ kind: "file", path: `${kernelDir(project)}/cli.py`, content: cliTemplate(project) }];
}

/** The `[project]` table the scaffold and the pypi surface agree on. */
export function projectTable(project: Project): Record<string, unknown> {
  const { identity } = project;
  return compact({
    name: pypiName(project),
    version: identity.version,
    description: identity.description,
    license: identity.license,
    keywords: identity.keywords,
    authors: identity.author?.name
      ? [compact({ name: identity.author.name, email: identity.author.email })]
      : undefined,
    urls:
      identity.homepage || identity.repository
        ? compact({ Homepage: identity.homepage, Repository: identity.repository })
        : undefined,
  });
}

/** Written by `init` only when absent; owned by the author afterwards. */
export function scaffold(project: Project): PlannedFile[] {
  const pkg = pythonPackage(project);
  const pyproject = {
    project: {
      ...projectTable(project),
      "requires-python": ">=3.11",
      dependencies: ["mcp>=2,<3", "pydantic>=2"],
      ...(has(project, "cli")
        ? { scripts: { [project.identity.name]: cliEntryPoint(project) } }
        : {}),
    },
    "build-system": { requires: ["hatchling"], "build-backend": "hatchling.build" },
    tool: { hatch: { build: { targets: { wheel: { packages: [`src/${pkg}`] } } } } },
  };
  return [
    {
      kind: "file",
      path: `src/${pkg}/__init__.py`,
      content: `"""${project.identity.description ?? project.identity.name}"""\n`,
    },
    { kind: "file", path: opsPath(project), content: opsScaffold() },
    { kind: "file", path: "pyproject.toml", content: `${toml(pyproject)}\n` },
  ];
}
