/**
 * TypeScript binding: the six language-specific things, as templates against upstream
 * SDKs only. The kernel files under `src/toolfactory/` are regenerated on every build; the
 * author's `src/ops.ts` is scaffolded once and then owned.
 */
import type { PlannedFile, Project } from "../model.js";
import { configProperties, has, npmName } from "../surfaces/shared.js";

export const KERNEL_DIR = "src/toolfactory";
export const OPS_PATH = "src/ops.ts";

export function kernelCommand(): { command: string; args: string[] } {
  return { command: "node", args: ["--import", "tsx", `${KERNEL_DIR}/mcp.ts`] };
}

export function cliCommand(): { command: string; args: string[] } {
  return { command: "node", args: ["--import", "tsx", `${KERNEL_DIR}/cli.ts`] };
}

const HEADER = "// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

function typesTemplate(): string {
  return `${HEADER}import type { z } from "zod";

/** Host capabilities an operation may declare. Portable: net, fs, shell, secret. */
export type Capability =
  | "net"
  | "fs"
  | "shell"
  | "secret"
  | "browser"
  | "model"
  | "user-input"
  | "channel";

export interface Context {
  /** Configuration values read from the environment, keyed as declared in dev.toolfactory/tool.json. */
  config: Record<string, string | undefined>;
}

export interface Operation<Input extends z.ZodObject = z.ZodObject, Output extends z.ZodType = z.ZodType> {
  name: string;
  description: string;
  input: Input;
  output?: Output;
  requires?: Capability[];
  annotations?: {
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    idempotentHint?: boolean;
    openWorldHint?: boolean;
  };
  handler: (args: z.infer<Input>, context: Context) => Promise<z.infer<Output>> | z.infer<Output>;
}

/** Identity function that pins the generic parameters so handlers are typed. */
export function operation<Input extends z.ZodObject, Output extends z.ZodType>(
  definition: Operation<Input, Output>,
): Operation<Input, Output> {
  return definition;
}
`;
}

function configTemplate(project: Project): string {
  const keys = Object.keys(configProperties(project));
  const entries = keys.map(
    (key) => `  ${JSON.stringify(key)}: process.env[${JSON.stringify(key.toUpperCase())}],`,
  );
  return `${HEADER}import type { Context } from "./types.js";

/** Configuration is read from the environment; hosts inject it from their own settings UI. */
export function context(): Context {
  return {
    config: {
${entries.join("\n")}
    },
  };
}
`;
}

function mcpTemplate(project: Project): string {
  return `${HEADER}import { McpServer } from "@modelcontextprotocol/server";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { z } from "zod";
import { operations } from "../ops.js";
import { context } from "./config.js";

export const server = new McpServer({ name: ${JSON.stringify(project.identity.name)}, version: ${JSON.stringify(project.identity.version ?? "0.0.0")} });

for (const op of operations) {
  server.registerTool(
    op.name,
    {
      description: op.description,
      inputSchema: op.input as z.ZodObject,
      outputSchema: (op.output ?? z.unknown()) as z.ZodType,
      annotations: op.annotations,
      _meta: { "dev.toolfactory": { requires: op.requires ?? [] } },
    },
    async (args: Record<string, unknown>) => {
      const result = await op.handler(args as never, context());
      return {
        resultType: "complete" as const,
        content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
        structuredContent: result as Record<string, unknown>,
      };
    },
  );
}

export async function serve(): Promise<void> {
  await server.connect(new StdioServerTransport());
}

if (process.argv[1] && /toolfactory[\\\\/]mcp\\.[cm]?[jt]s$/.test(process.argv[1])) {
  serve().catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
`;
}

function cliTemplate(project: Project): string {
  return `#!/usr/bin/env node
${HEADER}import { Command } from "commander";
import { z } from "zod";
import { operations } from "../ops.js";
import { context } from "./config.js";

const program = new Command()
  .name(${JSON.stringify(project.identity.name)})
  .description(${JSON.stringify(project.identity.description ?? project.identity.name)})
  .version(${JSON.stringify(project.identity.version ?? "0.0.0")});

for (const op of operations) {
  const command = program.command(op.name).description(op.description);
  command.option("--json <arguments>", "all arguments as one JSON object");
  const schema = z.toJSONSchema(op.input, { io: "input" }) as {
    properties?: Record<string, { description?: string; type?: string; default?: unknown }>;
  };
  for (const [key, property] of Object.entries(schema.properties ?? {})) {
    const flag = property.type === "boolean" ? \`--\${key}\` : \`--\${key} <value>\`;
    const hint = property.type === "array" ? " (comma-separated)" : property.type === "object" ? " (JSON)" : "";
    command.option(flag, \`\${property.description ?? key}\${hint}\`);
  }
  command.action(async (options: Record<string, string | boolean | undefined>) => {
    const fromJson = options.json ? (JSON.parse(String(options.json)) as Record<string, unknown>) : {};
    const fromFlags = Object.fromEntries(
      Object.entries(options)
        .filter(([key, value]) => key !== "json" && value !== undefined)
        .map(([key, value]) => {
          const type = schema.properties?.[key]?.type;
          if (type === "number" || type === "integer") return [key, Number(value)];
          if (type === "boolean") return [key, value === true || value === "true"];
          if (type === "array") return [key, String(value).split(",").map((item) => item.trim()).filter(Boolean)];
          if (type === "object") return [key, JSON.parse(String(value))];
          return [key, value];
        }),
    );
    const args = op.input.parse({ ...fromJson, ...fromFlags });
    const result = await op.handler(args as never, context());
    process.stdout.write(\`\${JSON.stringify(result, null, 2)}\\n\`);
  });
}

program
  .command("mcp")
  .description("Serve the operations as an MCP server over stdio")
  .action(async () => {
    const { serve } = await import("./mcp.js");
    await serve();
  });

program.parseAsync(process.argv).catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
`;
}

function opsScaffold(): string {
  return `import { z } from "zod";
import { operation } from "./toolfactory/types.js";

/**
 * Your tool's operations: pure functions of (arguments, context.config, filesystem).
 * Declare \`requires\` for anything a host must provide; toolfactory decides per surface
 * whether that operation is native, bridged, degraded, or excluded.
 */
export const operations = [
  operation({
    name: "echo",
    description: "Return the text you pass in.",
    input: z.object({ text: z.string().describe("Text to echo back") }),
    output: z.object({ text: z.string() }),
    annotations: { readOnlyHint: true },
    handler: async ({ text }) => ({ text }),
  }),
];
`;
}

/** Generated on every build. */
export function kernel(project: Project): PlannedFile[] {
  const files: PlannedFile[] = [
    { kind: "file", path: `${KERNEL_DIR}/types.ts`, content: typesTemplate() },
    { kind: "file", path: `${KERNEL_DIR}/config.ts`, content: configTemplate(project) },
  ];
  if (has(project, "mcp"))
    files.push({ kind: "file", path: `${KERNEL_DIR}/mcp.ts`, content: mcpTemplate(project) });
  if (has(project, "cli"))
    files.push({ kind: "file", path: `${KERNEL_DIR}/cli.ts`, content: cliTemplate(project) });
  return files;
}

const GITIGNORE = ["node_modules/", "dist/", ".env", ".env.*", "!.env.example", ""].join("\n");

/** Written by `init` only when absent; owned by the author afterwards. */
export function scaffold(project: Project): PlannedFile[] {
  const packageJson = {
    name: npmName(project),
    version: project.identity.version ?? "0.1.0",
    description: project.identity.description,
    license: project.identity.license,
    type: "module",
    engines: { node: ">=22" },
    scripts: { build: "tsc -p tsconfig.json", test: "vitest run --passWithNoTests" },
    dependencies: {
      "@modelcontextprotocol/server": "^2.0.0",
      commander: "^15.0.0",
      zod: "^4.0.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      toolfactory: `^${project.toolfactoryVersion}`,
      tsx: "^4.0.0",
      typescript: "^6.0.0",
      vitest: "^4.0.0",
    },
  };
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      declaration: true,
      outDir: "dist",
      rootDir: "src",
      skipLibCheck: true,
      types: ["node"],
    },
    include: ["src/**/*.ts"],
  };
  return [
    { kind: "file", path: OPS_PATH, content: opsScaffold() },
    { kind: "file", path: "package.json", content: `${JSON.stringify(packageJson, null, 2)}\n` },
    { kind: "file", path: "tsconfig.json", content: `${JSON.stringify(tsconfig, null, 2)}\n` },
    { kind: "file", path: ".gitignore", content: GITIGNORE },
  ];
}
