/**
 * TypeScript binding: the six language-specific things, as templates against upstream
 * SDKs only. The kernel files under `src/toolfactory/` are regenerated on every build; the
 * author's `src/ops.ts` is scaffolded once and then owned.
 */
import type { PlannedFile, Project } from "../model.js";
import {
  configProperties,
  dataDirEnvName,
  envName,
  has,
  liveCredentials,
  liveExample,
  npmName,
} from "../surfaces/shared.js";

export const KERNEL_DIR = "src/toolfactory";
export const OPS_PATH = "src/ops.ts";
export const LIVE_TEST_PATH = "tests/live.test.ts";
/**
 * The scaffold script the `live` CI job and the author both run (§6 T4). Node's own
 * `--env-file`, so no dotenv dependency (vitest does not put `.env` into `process.env`);
 * `-if-exists` so CI, which injects the same names from the `live-tests` environment rather
 * than a file, runs the same script; vitest's own entry file rather than `node_modules/.bin`,
 * which is a shell shim under pnpm and cannot be handed to `node`.
 */
export const LIVE_TEST_SCRIPT = `node --env-file-if-exists=.env node_modules/vitest/vitest.mjs run ${LIVE_TEST_PATH}`;

const LIVE_GUARD_BEGIN = "// tf:live-guard";
const LIVE_GUARD_END = "// /tf:live-guard";

export function kernelCommand(): { command: string; args: string[] } {
  return { command: "node", args: ["--import", "tsx", `${KERNEL_DIR}/mcp.ts`] };
}

export function cliCommand(): { command: string; args: string[] } {
  return { command: "node", args: ["--import", "tsx", `${KERNEL_DIR}/cli.ts`] };
}

const HEADER = "// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

function typesTemplate(): string {
  return `${HEADER}import type { z } from "zod";

/** Host capabilities an operation may declare. Portable: net, fs, shell, secret. */
export type Capability =
  | "net"
  | "fs"
  | "shell"
  | "secret"
  | "browser"
  | "model"
  | "user-input"
  | "channel";

export interface Context {
  /** Configuration values read from the environment, keyed as declared in dev.toolfactory/tool.json. */
  config: Record<string, string | undefined>;
  /** Directory this tool may keep its own state in. Created by the tool, not by the kernel. */
  dataDir: string;
}

export interface Operation<Input extends z.ZodObject = z.ZodObject, Output extends z.ZodType = z.ZodType> {
  name: string;
  description: string;
  input: Input;
  output?: Output;
  requires?: Capability[];
  annotations?: {
    readOnlyHint?: boolean;
    destructiveHint?: boolean;
    idempotentHint?: boolean;
    openWorldHint?: boolean;
  };
  handler: (args: z.infer<Input>, context: Context) => Promise<z.infer<Output>> | z.infer<Output>;
}

/** Identity function that pins the generic parameters so handlers are typed. */
export function operation<Input extends z.ZodObject, Output extends z.ZodType>(
  definition: Operation<Input, Output>,
): Operation<Input, Output> {
  return definition;
}

/** Capabilities every surface can satisfy on its own. */
export const PORTABLE: ReadonlySet<Capability> = new Set(["net", "fs", "shell", "secret"]);

/** Whether a surface can run an operation: MCP needs a portable one; a CLI also has a human for user-input. */
export function serves(operation: { requires?: Capability[] }, surface: "mcp" | "cli"): boolean {
  return (operation.requires ?? []).every(
    (capability) => PORTABLE.has(capability) || (surface === "cli" && capability === "user-input"),
  );
}
`;
}

function configTemplate(project: Project): string {
  const keys = Object.keys(configProperties(project));
  const entries = keys.map(
    (key) => `  ${JSON.stringify(key)}: process.env[${JSON.stringify(envName(key))}],`,
  );
  const name = project.identity.name;
  const dataDirEnv = dataDirEnvName(project);
  return `${HEADER}import { homedir } from "node:os";
import { join } from "node:path";
import type { Context } from "./types.js";

/**
 * Where this tool may keep its own state: ${dataDirEnv} when a host sets it, else the
 * platform's own data location (XDG on POSIX, %LOCALAPPDATA% on Windows).
 */
function dataDir(): string {
  // Hosts that launch the kernel export their own name for it: Agent Plugins clients and
  // OpenClaw set PLUGIN_DATA, Claude Code sets CLAUDE_PLUGIN_DATA.
  const configured =
    process.env[${JSON.stringify(dataDirEnv)}] ??
    process.env.PLUGIN_DATA ??
    process.env.CLAUDE_PLUGIN_DATA;
  if (configured) return configured;
  const base =
    process.platform === "win32"
      ? (process.env.LOCALAPPDATA ?? join(homedir(), "AppData", "Local"))
      : (process.env.XDG_DATA_HOME ?? join(homedir(), ".local", "share"));
  return join(base, ${JSON.stringify(name)});
}

/** Configuration is read from the environment; hosts inject it from their own settings UI. */
export function context(): Context {
  return {
    config: {
${entries.join("\n")}
    },
    dataDir: dataDir(),
  };
}
`;
}

/**
 * The T4 live tier: real calls against the real service, kept out of the default `vitest run`
 * by a generated guard over the credentials `tool.json` declares as required and sensitive.
 * The markers hold only the guard; the example test around them is the author's.
 */
export function liveTest(project: Project): PlannedFile[] {
  const credentials = liveCredentials(project).map(envName);
  const example = liveExample(project);
  if (credentials.length === 0 || !example) return [];
  const guard = `
const CREDENTIALS = ${JSON.stringify(credentials)};
const live = CREDENTIALS.every((name) => process.env[name]);
`;
  const template = `/**
 * Live tests: real calls against the real service, so they run only when the credentials
 * (${credentials.join(", ")}) are in the environment — \`npm test\` skips them.
 *
 * Locally: copy .env.example to .env, fill it in, then \`npm run test:live\`.
 * In CI:   the \`live\` job of .github/workflows/ci.yml, from the \`live-tests\` environment.
 */
import { describe, expect, it } from "vitest";
import { operations } from "../src/ops.js";
import { context } from "../src/toolfactory/config.js";

${LIVE_GUARD_BEGIN}${LIVE_GUARD_END}

describe.skipIf(!live)(${JSON.stringify(`${project.identity.name} against the real service`)}, () => {
  it(${JSON.stringify(`${example.name} answers`)}, async () => {
    const operation = operations.find((candidate) => candidate.name === ${JSON.stringify(example.name)});
    if (!operation) throw new Error(${JSON.stringify(`no operation named ${example.name}; point this test at another one`)});
    const result = await operation.handler(${JSON.stringify(example.args)} as never, context());
    // Replace this with the assertion that proves the real service answered correctly.
    expect(result).toBeDefined();
  });
});
`;
  return [
    {
      kind: "region",
      path: LIVE_TEST_PATH,
      regions: [{ begin: LIVE_GUARD_BEGIN, end: LIVE_GUARD_END, content: guard }],
      template,
    },
  ];
}

function mcpTemplate(project: Project): string {
  return `${HEADER}/**
 * The kernel MCP server: stdio by default; \`--http [port]\` (or \`serveHttp()\`) serves the
 * same operations over MCP streamable HTTP instead, stateless per MCP 2026-07-28 (a fresh
 * server instance per request, from \`createMcpHandler\`).
 */
import { localhostHostValidation, toNodeHandler } from "@modelcontextprotocol/node";
import { createMcpHandler, McpServer } from "@modelcontextprotocol/server";
import { StdioServerTransport } from "@modelcontextprotocol/server/stdio";
import { createServer as createHttpServer } from "node:http";
import { z } from "zod";
import { operations } from "../ops.js";
import { context } from "./config.js";
import { serves } from "./types.js";

/** toolfactory introspects with every operation visible; a served instance lists only what MCP can run. */
const introspecting = Boolean(process.env.TOOLFACTORY_INTROSPECT);

/** Builds one server instance with every servable operation registered; called once for stdio, once per HTTP request. */
function createServer(): McpServer {
  const server = new McpServer({ name: ${JSON.stringify(project.identity.name)}, version: ${JSON.stringify(project.identity.version ?? "0.0.0")} });
  for (const op of operations) {
    if (!introspecting && !serves(op, "mcp")) continue;
    server.registerTool(
      op.name,
      {
        description: op.description,
        inputSchema: op.input as z.ZodObject,
        outputSchema: (op.output ?? z.unknown()) as z.ZodType,
        annotations: op.annotations,
        _meta: { "dev.toolfactory": { requires: op.requires ?? [] } },
      },
      async (args: Record<string, unknown>) => {
        const result = await op.handler(args as never, context());
        return {
          resultType: "complete" as const,
          content: [{ type: "text" as const, text: JSON.stringify(result, null, 2) }],
          structuredContent: result as Record<string, unknown>,
        };
      },
    );
  }
  return server;
}

export const server = createServer();

export async function serve(): Promise<void> {
  await server.connect(new StdioServerTransport());
}

export interface HttpOptions {
  port?: number;
  host?: string;
  path?: string;
}

/** Serve over MCP streamable HTTP instead of stdio. Opt-in; stdio stays the default transport. */
export async function serveHttp(options: HttpOptions = {}): Promise<void> {
  const { port = 3000, host = "127.0.0.1", path = "/mcp" } = options;
  const handle = toNodeHandler(createMcpHandler(createServer));
  const loopback = host === "127.0.0.1" || host === "localhost" || host === "::1";
  const hostGuard = loopback ? localhostHostValidation() : undefined;
  const base = \`http://\${host}:\${port}\`;
  const httpServer = createHttpServer((req, res) => {
    if (new URL(req.url ?? "/", base).pathname !== path) {
      res.writeHead(404).end();
      return;
    }
    if (hostGuard && !hostGuard(req, res)) return;
    handle(req, res).catch((error: unknown) => {
      console.error(error);
      if (!res.headersSent) res.writeHead(500);
      res.end();
    });
  });
  await new Promise<void>((resolve, reject) => {
    httpServer.once("error", reject);
    httpServer.listen(port, host, resolve);
  });
  console.error(\`Serving MCP streamable HTTP on \${base}\${path}\`);
}

/** Parses a manually-run \`node mcp.ts [--http [port]]\` invocation; the CLI's \`mcp\` subcommand parses its own. */
function httpPortArg(argv: string[]): number | undefined {
  const index = argv.indexOf("--http");
  if (index === -1) return undefined;
  const value = argv[index + 1];
  return value && !value.startsWith("-") ? Number(value) : 3000;
}

if (process.argv[1] && /toolfactory[\\\\/]mcp\\.[cm]?[jt]s$/.test(process.argv[1])) {
  const port = httpPortArg(process.argv.slice(2));
  (port === undefined ? serve() : serveHttp({ port })).catch((error) => {
    console.error(error);
    process.exit(1);
  });
}
`;
}

function cliTemplate(project: Project): string {
  return `#!/usr/bin/env node
${HEADER}import { Command } from "commander";
import { z } from "zod";
import { operations } from "../ops.js";
import { context } from "./config.js";
import { serves } from "./types.js";

const program = new Command()
  .name(${JSON.stringify(project.identity.name)})
  .description(${JSON.stringify(project.identity.description ?? project.identity.name)})
  .version(${JSON.stringify(project.identity.version ?? "0.0.0")});

for (const op of operations) {
  if (!serves(op, "cli")) continue;
  const command = program.command(op.name).description(op.description);
  command.option("--json <arguments>", "all arguments as one JSON object");
  const schema = z.toJSONSchema(op.input, { io: "input" }) as {
    properties?: Record<string, { description?: string; type?: string; default?: unknown }>;
  };
  for (const [key, property] of Object.entries(schema.properties ?? {})) {
    const flag = property.type === "boolean" ? \`--\${key}\` : \`--\${key} <value>\`;
    const hint = property.type === "array" ? " (comma-separated)" : property.type === "object" ? " (JSON)" : "";
    command.option(flag, \`\${property.description ?? key}\${hint}\`);
  }
  command.action(async (options: Record<string, string | boolean | undefined>) => {
    const fromJson = options.json ? (JSON.parse(String(options.json)) as Record<string, unknown>) : {};
    const fromFlags = Object.fromEntries(
      Object.entries(options)
        .filter(([key, value]) => key !== "json" && value !== undefined)
        .map(([key, value]) => {
          const type = schema.properties?.[key]?.type;
          if (type === "number" || type === "integer") return [key, Number(value)];
          if (type === "boolean") return [key, value === true || value === "true"];
          if (type === "array") return [key, String(value).split(",").map((item) => item.trim()).filter(Boolean)];
          if (type === "object") return [key, JSON.parse(String(value))];
          return [key, value];
        }),
    );
    const args = op.input.parse({ ...fromJson, ...fromFlags });
    const result = await op.handler(args as never, context());
    process.stdout.write(\`\${JSON.stringify(result, null, 2)}\\n\`);
  });
}

${
  has(project, "mcp")
    ? `program
  .command("mcp")
  .description("Serve the operations as an MCP server over stdio, or over streamable HTTP with --http")
  .option(
    "--http [port]",
    "serve over MCP streamable HTTP instead of stdio (default port 3000, host 127.0.0.1, path /mcp)",
  )
  .action(async (options: { http?: string | boolean }) => {
    const { serve, serveHttp } = await import("./mcp.js");
    if (options.http === undefined) await serve();
    else await serveHttp({ port: options.http === true ? 3000 : Number(options.http) });
  });

`
    : ""
}program.parseAsync(process.argv).catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
`;
}

function opsScaffold(): string {
  return `import { z } from "zod";
import { operation } from "./toolfactory/types.js";

/**
 * Your tool's operations: pure functions of (arguments, context.config, filesystem).
 * Declare \`requires\` for anything a host must provide; toolfactory decides per surface
 * whether that operation is native, bridged, degraded, or excluded.
 */
export const operations = [
  operation({
    name: "echo",
    description: "Return the text you pass in.",
    input: z.object({ text: z.string().describe("Text to echo back") }),
    output: z.object({ text: z.string() }),
    annotations: { readOnlyHint: true },
    handler: async ({ text }) => ({ text }),
  }),
];
`;
}

/** The kernel, generated on every build for every tool: the contract, config, and the MCP server toolfactory introspects. */
export function kernel(project: Project): PlannedFile[] {
  return [
    { kind: "file", path: `${KERNEL_DIR}/types.ts`, content: typesTemplate() },
    { kind: "file", path: `${KERNEL_DIR}/config.ts`, content: configTemplate(project) },
    { kind: "file", path: `${KERNEL_DIR}/mcp.ts`, content: mcpTemplate(project) },
  ];
}

/** The CLI surface's file. */
export function cli(project: Project): PlannedFile[] {
  return [{ kind: "file", path: `${KERNEL_DIR}/cli.ts`, content: cliTemplate(project) }];
}

const GITIGNORE = ["node_modules/", "dist/", ".env", ".env.*", "!.env.example", ""].join("\n");

/** Written by `init` only when absent; owned by the author afterwards. */
export function scaffold(project: Project): PlannedFile[] {
  const packageJson = {
    name: npmName(project),
    version: project.identity.version ?? "0.1.0",
    description: project.identity.description,
    license: project.identity.license,
    type: "module",
    engines: { node: ">=22.12" },
    scripts: {
      build: "tsc -p tsconfig.json",
      test: "vitest run --passWithNoTests",
      "test:live": LIVE_TEST_SCRIPT,
    },
    dependencies: {
      "@modelcontextprotocol/node": "^2.0.0",
      "@modelcontextprotocol/server": "^2.0.0",
      commander: "^15.0.0",
      zod: "^4.0.0",
    },
    devDependencies: {
      "@types/node": "^22.0.0",
      toolfactory: `^${project.toolfactoryVersion}`,
      tsx: "^4.0.0",
      typescript: "^6.0.0",
      vitest: "^4.0.0",
    },
  };
  const tsconfig = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      declaration: true,
      outDir: "dist",
      rootDir: "src",
      skipLibCheck: true,
      types: ["node"],
    },
    include: ["src/**/*.ts"],
  };
  return [
    { kind: "file", path: OPS_PATH, content: opsScaffold() },
    { kind: "file", path: "package.json", content: `${JSON.stringify(packageJson, null, 2)}\n` },
    { kind: "file", path: "tsconfig.json", content: `${JSON.stringify(tsconfig, null, 2)}\n` },
    { kind: "file", path: ".gitignore", content: GITIGNORE },
  ];
}
