# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
"""Hermes plugin for toolfactory, registered through PluginContext.

Every handler returns a JSON string and never raises: Hermes dispatches tool
calls without a guard of its own, so an exception here escapes into the turn.
"""

from __future__ import annotations

import json
import os
import subprocess
from pathlib import Path
from typing import Any, Callable

TOOLSET = "toolfactory"
REQUIRES_ENV = []
TOOLS = json.loads(
    r"""[
  {
    "name": "adopt",
    "description": "Stop regenerating one file; it becomes the author's (recorded as manual in the lock).",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "path": {
          "type": "string",
          "description": "Repo-relative path of a generated file"
        }
      },
      "required": [
        "path"
      ]
    }
  },
  {
    "name": "bootstrap-repo",
    "description": "Prepare the GitHub repository for the live-test tier: create the `live-tests` environment with required reviewers, then set every required sensitive config key as an environment secret from the local .env.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "reviewers": {
          "default": [],
          "description": "GitHub logins that must approve a live run",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "dryRun": {
          "default": false,
          "description": "Print the gh invocations instead of running them",
          "type": "boolean"
        }
      }
    }
  },
  {
    "name": "build",
    "description": "Generate every selected surface in-tree from the identity file and the operation snapshot, and refresh the lock.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "check",
    "description": "Fail if the operation snapshot or any generated file drifted from the code (the CI drift gate).",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "coverage",
    "description": "The operation × surface verdict matrix: native, bridged, degraded, or excluded, with reasons.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "doctor",
    "description": "Report which upstream CLIs this machine can delegate to (git, gh, npm, uv, claude, openclaw, clawhub, hermes, uvx, agentskills, MCP Inspector, docker).",
    "parameters": {
      "type": "object",
      "properties": {}
    }
  },
  {
    "name": "eject",
    "description": "Adopt every file a surface owns, so the author takes it over entirely.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "surface": {
          "type": "string",
          "enum": [
            "skill",
            "agent-plugins",
            "claude",
            "codex",
            "cursor",
            "mcp",
            "mcp-registry",
            "cli",
            "npm",
            "pypi",
            "openclaw-native",
            "hermes-native",
            "clawhub",
            "web",
            "dsh",
            "workflows",
            "agents",
            "readme",
            "gemini",
            "mcpb",
            "browser-extension"
          ]
        }
      },
      "required": [
        "surface"
      ]
    }
  },
  {
    "name": "gate",
    "description": "Run the gate here, in order: build, the drift check, every selected surface's upstream validator, the author's checks and tests, and the credential-free host end-to-end. The same step list the generated ci.yml renders, so a project with no CI has the identical gate.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "init",
    "description": "Create a new tool: dev.toolfactory/tool.json, the authored identity file, the kernel scaffold for the chosen language, and the first build of every selected surface.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "name": {
          "type": "string",
          "description": "Tool name: lowercase letters, digits, hyphens, dots (Agent Plugins rule)"
        },
        "binding": {
          "type": "string",
          "enum": [
            "typescript",
            "python"
          ],
          "description": "Language of the core logic: typescript or python"
        },
        "surfaces": {
          "minItems": 1,
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "skill",
              "agent-plugins",
              "claude",
              "codex",
              "cursor",
              "mcp",
              "mcp-registry",
              "cli",
              "npm",
              "pypi",
              "openclaw-native",
              "hermes-native",
              "clawhub",
              "web",
              "dsh",
              "workflows",
              "agents",
              "readme",
              "gemini",
              "mcpb",
              "browser-extension"
            ]
          },
          "description": "Surfaces to generate"
        },
        "description": {
          "description": "One-line description",
          "type": "string"
        },
        "license": {
          "description": "SPDX license identifier",
          "type": "string"
        },
        "repository": {
          "description": "Source repository URL (GitHub URL enables the MCP Registry name)",
          "type": "string"
        },
        "author": {
          "description": "Author name",
          "type": "string"
        },
        "keywords": {
          "description": "Activation triggers for hosts that key off them (Kiro Powers, Agent Plugins); defaults to [name]",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "git": {
          "default": true,
          "description": "git init when the directory is not a repository yet, and make the first commit",
          "type": "boolean"
        },
        "setup": {
          "default": true,
          "description": "Run .agents/setup: render the harness adapters, install the git hooks, install dependencies",
          "type": "boolean"
        },
        "repo": {
          "description": "owner/name of a GitHub repository to create with gh and push to",
          "type": "string"
        },
        "public": {
          "default": false,
          "description": "Create that repository public, not private",
          "type": "boolean"
        },
        "dryRun": {
          "default": false,
          "description": "Print the gh invocations instead of running them",
          "type": "boolean"
        },
        "reviewers": {
          "default": [],
          "description": "GitHub logins that must approve a live run, when the repository gets a live tier",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "name",
        "binding",
        "surfaces"
      ]
    }
  },
  {
    "name": "introspect",
    "description": "Spawn the kernel MCP server, list its tools, and snapshot them to dev.toolfactory/ops.json.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "package",
    "description": "Build every release asset into dist/release/ — npm tarball, Python distributions, OpenClaw plugin tarball, plugin bundle zip, web build, coverage — by the same steps the release workflow's package job runs. Publishing stays a CI concern.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        }
      }
    }
  },
  {
    "name": "unadopt",
    "description": "Return an adopted file to toolfactory and regenerate it.",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "path": {
          "type": "string",
          "description": "Repo-relative path of an adopted file"
        }
      },
      "required": [
        "path"
      ]
    }
  },
  {
    "name": "validate",
    "description": "Run each selected surface's own upstream validator (agentskills, claude plugin validate, MCP Inspector, openclaw, hermes, npm pack, uv build).",
    "parameters": {
      "type": "object",
      "properties": {
        "root": {
          "default": ".",
          "description": "Project root (directory containing dev.toolfactory/)",
          "type": "string"
        },
        "surface": {
          "description": "Only this surface",
          "type": "string",
          "enum": [
            "skill",
            "agent-plugins",
            "claude",
            "codex",
            "cursor",
            "mcp",
            "mcp-registry",
            "cli",
            "npm",
            "pypi",
            "openclaw-native",
            "hermes-native",
            "clawhub",
            "web",
            "dsh",
            "workflows",
            "agents",
            "readme",
            "gemini",
            "mcpb",
            "browser-extension"
          ]
        }
      }
    }
  }
]"""
)


def _ready() -> bool:
    """Hermes gates dispatch on this: every declared credential has to be present."""
    return all(os.environ.get(name) for name in REQUIRES_ENV)


#: The plugin sits at <repo>/hosts/hermes/<package>, so in a checkout the root is
#: three levels up; once Hermes has copied the plugin into $HERMES_HOME/plugins,
#: TOOLFACTORY_ROOT is how the operator says where it went.
_ROOT = os.environ.get("TOOLFACTORY_ROOT")
REPO_ROOT = Path(_ROOT) if _ROOT else Path(__file__).resolve().parents[3]
KERNEL = ["node", "--import", "tsx", "src/toolfactory/cli.ts"]



def _handler(name: str) -> Callable[..., str]:
    def call(args: dict, **_kwargs: Any) -> str:
        try:
            done = subprocess.run(
                [*KERNEL, name, "--json", json.dumps(args)],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                check=True,
            )
            return done.stdout.strip()
        except subprocess.CalledProcessError as exc:
            detail = (exc.stderr or exc.stdout or "").strip()
            return json.dumps({"error": detail or f"{name} exited {exc.returncode}"})
        except Exception as exc:
            return json.dumps({"error": str(exc)})

    call.__name__ = f"{name}_handler"
    return call


def register(ctx: Any) -> None:
    # Hermes' own per-plugin data directory, through the variable every host uses.
    os.environ.setdefault("TOOLFACTORY_DATA_DIR", str(ctx.state.data_dir))
    for schema in TOOLS:
        ctx.register_tool(
            name=schema["name"],
            toolset=TOOLSET,
            schema=schema,
            handler=_handler(schema["name"]),
            check_fn=_ready,
            requires_env=list(REQUIRES_ENV),
            description=schema["description"],
        )
