/**
 * OpenClaw native plugin — the §4.4 escape hatch. The package under `hosts/openclaw/` is the
 * scaffold `openclaw plugins init <id> --type tool` writes, with the tool list projected from
 * the operations OpenClaw can actually run.
 *
 * A plugin that contributes something other than tools (a realtime-voice provider, a speech
 * provider) is the same package: `defineToolPlugin` keeps the upstream build/validate gates,
 * and the host registrations it declares in `tool.json` (`openclaw.registers`) drive the
 * manifest contracts, the plugin inspector's expectations and the generated test. The one
 * thing toolfactory cannot write is the registration body, so `src/index.ts` is a region file:
 * toolfactory owns the entry, the author owns the tail that wires the registrations.
 *
 * §8 C2 ("mirror scaffolds by execution, not transcription"): `plan()` is pure and therefore
 * has to carry the scaffold's constants, so `validate()` runs the real generator and fails when
 * any of them drifted. Every pinned value lives in OPENCLAW_SCAFFOLD below and nowhere else.
 */
import { execArgv } from "node:process";
import { DRIFT_ENTRY } from "../hosts/openclaw.js";
import { projectName } from "../identity/name.js";
import { isPortable, type Operation, type Project, type Surface, type Verdict } from "../model.js";
import { includedOperations, type Registration } from "../report/coverage.js";
import {
  compact,
  configProperties,
  dataDirEnvName,
  isSensitive,
  json,
  npmName,
  rootEnvName,
} from "./shared.js";

/** Transcribed from `openclaw plugins init --type tool`; `validate()` proves them still current. */
export const OPENCLAW_SCAFFOLD = {
  /** The OpenClaw release the scaffold was taken from (`package.json openclaw.build`). */
  openclawVersion: "2026.8.2",
  /** `peerDependencies.openclaw` and `openclaw.compat.pluginApi`. */
  pluginApi: ">=2026.5.17",
  private: true,
  scripts: {
    build: "tsc -p tsconfig.json",
    "plugin:build": "npm run build && openclaw plugins build --entry ./dist/index.js",
    "plugin:validate": "npm run build && openclaw plugins validate --entry ./dist/index.js",
    test: "vitest run --config ./vitest.config.ts",
  },
  files: ["dist", "openclaw.plugin.json", "README.md"],
  dependencies: { typebox: "^1.1.38" },
  devDependencies: { openclaw: "latest", typescript: "^5.9.0", vitest: "^3.2.0" },
  tsconfig: {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      declaration: true,
      outDir: "dist",
      skipLibCheck: true,
    },
    include: ["src/**/*.ts"],
  },
  vitestConfig: `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
  },
});
`,
  /** Entry module, relative to the plugin root, as `openclaw.extensions` records it. */
  entry: "./dist/index.js",
  sdkModule: "openclaw/plugin-sdk/tool-plugin",
  /** `resolveStateDir()`: the directory OpenClaw keeps its own state in. */
  statePathsModule: "openclaw/plugin-sdk/state-paths",
  /** Where `OpenClawPluginApi` and every registrar's parameter type come from. */
  entryModule: "openclaw/plugin-sdk/plugin-entry",
  /** `pluginInspector` in package.json, as `--type provider` writes it. */
  inspector: { version: 1, priority: "high", seams: ["plugin-runtime"], sourceRoot: "." },
} as const;

export const HOST_DIR = "hosts/openclaw";

const HEADER = "// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

/** The region of `src/index.ts` toolfactory owns; the tail below the end marker is the author's. */
export const ENTRY_BEGIN = "// tf:entry";
export const ENTRY_END = "// /tf:entry";

/** `titleFromId` from OpenClaw's scaffold generator. */
export function displayName(id: string): string {
  return projectName.display(id);
}

/** Host registrations the plugin declares beyond tools. */
export function registrations(project: Project): Registration[] {
  return project.tool.openclaw?.registers ?? [];
}

/** `activation` for both the entry and the manifest; OpenClaw's own default is startup. */
export function activation(project: Project): Record<string, unknown> {
  return project.tool.openclaw?.activation ?? { onStartup: true };
}

/**
 * OpenClaw stores `normalizeJsonSchema(schema)` in the plugin manifest, so emit schemas that are
 * already in that shape and `openclaw plugins build --check` stays a byte-for-byte agreement.
 */
export function normalizeSchema(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeSchema);
  if (!value || typeof value !== "object") return value;
  const record = { ...(value as Record<string, unknown>) };
  delete record.$schema;
  for (const [key, nested] of Object.entries(record)) record[key] = normalizeSchema(nested);
  const propertyNames = record.propertyNames as Record<string, unknown> | undefined;
  if (propertyNames && typeof propertyNames === "object" && propertyNames.type === "string") {
    delete record.propertyNames;
  }
  if (Array.isArray(record.required) && record.required.length === 0) delete record.required;
  return record;
}

/** A JSON value as a TypeScript literal, re-indented to sit at `indent` columns. */
function literal(value: unknown, indent: number): string {
  return JSON.stringify(value, null, 2).replaceAll("\n", `\n${" ".repeat(indent)}`);
}

/** `EMPTY_TOOL_PLUGIN_CONFIG_SCHEMA` from the SDK: what a plugin with no config schema reports. */
const EMPTY_CONFIG_SCHEMA = { type: "object", properties: {}, additionalProperties: false };

function hasConfig(project: Project): boolean {
  return Boolean(project.tool.config) && Object.keys(configProperties(project)).length > 0;
}

/** The plugin's `configSchema`: the tool's own config schema, or OpenClaw's empty default. */
export function configSchema(project: Project): Record<string, unknown> {
  return hasConfig(project)
    ? (normalizeSchema(project.tool.config) as Record<string, unknown>)
    : EMPTY_CONFIG_SCHEMA;
}

function pluginDescription(project: Project): string {
  return (
    project.identity.description ?? `Add ${displayName(project.identity.name)} tools to OpenClaw.`
  );
}

function verdict(operation: Operation, project: Project): Verdict {
  if (!isPortable(operation)) return { kind: "excluded", reason: "excluded:implement-in-hosts" };
  return project.tool.binding === "typescript"
    ? { kind: "native" }
    : { kind: "degraded", reason: "degraded:out-of-process" };
}

/** The API range the plugin declares; the author's `pluginApi` wins over the scaffold's. */
function pluginApi(project: Project): string {
  return project.tool.openclaw?.pluginApi ?? OPENCLAW_SCAFFOLD.pluginApi;
}

/** The manifest contract keys the plugin fills: `tools` when it has any, plus every declared one. */
function contractKeys(project: Project, operations: Operation[]): string[] {
  const declared = registrations(project).map((registration) => registration.contract);
  return [...new Set([...(operations.length ? ["tools"] : []), ...declared])];
}

/**
 * The inspector fixture, in the shape `--type provider` writes: it re-derives the registrations
 * from the source and the contracts from the manifest, so a declaration nobody wired fails
 * `plugin-inspector inspect --check` by name.
 */
function pluginInspector(project: Project, operations: Operation[]): Record<string, unknown> {
  return {
    version: OPENCLAW_SCAFFOLD.inspector.version,
    plugin: {
      id: project.identity.name,
      priority: OPENCLAW_SCAFFOLD.inspector.priority,
      seams: OPENCLAW_SCAFFOLD.inspector.seams,
      sourceRoot: OPENCLAW_SCAFFOLD.inspector.sourceRoot,
      expect: {
        registrations: registrations(project).map((registration) => registration.api),
        manifestContracts: contractKeys(project, operations),
      },
    },
  };
}

function packageJson(project: Project, operations: Operation[]): string {
  // The core is imported in-process only when an operation reaches this surface.
  const core =
    project.tool.binding === "typescript" && operations.length
      ? { [npmName(project)]: "file:../.." }
      : undefined;
  const extra = project.tool.openclaw;
  return json(
    compact({
      name: projectName.openclawPackage(project.identity.name),
      version: project.identity.version ?? "0.0.0",
      description: pluginDescription(project),
      type: "module",
      private: OPENCLAW_SCAFFOLD.private,
      scripts: OPENCLAW_SCAFFOLD.scripts,
      files: OPENCLAW_SCAFFOLD.files,
      peerDependencies: { openclaw: pluginApi(project), ...extra?.peerDependencies },
      dependencies: { ...OPENCLAW_SCAFFOLD.dependencies, ...core, ...extra?.dependencies },
      devDependencies: { ...OPENCLAW_SCAFFOLD.devDependencies, ...extra?.devDependencies },
      openclaw: {
        extensions: [OPENCLAW_SCAFFOLD.entry],
        compat: { pluginApi: pluginApi(project) },
        build: { openclawVersion: OPENCLAW_SCAFFOLD.openclawVersion },
      },
      pluginInspector: registrations(project).length
        ? pluginInspector(project, operations)
        : undefined,
    }),
  );
}

/**
 * `openclaw plugins build` regenerates this file; emitting it keeps `--check` green from a clean
 * tree. The builder owns `contracts.tools` and preserves every other contract key, so a declared
 * registration's ids survive a rebuild. `uiHints` is manifest-owned too: it is how OpenClaw's
 * config UI learns which keys to mask, from the same `x-toolfactory.sensitive` declaration every
 * other surface reads.
 */
function pluginManifest(project: Project, operations: Operation[]): string {
  const sensitive = Object.entries(configProperties(project))
    .filter(([, property]) => isSensitive(property))
    .map(([key]) => [key, { sensitive: true }]);
  const declared = registrations(project).map((registration) => [
    registration.contract,
    registration.ids,
  ]);
  return json(
    compact({
      id: project.identity.name,
      name: displayName(project.identity.name),
      description: pluginDescription(project),
      version: project.identity.version ?? "0.0.0",
      configSchema: configSchema(project),
      uiHints: sensitive.length ? Object.fromEntries(sensitive) : undefined,
      activation: activation(project),
      contracts: {
        tools: operations.map((operation) => operation.name),
        ...Object.fromEntries(declared),
      },
    }),
  );
}

function executeBody(project: Project, operation: Operation): string {
  if (project.tool.binding === "typescript") {
    return `execute: async (params, config) =>
        operation(${JSON.stringify(operation.name)}).handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir,
        }),`;
  }
  return `execute: async (params, config) => kernel(${JSON.stringify(operation.name)}, params, config),`;
}

function pythonKernel(project: Project): string {
  const module = `${projectName.pythonPackage(project.identity.name)}.toolfactory.cli`;
  return `const repoRoot =
  process.env[${JSON.stringify(rootEnvName(project))}] ?? fileURLToPath(new URL("../../../", import.meta.url));

/**
 * Shim variant: the core is Python, so every call crosses a process boundary and config
 * travels as environment, exactly as it does for the CLI and the MCP server.
 */
async function kernel(name: string, params: unknown, config: unknown): Promise<unknown> {
  const env: Record<string, string> = { ...(process.env as Record<string, string>) };
  for (const [key, value] of Object.entries((config ?? {}) as Record<string, unknown>)) {
    if (value !== undefined && value !== null) env[key.toUpperCase().replace(/[^A-Z0-9]/g, "_")] = String(value);
  }
  env[${JSON.stringify(dataDirEnvName(project))}] = dataDir;
  const { stdout } = await execFileAsync(
    "uv",
    ["run", "python", "-m", ${JSON.stringify(module)}, name, "--json", JSON.stringify(params)],
    { cwd: repoRoot, env },
  );
  return JSON.parse(stdout) as unknown;
}
`;
}

/** `Parameters<OpenClawPluginApi["<api>"]>[0]`: the typed route to a registrar's argument. */
function registrarType(api: string): string {
  return `Parameters<OpenClawPluginApi[${JSON.stringify(api)}]>[0]`;
}

/** The generated region of `src/index.ts`: imports, the entry, and how to reach it from the tail. */
function indexRegion(project: Project, operations: Operation[]): string {
  const typescript = project.tool.binding === "typescript";
  const shim = !typescript && operations.length > 0;
  const imports = [
    ...(shim
      ? [
          `import { execFile } from "node:child_process";`,
          `import { fileURLToPath } from "node:url";`,
          `import { promisify } from "node:util";`,
        ]
      : []),
    ...(operations.length ? [`import { join } from "node:path";`] : []),
    `import { defineToolPlugin } from ${JSON.stringify(OPENCLAW_SCAFFOLD.sdkModule)};`,
    ...(operations.length
      ? [`import { resolveStateDir } from ${JSON.stringify(OPENCLAW_SCAFFOLD.statePathsModule)};`]
      : []),
    ...(operations.length || hasConfig(project) ? [`import { Type } from "typebox";`] : []),
    ...(typescript && operations.length
      ? [`import { operations } from ${JSON.stringify(`${npmName(project)}/dist/ops.js`)};`]
      : []),
  ];
  // The host's own state directory is what the tool keeps its data under; the kernel's
  // `<N>_DATA_DIR` fallback only has to answer when no host supplies one.
  const dataDir = !operations.length
    ? ""
    : `
/** Where this tool may keep its own state: OpenClaw's state directory, one folder per plugin. */
const dataDir = join(resolveStateDir(), "plugin-data", ${JSON.stringify(project.identity.name)});
`;
  const preamble = !operations.length
    ? ""
    : typescript
      ? `
/** Fail loudly if the core package and this plugin ever disagree about the operation list. */
function operation(name: string) {
  const found = operations.find((candidate) => candidate.name === name);
  if (!found) throw new Error(\`operation \${name} is missing from the core package\`);
  return found;
}
`
      : `
const execFileAsync = promisify(execFile);

${pythonKernel(project)}`;
  const tools = operations.map(
    (operation) => `    tool({
      name: ${JSON.stringify(operation.name)},
      description: ${JSON.stringify(operation.description ?? operation.name)},
      parameters: Type.Unsafe(${literal(normalizeSchema(operation.inputSchema), 6)}),
      ${executeBody(project, operation)}
    }),`,
  );
  const configLine = !hasConfig(project)
    ? ""
    : `  configSchema: Type.Unsafe<Record<string, unknown>>(${literal(configSchema(project), 2)}),\n`;
  const declared = registrations(project).flatMap((registration) => [
    `// - \`api.${registration.api}\` → contracts.${registration.contract}: ${registration.ids.join(", ")}`,
    `//   argument type: ${registrarType(registration.api)}`,
  ]);
  const trailer = declared.length
    ? [
        "",
        "// Declared in dev.toolfactory/tool.json (openclaw.registers), asserted by index.test.ts and by",
        "// `plugin-inspector inspect --check`; wire each one below the end marker.",
        ...declared,
      ]
    : [];
  return `
${HEADER}${imports.join("\n")}
${dataDir}${preamble}
const entry = defineToolPlugin({
  id: ${JSON.stringify(project.identity.name)},
  name: ${JSON.stringify(displayName(project.identity.name))},
  description: ${JSON.stringify(pluginDescription(project))},
  activation: ${literal(activation(project), 2)},
${configLine}${tools.length ? `  tools: (tool) => [\n${tools.join("\n")}\n  ],` : "  tools: () => [],"}
});
${trailer.join("\n")}
`;
}

/** Written once, when `src/index.ts` does not exist: the region plus the author's tail. */
function indexTemplate(project: Project): string {
  const first = registrations(project)[0];
  const example = !first
    ? []
    : [
        "",
        "// Wire the declared registrations by wrapping the generated entry (commented out so the",
        "// plugin builds before you fill it in):",
        "//",
        `// import type { OpenClawPluginApi } from ${JSON.stringify(OPENCLAW_SCAFFOLD.entryModule)};`,
        "//",
        "// const registerTools = entry.register;",
        "// entry.register = (api: OpenClawPluginApi) => {",
        "//   registerTools(api);",
        `//   const provider: ${registrarType(first.api)} = { id: ${JSON.stringify(first.ids[0] ?? project.identity.name)}, /* ... */ };`,
        `//   api.${first.api}(provider);`,
        "// };",
      ];
  return [`${ENTRY_BEGIN}${ENTRY_END}`, ...example, "", "export default entry;", ""].join("\n");
}

/**
 * The generated test proves both halves of the entry: the tool metadata OpenClaw reads from
 * `defineToolPlugin`, and — for every declared registration — that the author's tail actually
 * calls the registrar with the declared ids. A recorder standing in for `OpenClawPluginApi` is
 * how the upstream provider scaffold's own test does it.
 */
function indexTestTs(project: Project, operations: Operation[]): string {
  const declared = registrations(project);
  const registrationTest = !declared.length
    ? ""
    : `
  it("registers what dev.toolfactory/tool.json declares", () => {
    const registered: Record<string, unknown[]> = {};
    const record = (name: string) => (value: unknown) => {
      (registered[name] ??= []).push(value);
    };
    const api = {
      registerTool: record("registerTool"),
${declared.map((registration) => `      ${registration.api}: record(${JSON.stringify(registration.api)}),`).join("\n")}
    } as Partial<OpenClawPluginApi>;

    entry.register(api as OpenClawPluginApi);

${declared
  .map(
    (registration) =>
      `    expect(
      (registered[${JSON.stringify(registration.api)}] ?? []).map((value) => (value as { id: string }).id),
    ).toEqual(${JSON.stringify(registration.ids)});`,
  )
  .join("\n")}
  });
`;
  const entryImport = declared.length
    ? `import type { OpenClawPluginApi } from ${JSON.stringify(OPENCLAW_SCAFFOLD.entryModule)};\n`
    : "";
  return `${HEADER}import { getToolPluginMetadata } from ${JSON.stringify(OPENCLAW_SCAFFOLD.sdkModule)};
${entryImport}import { describe, expect, it } from "vitest";
import entry from "./index.js";

describe(${JSON.stringify(project.identity.name)}, () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual(${JSON.stringify(operations.map((operation) => operation.name))});
  });
${registrationTest}});
`;
}

/**
 * What a third-party plugin can reach at OpenClaw HEAD. Checked against the clone at
 * openclaw 2026.8.2 / git 0635e09a; every claim names the file it was read from, so the next
 * reader can re-check it instead of trusting this paragraph.
 */
function boundary(): string[] {
  return [
    "## Boundary — what a plugin can reach",
    "",
    "Everything this plugin does goes through `OpenClawPluginApi` (`src/plugins/plugin-api.types.ts`",
    "upstream, re-exported as `openclaw/plugin-sdk/plugin-entry`). Two things a Codex-facing voice",
    "plugin would like are **not** reachable from a third-party plugin at OpenClaw HEAD:",
    "",
    "- **The shared Codex app-server client.** A plugin may observe it —",
    "  `api.registerCodexAppServerExtensionFactory` (`src/plugins/plugin-api.types.ts`) delivers",
    "  read-only `tool_result` events (`src/plugins/codex-app-server-extension-types.ts`) — but the",
    "  client itself (`src/agents/harness/codex-app-server-extensions.ts`,",
    "  `src/agents/embedded-agent-runner/run/codex-app-server-recovery.ts`) has no `plugin-sdk`",
    "  export in the published package, so a plugin cannot open or drive a Codex session.",
    "- **The native-subagent monitor.** `src/plugins/plugin-api.types.ts` has no subagent seam at all;",
    "  the monitor lives in gateway/agent internals (`src/gateway/server-plugin-subagent-runtime.ts`,",
    "  `src/agents/subagents/`), none of which is exported.",
    "",
    "Smallest upstream ask that would close both: export the Codex app-server session client as",
    "`openclaw/plugin-sdk/codex-app-server-extensions`, and add one subagent lifecycle subscription",
    "next to `registerCodexAppServerExtensionFactory` in `src/plugins/plugin-api.types.ts`. Until",
    "then this plugin builds, validates, tests and publishes exactly as it does now; only the two",
    "capabilities above have to be driven from OpenClaw itself.",
    "",
  ];
}

function readme(project: Project, operations: Operation[]): string {
  const excluded = project.operations.filter(
    (operation) => verdict(operation, project).kind === "excluded",
  );
  const shim = project.tool.binding !== "typescript";
  const declared = registrations(project);
  const lines = [
    `# ${displayName(project.identity.name)} — OpenClaw plugin`,
    "",
    `Generated by toolfactory from \`${project.tool.identity}\` and \`dev.toolfactory/ops.json\`.`,
    "The layout is whatever `openclaw plugins init --type tool` writes; the tool list, the manifest",
    "contracts and the entry between the `tf:entry` markers in `src/index.ts` are projected.",
    "",
    "## Build",
    "",
    "```bash",
    "npm install",
    "npm run plugin:build",
    "npm run plugin:validate",
    "npm test",
    "```",
    "",
  ];
  if (declared.length) {
    lines.push(
      "## Contributes",
      "",
      "Declared in `dev.toolfactory/tool.json` (`openclaw.registers`). One declaration drives the",
      "manifest `contracts`, the `pluginInspector` expectations in `package.json` and `src/index.test.ts`;",
      "the call itself is yours, below the `// /tf:entry` marker in `src/index.ts`. Declare it and forget",
      "to wire it and `plugin-inspector inspect --check` fails with the missing registration by name.",
      "",
      ...declared.map(
        (registration) =>
          `- \`api.${registration.api}(…)\` → \`contracts.${registration.contract}\`: ${registration.ids
            .map((id) => `\`${id}\``)
            .join(", ")} — argument type \`${registrarType(registration.api)}\``,
      ),
      "",
    );
  }
  lines.push(
    "## Tools",
    "",
    ...(operations.length
      ? operations.map(
          (operation) =>
            `- \`${operation.name}\` — ${operation.description ?? "no description"} (${
              shim ? "degraded:out-of-process" : "native"
            })`,
        )
      : [
          declared.length
            ? "_None: this plugin contributes the registrations above, not tools. `contracts.tools` is empty and `defineToolPlugin` still supplies the metadata `openclaw plugins build` and `validate` check._"
            : "_No operation reaches this surface yet._",
        ]),
    "",
  );
  if (shim && operations.length) {
    lines.push(
      `Shim variant: the core is ${project.tool.binding}, so each tool spawns the kernel CLI and no host`,
      "capability is borrowed in-process. A native plugin requires a TypeScript core.",
      "",
    );
  }
  if (declared.length) lines.push(...boundary());
  if (excluded.length) {
    lines.push(
      "## Not generated — `excluded:implement-in-hosts`",
      "",
      "These operations declare a capability no portable core can satisfy, so toolfactory omits them",
      "rather than shipping a tool that throws at call time. This package is the escape hatch: write",
      `them here by hand in the author's half of \`${HOST_DIR}/src/index.ts\` (below the \`// /tf:entry\``,
      "marker), which no rebuild touches.",
      "",
      ...excluded.map(
        (operation) => `- \`${operation.name}\` — requires ${operation.requires.join(", ")}`,
      ),
      "",
    );
  }
  return lines.join("\n");
}

export const surface: Surface = {
  id: "openclaw-native",
  plan(project) {
    const operations = includedOperations(project, surface);
    return [
      {
        kind: "file",
        path: `${HOST_DIR}/package.json`,
        content: packageJson(project, operations),
      },
      {
        kind: "file",
        path: `${HOST_DIR}/tsconfig.json`,
        content: json(OPENCLAW_SCAFFOLD.tsconfig),
      },
      {
        kind: "file",
        path: `${HOST_DIR}/vitest.config.ts`,
        content: OPENCLAW_SCAFFOLD.vitestConfig,
      },
      {
        kind: "file",
        path: `${HOST_DIR}/openclaw.plugin.json`,
        content: pluginManifest(project, operations),
      },
      {
        kind: "region",
        path: `${HOST_DIR}/src/index.ts`,
        regions: [
          { begin: ENTRY_BEGIN, end: ENTRY_END, content: indexRegion(project, operations) },
        ],
        template: indexTemplate(project),
      },
      {
        kind: "file",
        path: `${HOST_DIR}/src/index.test.ts`,
        content: indexTestTs(project, operations),
      },
      { kind: "file", path: `${HOST_DIR}/README.md`, content: readme(project, operations) },
    ];
  },
  validate(project) {
    const at = { cwd: project.root };
    // Run the openclaw the plugin pins as a devDependency, not whatever happens to be on PATH.
    const openclaw = ["--prefix", HOST_DIR, "exec", "--no", "--", "openclaw", "plugins"];
    const entry = ["--root", HOST_DIR, "--entry", OPENCLAW_SCAFFOLD.entry];
    const operations = includedOperations(project, surface);
    return [
      // hosts/openclaw type-checks against the core's emitted declarations, so build it first —
      // unless no operation reaches the plugin, in which case it never imports the core.
      ...(project.tool.binding === "typescript" && operations.length
        ? [{ label: "core build", command: "npm", args: ["run", "build"], ...at }]
        : []),
      {
        label: "npm install (hosts/openclaw)",
        command: "npm",
        args: ["--prefix", HOST_DIR, "install"],
        ...at,
      },
      // C2: the scaffold is mirrored by running the real generator, never by trusting constants.
      {
        label: "openclaw scaffold drift",
        command: "node",
        args: [...execArgv, DRIFT_ENTRY, project.root],
        ...at,
      },
      {
        label: "tsc (hosts/openclaw)",
        command: "npm",
        args: ["--prefix", HOST_DIR, "run", "build"],
        ...at,
      },
      {
        label: "openclaw plugins build --check",
        command: "npm",
        args: [...openclaw, "build", "--check", ...entry],
        ...at,
      },
      {
        label: "openclaw plugins validate",
        command: "npm",
        args: [...openclaw, "validate", ...entry],
        ...at,
      },
      {
        label: "@openclaw/plugin-inspector inspect",
        command: "npx",
        args: [
          "--yes",
          "@openclaw/plugin-inspector",
          "inspect",
          "--plugin-root",
          HOST_DIR,
          "--no-openclaw",
          "--check",
          // Resolved against --plugin-root; keep the reports out of the author's tree.
          "--out",
          "node_modules/.cache/plugin-inspector",
        ],
        ...at,
      },
    ];
  },
  verdict,
};
