/**
 * OpenClaw native plugin — the §4.4 escape hatch. The package under `hosts/openclaw/` is the
 * scaffold `openclaw plugins init <id> --type tool` writes, with the tool list projected from
 * the operations OpenClaw can actually run.
 *
 * §8 C2 ("mirror scaffolds by execution, not transcription"): `plan()` is pure and therefore
 * has to carry the scaffold's constants, so `validate()` runs the real generator and fails when
 * any of them drifted. Every pinned value lives in OPENCLAW_SCAFFOLD below and nowhere else.
 */
import { execArgv } from "node:process";
import { DRIFT_ENTRY } from "../hosts/openclaw.js";
import { projectName } from "../identity/name.js";
import { isPortable, type Operation, type Project, type Surface, type Verdict } from "../model.js";
import { includedOperations } from "../report/coverage.js";
import { compact, configProperties, isSensitive, json, npmName, rootEnvName } from "./shared.js";

/** Transcribed from `openclaw plugins init --type tool`; `validate()` proves them still current. */
export const OPENCLAW_SCAFFOLD = {
  /** The OpenClaw release the scaffold was taken from (`package.json openclaw.build`). */
  openclawVersion: "2026.8.2",
  /** `peerDependencies.openclaw` and `openclaw.compat.pluginApi`. */
  pluginApi: ">=2026.5.17",
  private: true,
  scripts: {
    build: "tsc -p tsconfig.json",
    "plugin:build": "npm run build && openclaw plugins build --entry ./dist/index.js",
    "plugin:validate": "npm run build && openclaw plugins validate --entry ./dist/index.js",
    test: "vitest run --config ./vitest.config.ts",
  },
  files: ["dist", "openclaw.plugin.json", "README.md"],
  dependencies: { typebox: "^1.1.38" },
  devDependencies: { openclaw: "latest", typescript: "^5.9.0", vitest: "^3.2.0" },
  tsconfig: {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      strict: true,
      declaration: true,
      outDir: "dist",
      skipLibCheck: true,
    },
    include: ["src/**/*.ts"],
  },
  vitestConfig: `import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    include: ["src/**/*.test.ts"],
  },
});
`,
  /** Entry module, relative to the plugin root, as `openclaw.extensions` records it. */
  entry: "./dist/index.js",
  sdkModule: "openclaw/plugin-sdk/tool-plugin",
} as const;

export const HOST_DIR = "hosts/openclaw";

const HEADER = "// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n";

/** `titleFromId` from OpenClaw's scaffold generator. */
export function displayName(id: string): string {
  return id
    .split(/[-_.]/)
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

/**
 * OpenClaw stores `normalizeJsonSchema(schema)` in the plugin manifest, so emit schemas that are
 * already in that shape and `openclaw plugins build --check` stays a byte-for-byte agreement.
 */
export function normalizeSchema(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(normalizeSchema);
  if (!value || typeof value !== "object") return value;
  const record = { ...(value as Record<string, unknown>) };
  delete record.$schema;
  for (const [key, nested] of Object.entries(record)) record[key] = normalizeSchema(nested);
  const propertyNames = record.propertyNames as Record<string, unknown> | undefined;
  if (propertyNames && typeof propertyNames === "object" && propertyNames.type === "string") {
    delete record.propertyNames;
  }
  if (Array.isArray(record.required) && record.required.length === 0) delete record.required;
  return record;
}

/** A JSON value as a TypeScript literal, re-indented to sit at `indent` columns. */
function literal(value: unknown, indent: number): string {
  return JSON.stringify(value, null, 2).replaceAll("\n", `\n${" ".repeat(indent)}`);
}

/** `EMPTY_TOOL_PLUGIN_CONFIG_SCHEMA` from the SDK: what a plugin with no config schema reports. */
const EMPTY_CONFIG_SCHEMA = { type: "object", properties: {}, additionalProperties: false };

function hasConfig(project: Project): boolean {
  return Boolean(project.tool.config) && Object.keys(configProperties(project)).length > 0;
}

/** The plugin's `configSchema`: the tool's own config schema, or OpenClaw's empty default. */
export function configSchema(project: Project): Record<string, unknown> {
  return hasConfig(project)
    ? (normalizeSchema(project.tool.config) as Record<string, unknown>)
    : EMPTY_CONFIG_SCHEMA;
}

function pluginDescription(project: Project): string {
  return (
    project.identity.description ?? `Add ${displayName(project.identity.name)} tools to OpenClaw.`
  );
}

function verdict(operation: Operation, project: Project): Verdict {
  if (!isPortable(operation)) return { kind: "excluded", reason: "excluded:implement-in-hosts" };
  return project.tool.binding === "typescript"
    ? { kind: "native" }
    : { kind: "degraded", reason: "degraded:out-of-process" };
}

function packageJson(project: Project): string {
  const core =
    project.tool.binding === "typescript" ? { [npmName(project)]: "file:../.." } : undefined;
  return json({
    name: projectName.openclawPackage(project.identity.name),
    version: project.identity.version ?? "0.0.0",
    description: pluginDescription(project),
    type: "module",
    private: OPENCLAW_SCAFFOLD.private,
    scripts: OPENCLAW_SCAFFOLD.scripts,
    files: OPENCLAW_SCAFFOLD.files,
    peerDependencies: { openclaw: OPENCLAW_SCAFFOLD.pluginApi },
    dependencies: { ...OPENCLAW_SCAFFOLD.dependencies, ...core },
    devDependencies: OPENCLAW_SCAFFOLD.devDependencies,
    openclaw: {
      extensions: [OPENCLAW_SCAFFOLD.entry],
      compat: { pluginApi: OPENCLAW_SCAFFOLD.pluginApi },
      build: { openclawVersion: OPENCLAW_SCAFFOLD.openclawVersion },
    },
  });
}

/**
 * `openclaw plugins build` regenerates this file; emitting it keeps `--check` green from a clean tree.
 * `uiHints` is manifest-owned (preserved by the builder): it is how OpenClaw's config UI learns which
 * keys to mask, from the same `x-toolfactory.sensitive` declaration every other surface reads.
 */
function pluginManifest(project: Project, operations: Operation[]): string {
  const sensitive = Object.entries(configProperties(project))
    .filter(([, property]) => isSensitive(property))
    .map(([key]) => [key, { sensitive: true }]);
  return json(
    compact({
      id: project.identity.name,
      name: displayName(project.identity.name),
      description: pluginDescription(project),
      version: project.identity.version ?? "0.0.0",
      configSchema: configSchema(project),
      uiHints: sensitive.length ? Object.fromEntries(sensitive) : undefined,
      activation: { onStartup: true },
      contracts: { tools: operations.map((operation) => operation.name) },
    }),
  );
}

function executeBody(project: Project, operation: Operation): string {
  if (project.tool.binding === "typescript") {
    return `execute: async (params, config) =>
        operation(${JSON.stringify(operation.name)}).handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),`;
  }
  return `execute: async (params, config) => kernel(${JSON.stringify(operation.name)}, params, config),`;
}

function pythonKernel(project: Project): string {
  const module = `${projectName.pythonPackage(project.identity.name)}.toolfactory.cli`;
  return `const repoRoot =
  process.env[${JSON.stringify(rootEnvName(project))}] ?? fileURLToPath(new URL("../../../", import.meta.url));

/**
 * Shim variant: the core is Python, so every call crosses a process boundary and config
 * travels as environment, exactly as it does for the CLI and the MCP server.
 */
async function kernel(name: string, params: unknown, config: unknown): Promise<unknown> {
  const env: Record<string, string> = { ...(process.env as Record<string, string>) };
  for (const [key, value] of Object.entries((config ?? {}) as Record<string, unknown>)) {
    if (value !== undefined && value !== null) env[key.toUpperCase()] = String(value);
  }
  const { stdout } = await execFileAsync(
    "uv",
    ["run", "python", "-m", ${JSON.stringify(module)}, name, "--json", JSON.stringify(params)],
    { cwd: repoRoot, env },
  );
  return JSON.parse(stdout) as unknown;
}
`;
}

function indexTs(project: Project, operations: Operation[]): string {
  const typescript = project.tool.binding === "typescript";
  const imports = typescript
    ? [
        `import { defineToolPlugin } from ${JSON.stringify(OPENCLAW_SCAFFOLD.sdkModule)};`,
        `import { Type } from "typebox";`,
        // In-process call into the author's own module: the only shape that earns `native`.
        `import { operations } from ${JSON.stringify(`${npmName(project)}/dist/ops.js`)};`,
      ]
    : [
        `import { execFile } from "node:child_process";`,
        `import { fileURLToPath } from "node:url";`,
        `import { promisify } from "node:util";`,
        `import { defineToolPlugin } from ${JSON.stringify(OPENCLAW_SCAFFOLD.sdkModule)};`,
        `import { Type } from "typebox";`,
      ];
  const preamble = typescript
    ? `/** Fail loudly if the core package and this plugin ever disagree about the operation list. */
function operation(name: string) {
  const found = operations.find((candidate) => candidate.name === name);
  if (!found) throw new Error(\`operation \${name} is missing from the core package\`);
  return found;
}
`
    : `const execFileAsync = promisify(execFile);

${pythonKernel(project)}`;
  const tools = operations.map(
    (operation) => `    tool({
      name: ${JSON.stringify(operation.name)},
      description: ${JSON.stringify(operation.description ?? operation.name)},
      parameters: Type.Unsafe(${literal(normalizeSchema(operation.inputSchema), 6)}),
      ${executeBody(project, operation)}
    }),`,
  );
  const configLine = !hasConfig(project)
    ? ""
    : `  configSchema: Type.Unsafe<Record<string, unknown>>(${literal(configSchema(project), 2)}),\n`;
  return `${HEADER}${imports.join("\n")}

${preamble}
export default defineToolPlugin({
  id: ${JSON.stringify(project.identity.name)},
  name: ${JSON.stringify(displayName(project.identity.name))},
  description: ${JSON.stringify(pluginDescription(project))},
${configLine}  tools: (tool) => [
${tools.join("\n")}
  ],
});
`;
}

function indexTestTs(project: Project, operations: Operation[]): string {
  return `${HEADER}import { getToolPluginMetadata } from ${JSON.stringify(OPENCLAW_SCAFFOLD.sdkModule)};
import { describe, expect, it } from "vitest";
import entry from "./index.js";

describe(${JSON.stringify(project.identity.name)}, () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual(${JSON.stringify(operations.map((operation) => operation.name))});
  });
});
`;
}

function readme(project: Project, operations: Operation[]): string {
  const excluded = project.operations.filter(
    (operation) => verdict(operation, project).kind === "excluded",
  );
  const shim = project.tool.binding !== "typescript";
  const lines = [
    `# ${displayName(project.identity.name)} — OpenClaw plugin`,
    "",
    `Generated by toolfactory from \`${project.tool.identity}\` and \`dev.toolfactory/ops.json\`.`,
    "The layout is whatever `openclaw plugins init --type tool` writes; only the tool list is projected.",
    "",
    "## Build",
    "",
    "```bash",
    "npm install",
    "npm run plugin:build",
    "npm run plugin:validate",
    "npm test",
    "```",
    "",
    "## Tools",
    "",
    ...(operations.length
      ? operations.map(
          (operation) =>
            `- \`${operation.name}\` — ${operation.description ?? "no description"} (${
              shim ? "degraded:out-of-process" : "native"
            })`,
        )
      : ["_No operation reaches this surface yet._"]),
    "",
  ];
  if (shim) {
    lines.push(
      `Shim variant: the core is ${project.tool.binding}, so each tool spawns the kernel CLI and no host`,
      "capability is borrowed in-process. A native plugin requires a TypeScript core.",
      "",
    );
  }
  if (excluded.length) {
    lines.push(
      "## Not generated — `excluded:implement-in-hosts`",
      "",
      "These operations declare a capability no portable core can satisfy, so toolfactory omits them",
      "rather than shipping a tool that throws at call time. This package is the escape hatch: write",
      "them here by hand against the full OpenClaw plugin SDK, then run `toolfactory adopt",
      `${HOST_DIR}/src/index.ts\` so your edits are never regenerated away.`,
      "",
      ...excluded.map(
        (operation) => `- \`${operation.name}\` — requires ${operation.requires.join(", ")}`,
      ),
      "",
    );
  }
  return lines.join("\n");
}

export const surface: Surface = {
  id: "openclaw-native",
  plan(project) {
    const operations = includedOperations(project, surface);
    return [
      { kind: "file", path: `${HOST_DIR}/package.json`, content: packageJson(project) },
      {
        kind: "file",
        path: `${HOST_DIR}/tsconfig.json`,
        content: json(OPENCLAW_SCAFFOLD.tsconfig),
      },
      {
        kind: "file",
        path: `${HOST_DIR}/vitest.config.ts`,
        content: OPENCLAW_SCAFFOLD.vitestConfig,
      },
      {
        kind: "file",
        path: `${HOST_DIR}/openclaw.plugin.json`,
        content: pluginManifest(project, operations),
      },
      { kind: "file", path: `${HOST_DIR}/src/index.ts`, content: indexTs(project, operations) },
      {
        kind: "file",
        path: `${HOST_DIR}/src/index.test.ts`,
        content: indexTestTs(project, operations),
      },
      { kind: "file", path: `${HOST_DIR}/README.md`, content: readme(project, operations) },
    ];
  },
  validate(project) {
    const at = { cwd: project.root };
    // Run the openclaw the plugin pins as a devDependency, not whatever happens to be on PATH.
    const openclaw = ["--prefix", HOST_DIR, "exec", "--no", "--", "openclaw", "plugins"];
    const entry = ["--root", HOST_DIR, "--entry", OPENCLAW_SCAFFOLD.entry];
    return [
      // hosts/openclaw type-checks against the core's emitted declarations, so build it first.
      ...(project.tool.binding === "typescript"
        ? [{ label: "core build", command: "npm", args: ["run", "build"], ...at }]
        : []),
      {
        label: "npm install (hosts/openclaw)",
        command: "npm",
        args: ["--prefix", HOST_DIR, "install"],
        ...at,
      },
      // C2: the scaffold is mirrored by running the real generator, never by trusting constants.
      {
        label: "openclaw scaffold drift",
        command: "node",
        args: [...execArgv, DRIFT_ENTRY, project.root],
        ...at,
      },
      {
        label: "tsc (hosts/openclaw)",
        command: "npm",
        args: ["--prefix", HOST_DIR, "run", "build"],
        ...at,
      },
      {
        label: "openclaw plugins build --check",
        command: "npm",
        args: [...openclaw, "build", "--check", ...entry],
        ...at,
      },
      {
        label: "openclaw plugins validate",
        command: "npm",
        args: [...openclaw, "validate", ...entry],
        ...at,
      },
      {
        label: "@openclaw/plugin-inspector inspect",
        command: "npx",
        args: [
          "--yes",
          "@openclaw/plugin-inspector",
          "inspect",
          "--plugin-root",
          HOST_DIR,
          "--no-openclaw",
          // Resolved against --plugin-root; keep the reports out of the author's tree.
          "--out",
          "node_modules/.cache/plugin-inspector",
        ],
        ...at,
      },
    ];
  },
  verdict,
};
