/** A native VS Code extension. The author owns activation and all native contributions. */
import { execArgv } from "node:process";
import { fileURLToPath } from "node:url";
import { z } from "zod";
import { githubOwner, projectName } from "../identity/name.js";
import { isPortable, type Project, type Surface } from "../model.js";
import {
  configProperties,
  dataDirEnvName,
  envName,
  has,
  isSensitive,
  npmName,
  pypiName,
  rootEnvName,
} from "./shared.js";
import {
  ESBUILD,
  ESLINT,
  GITIGNORE,
  IGNORE,
  LAUNCH,
  TASKS,
  VSCODE_SCAFFOLD,
} from "./vscode-scaffold.js";

export const HOST_DIR = "hosts/vscode";
export const vscodeConfigSchema = z.object({
  publisher: z
    .string()
    .regex(/^[a-zA-Z0-9][a-zA-Z0-9-]*$/)
    .optional()
    .describe(
      "Your registered Visual Studio Marketplace/Open VSX publisher; repository owner is the local packaging default.",
    ),
  marketplace: z.boolean().default(true),
  openvsx: z.boolean().default(true),
});
export const VSCE_VERSION = "3.9.2";
export const OVSX_VERSION = "1.1.1";

export function extensionName(project: Project): string {
  return project.identity.name.replaceAll(".", "-");
}

export function publisher(project: Project): string {
  return (
    project.tool.vscode?.publisher ??
    githubOwner(project.identity.repository) ??
    extensionName(project)
  );
}

export function vsixName(project: Project): string {
  return `${extensionName(project)}-${project.identity.version ?? "0.0.0"}.vsix`;
}

function operations(project: Project) {
  return project.operations.filter(isPortable);
}

function runtime(project: Project): string {
  const name = extensionName(project);
  const python = project.tool.binding === "python";
  const packageName = python ? pypiName(project) : npmName(project);
  const version = project.identity.version ?? "0.0.0";
  const defaults = python
    ? { command: "uvx", args: ["--from", `${packageName}==${version}`, project.identity.name] }
    : { command: "npx", args: ["--yes", `${packageName}@${version}`] };
  const config = Object.entries(configProperties(project)).map(([key, property]) => ({
    key,
    env: envName(key),
    secret: isSensitive(property),
  }));
  return `// Generated by toolfactory. Native extension code belongs in extension.ts.
import { mkdir } from 'node:fs/promises';
import { Client } from '@modelcontextprotocol/client';
import { StdioClientTransport } from '@modelcontextprotocol/client/stdio';
import * as vscode from 'vscode';

const namespace = ${JSON.stringify(name)};
const defaults = ${JSON.stringify(defaults)};
const config: Array<{key: string; env: string; secret: boolean}> = ${JSON.stringify(config)};
const operations: Array<{name: string; title: string}> = ${JSON.stringify(operations(project).map((op) => ({ name: op.name, title: op.title ?? op.name })))};

function launch(context: vscode.ExtensionContext) {
  const settings = vscode.workspace.getConfiguration(namespace);
  const root = vscode.Uri.joinPath(context.extensionUri, '../..').fsPath;
  const development = context.extensionMode !== vscode.ExtensionMode.Production;
  const local = ${python ? `{ command: 'uv', args: ['run', '--quiet', '--directory', root, 'python', '-m', '${projectName.pythonPackage(project.identity.name)}.toolfactory.cli'] }` : `{ command: 'node', args: ['--import', 'tsx', root + '/src/toolfactory/cli.ts'] }`};
  const selected = development ? local : defaults;
  const command = settings.get<string>('runtime.command');
  return {
    command: command || selected.command,
    args: command ? settings.get<string[]>('runtime.args', []) : selected.args,
    cwd: development ? root : undefined,
  };
}

async function environment(context: vscode.ExtensionContext): Promise<Record<string, string>> {
  const settings = vscode.workspace.getConfiguration(namespace);
  const env: Record<string, string> = {};
  for (const property of config) {
    const value = (property.secret ? await context.secrets.get(property.env) : settings.get('config.' + property.key)) ?? process.env[property.env];
    if (value !== undefined) env[property.env] = typeof value === 'string' ? value : JSON.stringify(value);
  }
  await mkdir(context.globalStorageUri.fsPath, { recursive: true });
  env[${JSON.stringify(dataDirEnvName(project))}] = context.globalStorageUri.fsPath;
  const folder = vscode.workspace.workspaceFolders?.find(folder => folder.uri.scheme === 'file');
  if (folder) env[${JSON.stringify(rootEnvName(project))}] = folder.uri.fsPath;
  return env;
}

export function registerGenerated(context: vscode.ExtensionContext): void {
  const changes = new vscode.EventEmitter<void>();
  context.subscriptions.push(changes,
    vscode.workspace.onDidChangeConfiguration(event => { if (event.affectsConfiguration(namespace)) changes.fire(); }),
    context.secrets.onDidChange(() => changes.fire()),
    vscode.lm.registerMcpServerDefinitionProvider(namespace, {
      onDidChangeMcpServerDefinitions: changes.event,
      provideMcpServerDefinitions() {
        const selected = launch(context);
        const server = new vscode.McpStdioServerDefinition(
          ${JSON.stringify(projectName.display(project.identity.name))}, selected.command,
          [...selected.args, 'mcp'], {}, ${JSON.stringify(version)},
        );
        server.cwd = selected.cwd ? vscode.Uri.file(selected.cwd) : undefined;
        return [server];
      },
      async resolveMcpServerDefinition(server) {
        if (!vscode.workspace.isTrusted) throw new Error('Trust this workspace before starting the tool runtime.');
        if (server instanceof vscode.McpStdioServerDefinition) server.env = { ...server.env, ...await environment(context) };
        return server;
      },
    }),
  );
  ${
    config.some((property) => property.secret)
      ? `context.subscriptions.push(vscode.commands.registerCommand(namespace + '.configureSecrets', async () => {
    const chosen = await vscode.window.showQuickPick(config.filter(property => property.secret).map(property => property.env), { title: 'Configure credentials' });
    if (!chosen) return;
    const value = await vscode.window.showInputBox({ title: chosen, password: true, prompt: 'Stored in VS Code SecretStorage. Leave empty to remove.' });
    if (value === undefined) return;
    if (value) await context.secrets.store(chosen, value); else await context.secrets.delete(chosen);
  }));`
      : ""
  }
  for (const operation of operations) {
    context.subscriptions.push(vscode.commands.registerCommand(namespace + '.' + operation.name, async (args?: Record<string, unknown>) => {
      if (!vscode.workspace.isTrusted) throw new Error('Trust this workspace before running tools.');
      const interactive = args === undefined;
      if (interactive) {
        const input = await vscode.window.showInputBox({ title: operation.title, prompt: 'Operation arguments (JSON object)', value: '{}',
          validateInput(value) { try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? undefined : 'Enter a JSON object'; } catch { return 'Enter a JSON object'; } },
        });
        if (input === undefined) return;
        args = JSON.parse(input) as Record<string, unknown>;
      }
      const selected = launch(context);
      const client = new Client({ name: namespace + '-vscode', version: ${JSON.stringify(version)} });
      try {
        await client.connect(new StdioClientTransport({ command: selected.command, args: [...selected.args, 'mcp'],
          cwd: selected.cwd, env: await environment(context),
        }));
        const response = await client.callTool({ name: operation.name, arguments: args });
        if (response.isError) throw new Error(JSON.stringify(response.content));
        const result = response.structuredContent ?? response.content;
        if (interactive) await vscode.window.showTextDocument(await vscode.workspace.openTextDocument({ language: 'json', content: JSON.stringify(result, null, 2) }));
        return result;
      } finally {
        await client.close();
      }
    }));
  }
}
`;
}

function packagePatch(project: Project): Record<string, unknown> {
  const name = extensionName(project);
  const properties = Object.fromEntries(
    Object.entries(configProperties(project))
      .filter(([, property]) => !isSensitive(property))
      .map(([key, property]) => {
        const { "x-toolfactory": _metadata, ...schema } = property;
        return [`${name}.config.${key}`, schema];
      }),
  );
  const commands = operations(project).map((op) => ({
    command: `${name}.${op.name}`,
    title: op.title ?? op.name,
    category: projectName.display(project.identity.name),
  }));
  if (Object.values(configProperties(project)).some(isSensitive))
    commands.push({
      command: `${name}.configureSecrets`,
      title: "Configure credentials",
      category: projectName.display(project.identity.name),
    });
  return {
    name,
    version: project.identity.version ?? "0.0.0",
    displayName: projectName.display(project.identity.name),
    description: project.identity.description ?? `${project.identity.name} tools for VS Code`,
    publisher: publisher(project),
    license: project.identity.license ?? "UNLICENSED",
    ...(project.identity.repository
      ? { repository: { type: "git", url: project.identity.repository } }
      : {}),
    engines: VSCODE_SCAFFOLD.engines,
    main: "./dist/extension.js",
    capabilities: { untrustedWorkspaces: { supported: false } },
    contributes: {
      commands,
      mcpServerDefinitionProviders: [
        { id: name, label: projectName.display(project.identity.name) },
      ],
      configuration: {
        title: projectName.display(project.identity.name),
        properties: {
          ...properties,
          [`${name}.runtime.command`]: {
            type: "string",
            scope: "machine",
            description: "Override the tool runtime executable.",
          },
          [`${name}.runtime.args`]: {
            type: "array",
            items: { type: "string" },
            scope: "machine",
            description: "Arguments for runtime.command, before the mcp subcommand.",
          },
        },
      },
    },
    scripts: { ...VSCODE_SCAFFOLD.scripts, vsix: "vsce package --out extension.vsix" },
    dependencies: { "@modelcontextprotocol/client": "^2.0.0" },
    devDependencies: { ...VSCODE_SCAFFOLD.devDependencies, "@vscode/vsce": `^${VSCE_VERSION}` },
    overrides: VSCODE_SCAFFOLD.overrides,
  };
}

export const surface: Surface = {
  id: "vscode-extension",
  plan(project) {
    const registry = project.tool.binding === "python" ? "pypi" : "npm";
    if (!has(project, registry))
      throw new Error(`vscode-extension requires ${registry} for its installed runtime.`);
    const entry = `import * as vscode from 'vscode';\nimport { registerGenerated } from './generated';\n`;
    const probe = operations(project).find((op) => project.tool.tests.examples[op.name]);
    return [
      {
        kind: "merge",
        path: `${HOST_DIR}/package.json`,
        format: "json",
        patch: packagePatch(project),
        keyedArrays: {
          "contributes.commands": "command",
          "contributes.mcpServerDefinitionProviders": "id",
        },
      },
      { kind: "file", path: `${HOST_DIR}/src/generated.ts`, content: runtime(project) },
      {
        kind: "region",
        path: `${HOST_DIR}/src/extension.ts`,
        regions: [{ begin: "// tf:imports", end: "// /tf:imports", content: `\n${entry}` }],
        template: `// tf:imports\n// /tf:imports\n\n// This is your extension entry. Use the complete VS Code API here.\nexport function activate(context: vscode.ExtensionContext) {\n  registerGenerated(context);\n}\n\nexport function deactivate() {}\n`,
      },
      {
        kind: "merge",
        path: `${HOST_DIR}/tsconfig.json`,
        format: "json",
        patch: {
          compilerOptions: {
            module: "Node16",
            target: "ES2022",
            lib: ["ES2022"],
            types: ["node", "mocha"],
            sourceMap: true,
            rootDir: "src",
            strict: true,
          },
        },
      },
      ...[
        ["esbuild.js", ESBUILD],
        ["eslint.config.mjs", ESLINT],
        [".vscode/launch.json", LAUNCH],
        [".vscode/tasks.json", TASKS],
        [".vscodeignore", IGNORE],
        [".gitignore", GITIGNORE],
      ].map(([path, content]) => ({
        kind: "region" as const,
        path: `${HOST_DIR}/${path}`,
        regions: [
          {
            begin: path?.endsWith("ignore") ? "# tf:scaffold" : "// tf:scaffold",
            end: path?.endsWith("ignore") ? "# /tf:scaffold" : "// /tf:scaffold",
            content: "\n",
          },
        ],
        template: `${path?.endsWith("ignore") ? "# tf:scaffold\n# /tf:scaffold" : "// tf:scaffold\n// /tf:scaffold"}\n${content}`,
      })),
      {
        kind: "file",
        path: `${HOST_DIR}/.vscode-test.mjs`,
        content: `import { defineConfig } from '@vscode/test-cli';\nexport default defineConfig({ files: 'out/test/**/*.test.js', launchArgs: ['--disable-workspace-trust', '--skip-welcome', '--skip-release-notes', '--no-sandbox'] });\n`,
      },
      {
        kind: "file",
        path: `${HOST_DIR}/src/test/generated.test.ts`,
        content: `import * as assert from 'node:assert/strict';\nimport * as vscode from 'vscode';\nsuite('Generated extension', () => {\n  test('activates and registers the operations', async () => {\n    const extension = vscode.extensions.getExtension(${JSON.stringify(`${publisher(project)}.${extensionName(project)}`)});\n    assert.ok(extension);\n    await extension.activate();\n    const commands = await vscode.commands.getCommands(true);\n    for (const command of ${JSON.stringify(operations(project).map((op) => `${extensionName(project)}.${op.name}`))}) assert.ok(commands.includes(command), command);\n    ${probe ? `await vscode.commands.executeCommand(${JSON.stringify(`${extensionName(project)}.${probe.name}`)}, ${JSON.stringify(project.tool.tests.examples[probe.name])});` : ""}\n  });\n});\n`,
      },
      {
        kind: "file",
        path: `${HOST_DIR}/README.md`,
        content: `# ${projectName.display(project.identity.name)} for VS Code\n\n${project.identity.description ?? ""}\n\nInstall the VSIX with \`code --install-extension ${vsixName(project)}\`. The extension provides an MCP server and commands for each portable operation. ${registry === "npm" ? "Node.js/npm" : "uv"} must be on PATH; installed extensions use the matching published ${registry} version.\n\nDevelop with \`npm install\`, then open this directory in VS Code and press F5. Development and tests use the checkout's kernel. \`npm test\` runs a real Extension Development Host; \`npm run vsix\` creates the installable package.\n\nEdit \`src/extension.ts\` outside its import markers and add native files freely. Use all VS Code APIs: language-model tools, chat participants, views, webviews, commands, editors and language services. Add native contribution points and additional commands directly to \`package.json\`; generated command/provider entries are maintained by identity, preserving your entries. Build scripts, debugger settings and ignore rules are editable scaffold files. Use \`adopt\` only when replacing a generated integration itself.\n\nConfiguration is in VS Code Settings; credentials use SecretStorage through the Configure credentials command when declared. The runtime command/arguments can be overridden in machine settings.\n\nPublishers must be registered separately with Visual Studio Marketplace and Open VSX. Releases attach a VSIX even when no publishing credentials are configured.\n`,
      },
    ];
  },
  validate(project) {
    const cwd = `${project.root}/${HOST_DIR}`;
    const drift = fileURLToPath(new URL("../hosts/vscode.js", import.meta.url));
    return [
      {
        label: "VS Code upstream scaffold",
        command: "node",
        args: [...execArgv, drift, project.root],
      },
      { label: "VS Code dependencies", command: "npm", args: ["install"], cwd },
      { label: "VS Code VSIX", command: "npm", args: ["run", "vsix"], cwd },
      {
        label: "VS Code Extension Development Host",
        command: process.platform === "linux" ? "xvfb-run" : "npm",
        args: process.platform === "linux" ? ["-a", "npm", "test"] : ["test"],
        cwd,
      },
    ];
  },
  verdict(operation) {
    return isPortable(operation)
      ? { kind: "bridged", reason: "bridged:vscode-mcp" }
      : { kind: "excluded", reason: "excluded:implement-in-hosts" };
  },
};
