/**
 * Surface "workflows": the CI/release/test-harness/credential/dependency-update files, always
 * generated (never in `tool.json.surfaces`; `project/plan.ts` adds this surface unconditionally).
 *
 * Every command these workflows run comes from `src/project/gate.ts` — the gate is a command and
 * this file is its GitHub projection, so a project with no GitHub at all still has the same
 * definition of green. Only the `uses:` steps (checkout, toolchains, caches, publishers) are this
 * file's own.
 *
 * - `.github/workflows/ci.yml` — T0/T1 always: toolchain per binding, then `gateSteps`.
 * - `.github/workflows/release.yml` — only when a registry surface (npm/pypi/mcp-registry/
 *   clawhub) is selected: the gate, `packageSteps` uploaded as one artifact, one publish job per
 *   registry in the forced order §7 requires, the GitHub Release, and the Pages pair.
 * - `compose.toolfactory.yaml` — only when a host-native surface (openclaw-native /
 *   hermes-native) is selected: the T3 container harness, one service per selected host.
 * - `.env.example` — always: every `tool.json.config` property, uppercased, secrets marked.
 * - `renovate.json` — always: `config:recommended`, minus the paths toolfactory itself owns.
 */
import { stringify as yamlStringify } from "yaml";
import { LIVE_TEST_COMMAND } from "../bindings/python.js";
import { githubOwner } from "../identity/name.js";
import type { PackageManager, PlannedFile, Project, Surface } from "../model.js";
import {
  bootstrapSteps,
  type GateStep,
  gateSteps,
  openclawTarball,
  outputsStep,
  PACKAGE_MANAGER_COMMANDS,
  packageSteps,
  RELEASE_DIR,
  tagVersionAssert,
  toolfactoryCli,
  WEB_BUILD,
} from "../project/gate.js";
import { HOST_DIR as BROWSER_HOST_DIR, sourcesZipName, zipName } from "./browser-extension.js";
import { HERMES_PIN, hermesInstall, pluginDir as hermesPluginDir } from "./hermes-native.js";
import { ociImage, registryName } from "./mcp-registry.js";
import { HOST_DIR as OPENCLAW_HOST_DIR } from "./openclaw-native.js";
import {
  compact,
  configProperties,
  envName,
  has,
  isSensitive,
  liveCredentials,
  requiredConfig,
} from "./shared.js";
import { skillPath } from "./skill.js";

const YAML_HEADER =
  "# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n\n";

/** The one artifact the `package` job uploads and every later job reads. */
const RELEASE_ARTIFACT = "release-assets";

type Step = Record<string, unknown>;

function yml(document: unknown): string {
  // lineWidth: 0 disables folding — a long `run:` one-liner stays one line instead of being
  // wrapped mid-command, which would still parse but reads (and diffs) badly.
  // aliasDuplicateObjects: false — shared step objects must not become YAML anchors.
  return yamlStringify(document, { lineWidth: 0, aliasDuplicateObjects: false });
}

/** A single job dependency as GitHub Actions spells it: a bare string for one, an array for many. */
function needsOf(jobs: string[]): string | string[] | undefined {
  if (jobs.length === 0) return undefined;
  // A copy: callers keep pushing onto the leg list after reading it.
  return jobs.length === 1 ? jobs[0] : [...jobs];
}

// ---------------------------------------------------------------------------------------------
// Provisioning: the `uses:` half, which only CI has. Everything else is a gate.ts command.
// ---------------------------------------------------------------------------------------------

/** The package-manager action each row needs before `setup-node`'s cache can see it. */
const SETUP_ACTIONS: Record<PackageManager, Step[]> = {
  npm: [],
  pnpm: [{ uses: "pnpm/action-setup@v4" }],
};

/** Checkout plus the language toolchain: everything a job needs before it can run a command. */
function toolchainSteps(project: Project, node: string): Step[] {
  const pmName = project.packageManager ?? "npm";
  const steps: Step[] = [{ uses: "actions/checkout@v7" }];
  if (project.tool.binding === "typescript") {
    // uv runs the agentskills validator; the python toolchain has it anyway.
    steps.push(...SETUP_ACTIONS[pmName], {
      uses: "actions/setup-node@v7",
      with: { "node-version": node, cache: pmName },
    });
    if (has(project, "skill") || has(project, "hermes-native"))
      steps.push({ uses: "astral-sh/setup-uv@v6" });
  } else {
    // Node only runs `npx toolfactory`; 24 also covers the openclaw CLI when selected.
    steps.push(
      { uses: "actions/setup-node@v7", with: { "node-version": node } },
      { uses: "astral-sh/setup-uv@v6", with: { "python-version": "3.12" } },
    );
  }
  return steps;
}

/**
 * Hermes has no published wheel carrying `plugins doctor`, so `toolfactory validate` needs its
 * installer. One install per pin: the checkout, its venv and the launcher come back from the
 * cache, so the installer only runs when the pin moves. GitHub throttles anonymous clones from
 * shared runner addresses (the failure mode the installer's own fallbacks exist for), so that one
 * run clones with the job's token.
 */
function hermesSteps(project: Project): Step[] {
  if (!has(project, "hermes-native")) return [];
  return [
    {
      name: "Restore Hermes",
      id: "hermes",
      uses: "actions/cache@v4",
      with: {
        path: ["~/.hermes", "~/.local/bin/hermes*", "~/.local/share/uv/python"].join("\n"),
        key: `hermes-\${{ runner.os }}-${HERMES_PIN.commit}`,
      },
    },
    {
      name: "Install Hermes",
      if: "steps.hermes.outputs.cache-hit != 'true'",
      env: {
        GIT_CONFIG_COUNT: "1",
        GIT_CONFIG_KEY_0: "url.https://x-access-token:${{ github.token }}@github.com/.insteadOf",
        GIT_CONFIG_VALUE_0: "https://github.com/",
      },
      run: hermesInstall(),
    },
    { name: "Hermes on PATH", run: 'echo "$HOME/.local/bin" >> "$GITHUB_PATH"' },
  ];
}

/** One gate.ts step as a GitHub step; `node24` becomes the matrix guard where a matrix exists. */
function actionStep(step: GateStep, matrix: boolean): Step {
  return compact({
    name: step.name,
    run: step.run,
    env: step.env,
    if: matrix && step.when === "node24" ? "matrix.node-version == '24'" : undefined,
  });
}

// ---------------------------------------------------------------------------------------------
// ci.yml — always.
// ---------------------------------------------------------------------------------------------

/**
 * T4: the live tier runs the binding's live test with the real credentials, so it exists iff
 * the generated live test does — when `config` declares a key that is both required and
 * sensitive. Its secrets come from the `live-tests` environment, whose required reviewers
 * `toolfactory bootstrap-repo` sets, and the `if` keeps a fork's pull request away from them
 * (an environment gates deployments, not the checkout an untrusted PR ships).
 */
function liveJob(project: Project): Record<string, unknown> | undefined {
  if (liveCredentials(project).length === 0) return undefined;
  const properties = configProperties(project);
  const secrets = Object.keys(properties).filter((key) =>
    isSensitive(properties[key] as Record<string, unknown>),
  );
  const pmName = project.packageManager ?? "npm";
  const pm = PACKAGE_MANAGER_COMMANDS[pmName];
  const steps: Step[] =
    project.tool.binding === "typescript"
      ? [
          { uses: "actions/checkout@v7" },
          ...SETUP_ACTIONS[pmName],
          { uses: "actions/setup-node@v7", with: { "node-version": "24", cache: pmName } },
          { run: pm.install },
          { run: pm.run("build") },
          { name: "live tests", run: pm.run("test:live") },
        ]
      : [
          { uses: "actions/checkout@v7" },
          { uses: "astral-sh/setup-uv@v6", with: { "python-version": "3.12" } },
          { run: "uv sync" },
          { name: "live tests", run: LIVE_TEST_COMMAND },
        ];
  return {
    needs: "test",
    if: "github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository",
    "runs-on": "ubuntu-latest",
    environment: "live-tests",
    env: Object.fromEntries(
      secrets.map((key) => [envName(key), `\${{ secrets.${envName(key)} }}`]),
    ),
    steps,
  };
}

function ciDocument(project: Project): Record<string, unknown> {
  const typescript = project.tool.binding === "typescript";
  const node = typescript ? "${{ matrix.node-version }}" : "24";
  const job = compact({
    "runs-on": "ubuntu-latest",
    strategy: typescript ? { matrix: { "node-version": ["22", "24"] } } : undefined,
    steps: [
      ...toolchainSteps(project, node),
      ...hermesSteps(project),
      ...gateSteps(project).map((step) => actionStep(step, typescript)),
    ],
  });
  const live = liveJob(project);
  return {
    name: "CI",
    on: compact({
      push: { branches: ["main"] },
      pull_request: {},
      // The live tier is also the one job a maintainer wants to fire by hand.
      workflow_dispatch: live ? {} : undefined,
    }),
    permissions: { contents: "read" },
    jobs: compact({ test: job, live }),
  };
}

// ---------------------------------------------------------------------------------------------
// The browser extension's publish-* legs: store submission (stored secrets, no OIDC — none of
// the three stores support it) and the opt-in Safari host-native leg. `wxt submit` reads every
// store credential from the environment itself once the flag naming the CLI's UPPER_SNAKE_CASE
// convention (verified live, `publish-browser-extension@6.1.1`'s resolveConfig): the shell only
// has to decide which store's `--<store>-zip` flag to pass, so an unconfigured store is a no-op,
// never a validation error, and a project with the surface selected but no store secrets at all
// still gets a green `publish-browser-ext` leg that does nothing.
// ---------------------------------------------------------------------------------------------

/**
 * Chrome Web Store API v2 (mandatory: v1/v1.1 shuts off 15 Oct 2026) authenticates with a
 * service account, not the client-id/secret/refresh-token triple v1.1 used — verified against
 * `publish-browser-extension`'s own config schema, which switches shape entirely on `apiVersion`.
 * Firefox and Edge have no v2 equivalent, so their names are the ones already in the CLI's
 * `--help`.
 */
const CHROME_STORE_SECRETS = [
  "CHROME_EXTENSION_ID",
  "CHROME_PUBLISHER_ID",
  "CHROME_SERVICE_ACCOUNT_CLIENT_EMAIL",
  "CHROME_SERVICE_ACCOUNT_PRIVATE_KEY",
];
const FIREFOX_STORE_SECRETS = ["FIREFOX_EXTENSION_ID", "FIREFOX_JWT_ISSUER", "FIREFOX_JWT_SECRET"];
const EDGE_STORE_SECRETS = ["EDGE_PRODUCT_ID", "EDGE_CLIENT_ID", "EDGE_API_KEY"];

/** `wxt submit --dry-run` (always) or a real `wxt submit` (tag push only), gated per store. */
function browserExtSubmitScript(project: Project, dryRun: boolean): string {
  const zip = (browser: "chrome" | "firefox" | "edge") =>
    `${RELEASE_ARTIFACT}/${zipName(project, browser)}`;
  const present = (names: string[]) => names.map((name) => `[ -n "$${name}" ]`).join(" && ");
  return [
    'flags=""',
    `if ${present(CHROME_STORE_SECRETS)}; then flags="$flags --chrome-zip ${zip("chrome")}"; fi`,
    `if ${present(FIREFOX_STORE_SECRETS)}; then flags="$flags --firefox-zip ${zip("firefox")} --firefox-sources-zip ${RELEASE_ARTIFACT}/${sourcesZipName(project)}"; fi`,
    `if ${present(EDGE_STORE_SECRETS)}; then flags="$flags --edge-zip ${zip("edge")}"; fi`,
    'if [ -z "$flags" ]; then echo "No browser store credentials configured; skipping wxt submit."; exit 0; fi',
    `npm --prefix ${BROWSER_HOST_DIR} exec --no -- wxt submit ${dryRun ? "--dry-run " : ""}$flags`,
  ].join("\n");
}

function browserExtPublishJob(project: Project): Record<string, unknown> {
  return {
    needs: needsOf(["gate", "package"]),
    "runs-on": "ubuntu-latest",
    permissions: { contents: "read" },
    env: {
      // Constant, not a secret: selects the v2 schema above whenever the Chrome secrets are set.
      CHROME_API_VERSION: "v2",
      ...Object.fromEntries(
        [...CHROME_STORE_SECRETS, ...FIREFOX_STORE_SECRETS, ...EDGE_STORE_SECRETS].map((name) => [
          name,
          `\${{ secrets.${name} }}`,
        ]),
      ),
    },
    steps: [
      ...toolchainSteps(project, "24"),
      // Only the `wxt`/`publish-browser-extension` binary is needed — the zips it submits are the
      // `package` job's own, downloaded below, not rebuilt.
      { run: `npm --prefix ${BROWSER_HOST_DIR} install` },
      {
        uses: "actions/download-artifact@v8",
        with: { name: RELEASE_ARTIFACT, path: RELEASE_ARTIFACT },
      },
      {
        name: "wxt submit --dry-run (auth + zip check on every push and PR, no listing mutation)",
        run: browserExtSubmitScript(project, true),
      },
      {
        name: "wxt submit",
        if: "github.event_name == 'push'",
        run: browserExtSubmitScript(project, false),
      },
    ],
  };
}

/**
 * Safari has no headless publish path (§6): `xcrun safari-web-extension-converter` is macOS-only
 * and Apple's own Xcode archive/export is the only route to App Store Connect. Opt-in
 * (`tool.json` `browserExtension.safari`) and never in the default matrix — a `macos-latest`
 * runner and a paid Apple Developer account are real costs the surface must not impose by
 * default. Documented as the host-native leg: toolfactory scaffolds the payload
 * (`wxt build -b safari`, any OS) and converts + signs it here; the archive/export invocation is
 * Apple's own and unverifiable without macOS, so an author adjusting scheme/entitlements for
 * their own app id is expected.
 */
function browserExtSafariJob(project: Project): Record<string, unknown> {
  return {
    needs: "gate",
    "runs-on": "macos-latest",
    permissions: { contents: "read" },
    env: {
      ASC_KEY_ID: "${{ secrets.ASC_KEY_ID }}",
      ASC_ISSUER_ID: "${{ secrets.ASC_ISSUER_ID }}",
      ASC_PRIVATE_KEY: "${{ secrets.ASC_PRIVATE_KEY }}",
    },
    steps: [
      ...toolchainSteps(project, "24"),
      { run: `npm --prefix ${BROWSER_HOST_DIR} install` },
      // `npm exec` never changes the working directory, so `wxt` needs its root passed
      // explicitly (verified live against `wxt zip`, the same CLI).
      {
        run: `npm --prefix ${BROWSER_HOST_DIR} exec --no -- wxt build ${BROWSER_HOST_DIR} -b safari`,
      },
      {
        name: "Convert to an Xcode project",
        run: `xcrun safari-web-extension-converter ${BROWSER_HOST_DIR}/.output/safari-mv2 --project-location dist/safari --no-open --no-prompt`,
      },
      {
        name: "Archive and export (App Store Connect API key)",
        run: [
          `key="dist/safari/AuthKey_$ASC_KEY_ID.p8" && printf '%s' "$ASC_PRIVATE_KEY" > "$key"`,
          `project="$(ls dist/safari/*.xcodeproj)" && scheme="$(basename "$project" .xcodeproj)"`,
          `xcodebuild archive -project "$project" -scheme "$scheme" -archivePath dist/safari/build.xcarchive`,
          `xcodebuild -exportArchive -archivePath dist/safari/build.xcarchive -exportPath dist/safari/export -authenticationKeyPath "$key" -authenticationKeyID "$ASC_KEY_ID" -authenticationKeyIssuerID "$ASC_ISSUER_ID"`,
        ].join(" && "),
      },
    ],
  };
}

// ---------------------------------------------------------------------------------------------
// release.yml — when npm, pypi, mcp-registry, clawhub or browser-extension is selected.
// ---------------------------------------------------------------------------------------------

function releaseDocument(
  project: Project,
): { doc: Record<string, unknown>; comments: string[] } | undefined {
  const npmSelected = has(project, "npm");
  const pypiSelected = has(project, "pypi");
  const mcpRegistrySelected = has(project, "mcp-registry");
  // ClawHub publishes the openclaw-native package; without that host there is nothing to publish.
  const clawhubSelected = has(project, "clawhub") && has(project, "openclaw-native");
  // ClawHub's skill catalog is a separate track from its plugin catalog above: it publishes
  // straight from the checkout (no openclaw-native package needed), so `skill` is all it takes.
  const clawhubSkillSelected = has(project, "clawhub") && has(project, "skill");
  const browserExtSelected = has(project, "browser-extension");
  if (
    !npmSelected &&
    !pypiSelected &&
    !mcpRegistrySelected &&
    !clawhubSelected &&
    !clawhubSkillSelected &&
    !browserExtSelected
  )
    return undefined;

  const pm = PACKAGE_MANAGER_COMMANDS[project.packageManager ?? "npm"];
  const cli = toolfactoryCli(project);
  const assert = tagVersionAssert(project);
  const jobs: Record<string, unknown> = {
    gate: {
      "runs-on": "ubuntu-latest",
      permissions: { contents: "read" },
      steps: [
        ...toolchainSteps(project, "24"),
        ...(assert ? [actionStep(assert, false)] : []),
        ...hermesSteps(project),
        ...gateSteps(project).map((step) => actionStep(step, false)),
      ],
    },
    package: compact({
      needs: "gate",
      "runs-on": "ubuntu-latest",
      permissions: { contents: "read" },
      // The Firefox self-hosted xpi packageSteps emits (gate.ts) is opt-in on this pair: present,
      // it signs; absent, that one step no-ops and the job still packages the unsigned zips.
      env: has(project, "browser-extension")
        ? {
            FIREFOX_JWT_ISSUER: "${{ secrets.FIREFOX_JWT_ISSUER }}",
            FIREFOX_JWT_SECRET: "${{ secrets.FIREFOX_JWT_SECRET }}",
          }
        : undefined,
      steps: [
        ...toolchainSteps(project, "24"),
        ...packageSteps(project).map((step) => actionStep(step, false)),
        {
          uses: "actions/upload-artifact@v7",
          with: { name: RELEASE_ARTIFACT, path: `${RELEASE_DIR}/` },
        },
      ],
    }),
  };
  const priorLegs: string[] = [];

  if (npmSelected) {
    jobs["publish-npm"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      permissions: { "id-token": "write", contents: "read" },
      steps: [
        { uses: "actions/checkout@v7" },
        ...SETUP_ACTIONS[project.packageManager ?? "npm"],
        {
          uses: "actions/setup-node@v7",
          with: { "node-version": "24", "registry-url": "https://registry.npmjs.org" },
        },
        // No `--provenance`: npm generates a provenance attestation itself under trusted publishing.
        { run: `${pm.install} && ${pm.run("build")} && npm publish --access public` },
      ],
    };
    priorLegs.push("publish-npm");
  }
  if (pypiSelected) {
    jobs["publish-pypi"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      environment: "pypi",
      permissions: { "id-token": "write" },
      steps: [
        { uses: "actions/checkout@v7" },
        { uses: "astral-sh/setup-uv@v6" },
        { run: "uv build" },
        {
          name: "Publish package distributions to PyPI",
          uses: "pypa/gh-action-pypi-publish@release/v1",
        },
      ],
    };
    priorLegs.push("publish-pypi");
  }
  const owner = githubOwner(project.identity.repository);
  if (mcpRegistrySelected && owner) {
    // The image the `mcp-registry` surface already named in `server.json`'s oci entry, and the
    // root Dockerfile it emitted alongside it. `type=semver` turns the v-prefixed tag into the
    // bare version the entry carries — the gate has already asserted they agree.
    const image = ociImage(project, owner).replace(/:[^:]*$/, "");
    jobs["publish-oci"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      permissions: {
        contents: "read",
        packages: "write",
        attestations: "write",
        "id-token": "write",
      },
      steps: [
        { uses: "actions/checkout@v7" },
        {
          uses: "docker/login-action@v4",
          with: {
            registry: "ghcr.io",
            username: "${{ github.actor }}",
            password: "${{ secrets.GITHUB_TOKEN }}",
          },
        },
        {
          id: "meta",
          uses: "docker/metadata-action@v6",
          with: {
            images: image,
            tags: "type=semver,pattern={{version}}",
            // The registry's OCI ownership check reads this label back out of the image config.
            labels: `io.modelcontextprotocol.server.name=${registryName(project)}`,
          },
        },
        {
          uses: "docker/build-push-action@v7",
          with: {
            context: ".",
            push: true,
            tags: "${{ steps.meta.outputs.tags }}",
            labels: "${{ steps.meta.outputs.labels }}",
          },
        },
      ],
    };
    priorLegs.push("publish-oci");
  }
  if (mcpRegistrySelected) {
    jobs["publish-mcp-registry"] = {
      // After every package leg (§7): mcp-publisher validates that each `packages[]` entry
      // already exists in its own registry, the oci image included.
      needs: needsOf(priorLegs.length ? priorLegs : ["gate"]),
      "runs-on": "ubuntu-latest",
      permissions: { "id-token": "write", contents: "read" },
      steps: [
        { uses: "actions/checkout@v7" },
        {
          run: 'curl -sL "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_linux_amd64.tar.gz" | tar xz mcp-publisher',
        },
        { run: "./mcp-publisher login github-oidc && ./mcp-publisher publish" },
      ],
    };
    priorLegs.push("publish-mcp-registry");
  }
  const comments = [
    "v0: no per-registry release-ledger (spec §7 defers it) — a partial failure across legs",
    "needs manual triage; a re-run is not yet skip-succeeded-legs safe.",
  ];
  if (npmSelected || pypiSelected) {
    comments.push(
      "",
      "One-time human setup (no API, so not automated here): register a GitHub trusted",
      "publisher for this repo + this workflow filename on npmjs.com / pypi.org.",
    );
  }
  if (clawhubSelected) {
    jobs["publish-clawhub"] = compact({
      // Last (§7): content-fingerprint deduped by ClawHub, therefore safe to retry. The reusable
      // workflow has no build step, so it publishes the tarball the `package` job already built
      // rather than the repository subdirectory. It is a workflow call, so it has no `permissions`
      // block of its own and inherits the file's `contents: read`.
      needs: needsOf(["package", ...priorLegs]),
      uses: "openclaw/clawhub/.github/workflows/package-publish.yml@main",
      with: {
        package_artifact_name: RELEASE_ARTIFACT,
        package_artifact_path: openclawTarball(project),
        dry_run: false,
        wait_for_publication: true,
      },
      secrets: { clawhub_token: "${{ secrets.CLAWHUB_TOKEN }}" },
    });
    priorLegs.push("publish-clawhub");
    comments.push(
      "",
      "ClawHub's GitHub-OIDC trusted publishing covers `workflow_dispatch` only, not",
      "`push: tags` — this leg is the one that is not secretless (§7): it needs a stored",
      "CLAWHUB_TOKEN repo secret, and `clawhub package trusted-publisher set` does not help here.",
    );
  }
  if (clawhubSkillSelected) {
    // A separate ClawHub track from the package leg above: publishes skills/<N> to ClawHub's
    // skill catalog straight from the checkout, so it only needs `gate`, not the built tarball.
    // ClawHub's own reusable workflow derives slug/name/version from SKILL.md and dedupes by
    // content fingerprint, same as `clawhub package publish` above — safe to retry.
    jobs["publish-clawhub-skill"] = compact({
      needs: "gate",
      uses: "openclaw/clawhub/.github/workflows/skill-publish.yml@main",
      with: { skill_path: skillPath(project).replace(/\/SKILL\.md$/, ""), dry_run: false },
      secrets: { clawhub_token: "${{ secrets.CLAWHUB_TOKEN }}" },
    });
    priorLegs.push("publish-clawhub-skill");
    comments.push(
      "",
      "ClawHub skill publishing has no OIDC trusted-publishing path yet (V1 is token-only,",
      "per its own docs) — this leg reuses the same stored CLAWHUB_TOKEN as publish-clawhub.",
    );
  }
  if (browserExtSelected) {
    jobs["publish-browser-ext"] = browserExtPublishJob(project);
    priorLegs.push("publish-browser-ext");
    comments.push(
      "",
      "None of Chrome Web Store, Firefox Add-ons or Edge Add-ons supports GitHub OIDC — like",
      "CLAWHUB_TOKEN above, publish-browser-ext is a stored-secrets leg, gated per store on that",
      "store's own secrets (nine names across the three stores); a store left unconfigured is",
      "skipped, never a failure, and the leg's own dry run runs on every push and pull request.",
    );
    if (project.tool.browserExtension?.safari) {
      // Opt-in and outside the release graph on purpose: it submits to App Store Connect, not
      // dist/release/, so nothing downstream needs to wait on it.
      jobs["publish-browser-ext-safari"] = browserExtSafariJob(project);
      comments.push(
        "",
        "publish-browser-ext-safari (opt-in, tool.json browserExtension.safari) is the macOS",
        "host-native leg: xcrun safari-web-extension-converter, then an Xcode archive/export",
        "signed with an App Store Connect API key. Runs on macos-latest, needs only `gate`, and",
        "does not gate the release — it submits to App Store Connect, not dist/release/.",
      );
    }
  }

  jobs.release = {
    // The tag's own release, after every leg: the assets are the same ones the registries got.
    needs: needsOf(["package", ...priorLegs]),
    "runs-on": "ubuntu-latest",
    permissions: { contents: "write" },
    steps: [
      {
        uses: "actions/download-artifact@v8",
        with: { name: RELEASE_ARTIFACT, path: RELEASE_ARTIFACT },
      },
      {
        uses: "softprops/action-gh-release@v3",
        with: {
          generate_release_notes: true,
          files: `${RELEASE_ARTIFACT}/*`,
          fail_on_unmatched_files: true,
        },
      },
    ],
  };

  if (has(project, "web")) {
    jobs["pages-build"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      permissions: { contents: "read" },
      steps: [
        ...toolchainSteps(project, "24"),
        ...[...bootstrapSteps(project), outputsStep(project)].map((step) =>
          actionStep(step, false),
        ),
        { uses: "actions/configure-pages@v5" },
        {
          name: "web build",
          // A project page is served from /<repo>/, so Vite's base has to say so or every asset
          // 404s. `web/vite.config.ts` reads PAGES_BASE and defaults to "/" for `npm run dev`.
          env: { PAGES_BASE: "/${{ github.event.repository.name }}/" },
          run: WEB_BUILD,
        },
        {
          name: "publish the schema and the coverage report alongside the app",
          run: `cp dev.toolfactory/tool.schema.json COVERAGE.md web/dist/ && ${cli} coverage > web/dist/coverage.json`,
        },
        { uses: "actions/upload-pages-artifact@v3", with: { path: "web/dist" } },
      ],
    };
    jobs["pages-deploy"] = {
      needs: "pages-build",
      "runs-on": "ubuntu-latest",
      permissions: { pages: "write", "id-token": "write" },
      environment: { name: "github-pages", url: "${{ steps.deployment.outputs.page_url }}" },
      steps: [{ id: "deployment", uses: "actions/deploy-pages@v5" }],
    };
    comments.push(
      "",
      "One-time human setup for Pages: Settings -> Pages -> Source = GitHub Actions.",
    );
  }

  const doc = {
    name: "Release",
    on: { push: { tags: ["v*"] } },
    permissions: { contents: "read" },
    jobs,
  };
  return { doc, comments };
}

// ---------------------------------------------------------------------------------------------
// compose.toolfactory.yaml — when openclaw-native or hermes-native is selected.
// ---------------------------------------------------------------------------------------------

function composeDocument(project: Project): Record<string, unknown> | undefined {
  const openclawSelected = has(project, "openclaw-native");
  const hermesSelected = has(project, "hermes-native");
  if (!openclawSelected && !hermesSelected) return undefined;

  const requiresBrowser = project.operations.some((op) => op.requires.includes("browser"));
  const services: Record<string, unknown> = {};

  if (openclawSelected) {
    services.openclaw = {
      image: `ghcr.io/openclaw/openclaw:latest${requiresBrowser ? "-browser" : ""}`,
      volumes: [".:/work", "PLUGIN_DATA:/data"],
      env_file: [".env"],
      // `--link` registers the mounted checkout in place: a plain install copies the whole tree,
      // node_modules/openclaw included, and trips the install-time symlink scan on the `file:`
      // core dependency. `--accept-capabilities` is what makes the install non-interactive.
      command: [
        "sh",
        "-c",
        `openclaw plugins install --link /work/${OPENCLAW_HOST_DIR} --force --accept-capabilities && openclaw plugins inspect ${project.identity.name} --runtime --json`,
      ],
    };
  }
  if (hermesSelected) {
    services.hermes = {
      // No published Hermes image exists; its own installer, pinned, in a stock image is the host.
      image: "buildpack-deps:bookworm",
      volumes: [".:/work", "PLUGIN_DATA:/data"],
      environment: { HERMES_HOME: "/data" },
      env_file: [".env"],
      command: [
        "bash",
        "-c",
        `${hermesInstall()} && hermes plugins doctor /work/${hermesPluginDir(project)} --ci`,
      ],
    };
  }
  return { services, volumes: { PLUGIN_DATA: {} } };
}

// ---------------------------------------------------------------------------------------------
// .env.example — always: every config key, from the one credential declaration (§6).
// ---------------------------------------------------------------------------------------------

function envExample(project: Project): string {
  const properties = configProperties(project);
  const required = new Set(requiredConfig(project));
  const keys = Object.keys(properties);
  const lines = [
    "# Generated by toolfactory from dev.toolfactory/tool.json `config`. Copy to `.env` and fill in.",
  ];
  if (keys.length === 0) lines.push("# No configuration keys are declared yet.");
  for (const key of keys) {
    const property = properties[key] as Record<string, unknown>;
    const sensitive = isSensitive(property);
    const meta = (property["x-toolfactory"] ?? {}) as { url?: string };
    const description = typeof property.description === "string" ? property.description : key;
    const tags = [required.has(key) ? "required" : "optional", sensitive ? "secret" : undefined]
      .filter(Boolean)
      .join(", ");
    lines.push(
      "",
      `# ${description} (${tags})${meta.url ? ` — get one: ${meta.url}` : ""}`,
      `${envName(key)}=`,
    );
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------------------------
// renovate.json — always: config:recommended already spans npm/PyPI/Actions/Docker (C9).
// ---------------------------------------------------------------------------------------------

function renovatePatch(): Record<string, unknown> {
  return {
    $schema: "https://docs.renovatebot.com/renovate-schema.json",
    // `group:all` is Renovate's own preset for one PR per run rather than one per dependency;
    // writing the rule out by hand would only own a key the author needs for their own pins.
    extends: ["config:recommended", "group:all"],
    // Mirrors OpenClaw's own minimumReleaseAge.
    minimumReleaseAge: "7 days",
    // These files are projections of dev.toolfactory/tool.json and are SHA-locked: a Renovate PR
    // editing one makes `toolfactory check` fail and the next `toolfactory build` reverts it.
    // Upgrading what they pin is a toolfactory version bump (§8 C6).
    ignorePaths: [".github/workflows/**", "hosts/*/package.json", "web/package.json"],
  };
}

export const surface: Surface = {
  id: "workflows",
  plan(project) {
    const files: PlannedFile[] = [
      {
        kind: "file",
        path: ".github/workflows/ci.yml",
        content: YAML_HEADER + yml(ciDocument(project)),
      },
    ];

    const release = releaseDocument(project);
    if (release) {
      const header = [
        YAML_HEADER.trimEnd(),
        ...release.comments.map((line) => (line ? `# ${line}` : "#")),
        "",
        "",
      ].join("\n");
      files.push({
        kind: "file",
        path: ".github/workflows/release.yml",
        content: header + yml(release.doc),
      });
    }

    const compose = composeDocument(project);
    if (compose) {
      files.push({
        kind: "file",
        path: "compose.toolfactory.yaml",
        content: YAML_HEADER + yml(compose),
      });
    }

    files.push({ kind: "file", path: ".env.example", content: envExample(project) });
    // A merge file: an author's own keys (a `customManagers` for pins in their source) survive.
    files.push({
      kind: "merge",
      path: "renovate.json",
      format: "json",
      patch: renovatePatch(),
      owned: ["extends", "ignorePaths"],
    });

    return files;
  },
};
