/**
 * Surface "workflows": the CI/release/test-harness/credential/dependency-update files, always
 * generated (never in `tool.json.surfaces`; `project/plan.ts` adds this surface unconditionally).
 *
 * - `.github/workflows/ci.yml` — T0/T1 always: toolchain per binding, `toolfactory check` +
 *   `validate`, the author's own tests, and whatever upstream validator CLIs the selected
 *   surfaces' `validate()` commands need on PATH.
 * - `.github/workflows/release.yml` — only when a registry surface (npm/pypi/mcp-registry/
 *   clawhub) is selected: the same check steps as a "gate" job, then one publish job per
 *   registry in the forced order §7 requires (npm/pypi → mcp-registry → clawhub), wired
 *   with `needs`.
 * - `compose.toolfactory.yaml` — only when a host-native surface (openclaw-native /
 *   hermes-native) is selected: the T3 container harness, one service per selected host.
 * - `.env.example` — always: every `tool.json.config` property, uppercased, secrets marked.
 * - `renovate.json` — always: `config:recommended` already covers npm/PyPI/Actions/Docker.
 */
import { stringify as yamlStringify } from "yaml";
import { LIVE_TEST_COMMAND } from "../bindings/python.js";
import type { PackageManager, PlannedFile, Project, Surface } from "../model.js";
import { HERMES_PIN, hermesInstall, pluginDir as hermesPluginDir } from "./hermes-native.js";
import {
  compact,
  configProperties,
  envName,
  has,
  isSensitive,
  json,
  liveCredentials,
  requiredConfig,
} from "./shared.js";

const YAML_HEADER =
  "# Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.\n\n";

type Step = Record<string, unknown>;

function yml(document: unknown): string {
  // lineWidth: 0 disables folding — a long `run:` one-liner stays one line instead of being
  // wrapped mid-command, which would still parse but reads (and diffs) badly.
  // aliasDuplicateObjects: false — shared step objects must not become YAML anchors.
  return yamlStringify(document, { lineWidth: 0, aliasDuplicateObjects: false });
}

/** A single job dependency as GitHub Actions spells it: a bare string for one, an array for many. */
function needsOf(jobs: string[]): string | string[] | undefined {
  if (jobs.length === 0) return undefined;
  return jobs.length === 1 ? jobs[0] : jobs;
}

// ---------------------------------------------------------------------------------------------
// The check steps: shared by ci.yml (matrix) and release.yml's gate job (Node 24).
// ---------------------------------------------------------------------------------------------

/** What each supported package manager spells; package.json `packageManager` picks the row. */
const PACKAGE_MANAGERS: Record<
  PackageManager,
  { setup: Step[]; install: string; run: (script: string) => string; test: string }
> = {
  npm: {
    setup: [],
    install: "npm ci",
    run: (script) => `npm run --if-present ${script}`,
    test: "npm test",
  },
  pnpm: {
    setup: [{ uses: "pnpm/action-setup@v4" }],
    install: "pnpm install --frozen-lockfile",
    run: (script) => `pnpm run --if-present ${script}`,
    test: "pnpm test",
  },
};

/** How CI invokes toolfactory: the devDependency in a TypeScript project, a pinned fetch otherwise. */
function toolfactoryCli(project: Project): string {
  return project.tool.binding === "typescript"
    ? "npx toolfactory"
    : `npx --yes toolfactory@${project.toolfactoryVersion}`;
}

/**
 * T0–T2 for one Node version: toolchain, install, build, `toolfactory check`, the validator
 * CLIs the selected surfaces' `validate()` commands need on PATH, `toolfactory validate`, then
 * the author's own `check` script (if present) and tests. Every command here is one the
 * surfaces themselves run, so the workflow cannot drift from `toolfactory validate`.
 */
function checkSteps(project: Project, node: string, matrix: boolean): Step[] {
  const typescript = project.tool.binding === "typescript";
  const pmName = project.packageManager ?? "npm";
  const pm = PACKAGE_MANAGERS[pmName];
  const cli = toolfactoryCli(project);
  // uv runs the agentskills validator; the python toolchain has it anyway.
  const needsUv = !typescript || has(project, "skill");

  const steps: Step[] = [{ uses: "actions/checkout@v6" }];
  if (typescript) {
    steps.push(...pm.setup, {
      uses: "actions/setup-node@v6",
      with: { "node-version": node, cache: pmName },
    });
    if (needsUv) steps.push({ uses: "astral-sh/setup-uv@v6" });
    steps.push({ run: pm.install }, { run: pm.run("build") });
  } else {
    // Node only runs `npx toolfactory`; 24 also covers the openclaw CLI when selected.
    steps.push(
      { uses: "actions/setup-node@v6", with: { "node-version": node } },
      { uses: "astral-sh/setup-uv@v6", with: { "python-version": "3.12" } },
      { run: "uv sync" },
    );
  }
  steps.push({ name: "toolfactory check", run: `${cli} check` });
  if (has(project, "claude")) {
    steps.push({ name: "Install Claude Code CLI", run: "npm i -g @anthropic-ai/claude-code" });
  }
  if (has(project, "web")) {
    // The web smoke drives Chromium; web/'s own npm install fetches the browser, the runner
    // needs its system libraries.
    steps.push({
      name: "Install Chromium dependencies",
      run: "npx --yes playwright install-deps chromium",
    });
  }
  if (has(project, "hermes-native")) {
    // One install per pin: the checkout, its venv and the launcher come back from the cache,
    // so the installer only runs when the pin moves. GitHub throttles anonymous clones from
    // shared runner addresses (the failure mode the installer's own fallbacks exist for), so
    // that one run clones with the job's token.
    steps.push(
      {
        name: "Restore Hermes",
        id: "hermes",
        uses: "actions/cache@v4",
        with: {
          path: ["~/.hermes", "~/.local/bin/hermes*", "~/.local/share/uv/python"].join("\n"),
          key: `hermes-\${{ runner.os }}-${HERMES_PIN.commit}`,
        },
      },
      {
        name: "Install Hermes",
        if: "steps.hermes.outputs.cache-hit != 'true'",
        env: {
          GIT_CONFIG_COUNT: "1",
          GIT_CONFIG_KEY_0: "url.https://x-access-token:${{ github.token }}@github.com/.insteadOf",
          GIT_CONFIG_VALUE_0: "https://github.com/",
        },
        run: hermesInstall(),
      },
      { name: "Hermes on PATH", run: 'echo "$HOME/.local/bin" >> "$GITHUB_PATH"' },
    );
  }
  steps.push(
    compact({
      name: "toolfactory validate",
      run: `${cli} validate`,
      // openclaw-native's validate() shells to the openclaw CLI, which needs Node >=24: skip
      // the 22 leg of the matrix rather than fail it (`validate` has no "all but one" filter).
      if: matrix && has(project, "openclaw-native") ? "matrix.node-version == '24'" : undefined,
    }),
  );
  if (typescript) steps.push({ name: "author checks", run: pm.run("check") });
  steps.push({
    name: "author tests",
    run: typescript ? pm.test : "uv run --with pytest pytest -q",
  });
  return steps;
}

// ---------------------------------------------------------------------------------------------
// ci.yml — always.
// ---------------------------------------------------------------------------------------------

/**
 * T4: the live tier runs the binding's live test with the real credentials, so it exists iff
 * the generated live test does — when `config` declares a key that is both required and
 * sensitive. Its secrets come from the `live-tests` environment, whose required reviewers
 * `toolfactory bootstrap-repo` sets, and the `if` keeps a fork's pull request away from them
 * (an environment gates deployments, not the checkout an untrusted PR ships).
 */
function liveJob(project: Project): Record<string, unknown> | undefined {
  if (liveCredentials(project).length === 0) return undefined;
  const properties = configProperties(project);
  const secrets = Object.keys(properties).filter((key) =>
    isSensitive(properties[key] as Record<string, unknown>),
  );
  const pmName = project.packageManager ?? "npm";
  const pm = PACKAGE_MANAGERS[pmName];
  const steps: Step[] =
    project.tool.binding === "typescript"
      ? [
          { uses: "actions/checkout@v6" },
          ...pm.setup,
          { uses: "actions/setup-node@v6", with: { "node-version": "24", cache: pmName } },
          { run: pm.install },
          { run: pm.run("build") },
          { name: "live tests", run: pm.run("test:live") },
        ]
      : [
          { uses: "actions/checkout@v6" },
          { uses: "astral-sh/setup-uv@v6", with: { "python-version": "3.12" } },
          { run: "uv sync" },
          { name: "live tests", run: LIVE_TEST_COMMAND },
        ];
  return {
    needs: "test",
    if: "github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository",
    "runs-on": "ubuntu-latest",
    environment: "live-tests",
    env: Object.fromEntries(
      secrets.map((key) => [envName(key), `\${{ secrets.${envName(key)} }}`]),
    ),
    steps,
  };
}

function ciDocument(project: Project): Record<string, unknown> {
  const typescript = project.tool.binding === "typescript";
  const job = compact({
    "runs-on": "ubuntu-latest",
    strategy: typescript ? { matrix: { "node-version": ["22", "24"] } } : undefined,
    steps: checkSteps(project, typescript ? "${{ matrix.node-version }}" : "24", typescript),
  });
  const live = liveJob(project);
  return {
    name: "CI",
    on: compact({
      push: { branches: ["main"] },
      pull_request: {},
      // The live tier is also the one job a maintainer wants to fire by hand.
      workflow_dispatch: live ? {} : undefined,
    }),
    permissions: { contents: "read" },
    jobs: compact({ test: job, live }),
  };
}

// ---------------------------------------------------------------------------------------------
// release.yml — when npm, pypi, mcp-registry or clawhub is selected.
// ---------------------------------------------------------------------------------------------

function releaseDocument(
  project: Project,
): { doc: Record<string, unknown>; comments: string[] } | undefined {
  const npmSelected = has(project, "npm");
  const pypiSelected = has(project, "pypi");
  const mcpRegistrySelected = has(project, "mcp-registry");
  // ClawHub publishes the openclaw-native package; without that host there is nothing to publish.
  const clawhubSelected = has(project, "clawhub") && has(project, "openclaw-native");
  if (!npmSelected && !pypiSelected && !mcpRegistrySelected && !clawhubSelected) return undefined;

  const pm = PACKAGE_MANAGERS[project.packageManager ?? "npm"];
  const jobs: Record<string, unknown> = {
    gate: { "runs-on": "ubuntu-latest", steps: checkSteps(project, "24", false) },
  };
  const priorLegs: string[] = [];

  if (npmSelected) {
    jobs["publish-npm"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      permissions: { "id-token": "write", contents: "read" },
      steps: [
        { uses: "actions/checkout@v6" },
        ...pm.setup,
        {
          uses: "actions/setup-node@v6",
          with: { "node-version": "24", "registry-url": "https://registry.npmjs.org" },
        },
        { run: `${pm.install} && ${pm.run("build")} && npm publish --provenance` },
      ],
    };
    priorLegs.push("publish-npm");
  }
  if (pypiSelected) {
    jobs["publish-pypi"] = {
      needs: "gate",
      "runs-on": "ubuntu-latest",
      environment: "pypi",
      permissions: { "id-token": "write" },
      steps: [
        { uses: "actions/checkout@v6" },
        { uses: "astral-sh/setup-uv@v6" },
        { run: "uv build" },
        {
          name: "Publish package distributions to PyPI",
          uses: "pypa/gh-action-pypi-publish@release/v1",
        },
      ],
    };
    priorLegs.push("publish-pypi");
  }
  if (mcpRegistrySelected) {
    jobs["publish-mcp-registry"] = {
      // Second (§7): mcp-publisher validates that the referenced package version already
      // exists in the target package registry, so it must run after that registry's publish.
      needs: needsOf(priorLegs.length ? priorLegs : ["gate"]),
      "runs-on": "ubuntu-latest",
      permissions: { "id-token": "write", contents: "read" },
      steps: [
        { uses: "actions/checkout@v6" },
        {
          run: 'curl -sL "https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_linux_amd64.tar.gz" | tar xz mcp-publisher',
        },
        { run: "./mcp-publisher login github-oidc && ./mcp-publisher publish" },
      ],
    };
    priorLegs.push("publish-mcp-registry");
  }
  const comments = [
    "v0: no per-registry release-ledger (spec §7 defers it) — a partial failure across legs",
    "needs manual triage; a re-run is not yet skip-succeeded-legs safe.",
  ];
  if (npmSelected || pypiSelected) {
    comments.push(
      "",
      "One-time human setup (no API, so not automated here): register a GitHub trusted",
      "publisher for this repo + this workflow filename on npmjs.com / pypi.org.",
    );
  }
  if (clawhubSelected) {
    jobs["publish-clawhub"] = compact({
      // Last (§7): content-fingerprint deduped by ClawHub, therefore safe to retry.
      // No `hashFiles('hosts/openclaw/**')` guard here (unlike the gate job's step): `hashFiles`
      // is only valid in a step's own `if`, and this is a reusable-workflow-call job with no
      // steps — moot anyway, since this job is only ever emitted when openclaw-native is selected.
      needs: needsOf(priorLegs.length ? priorLegs : ["gate"]),
      uses: "openclaw/clawhub/.github/workflows/package-publish.yml@main",
      with: {
        source: "${{ github.repository }}",
        source_path: "hosts/openclaw",
        dry_run: false,
        wait_for_publication: true,
      },
      secrets: { clawhub_token: "${{ secrets.CLAWHUB_TOKEN }}" },
    });
    comments.push(
      "",
      "ClawHub's GitHub-OIDC trusted publishing covers `workflow_dispatch` only, not",
      "`push: tags` — this leg is the one that is not secretless (§7): it needs a stored",
      "CLAWHUB_TOKEN repo secret, and `clawhub package trusted-publisher set` does not help here.",
    );
  }

  const doc = {
    name: "Release",
    on: { push: { tags: ["v*"] } },
    permissions: { contents: "read" },
    jobs,
  };
  return { doc, comments };
}

// ---------------------------------------------------------------------------------------------
// compose.toolfactory.yaml — when openclaw-native or hermes-native is selected.
// ---------------------------------------------------------------------------------------------

function composeDocument(project: Project): Record<string, unknown> | undefined {
  const openclawSelected = has(project, "openclaw-native");
  const hermesSelected = has(project, "hermes-native");
  if (!openclawSelected && !hermesSelected) return undefined;

  const requiresBrowser = project.operations.some((op) => op.requires.includes("browser"));
  const services: Record<string, unknown> = {};

  if (openclawSelected) {
    services.openclaw = {
      image: `ghcr.io/openclaw/openclaw:latest${requiresBrowser ? "-browser" : ""}`,
      volumes: [".:/work", "PLUGIN_DATA:/data"],
      env_file: [".env"],
      command: [
        "sh",
        "-c",
        `openclaw plugins install /work/hosts/openclaw --force && openclaw plugins inspect ${project.identity.name} --runtime --json`,
      ],
    };
  }
  if (hermesSelected) {
    services.hermes = {
      // No published Hermes image exists; its own installer, pinned, in a stock image is the host.
      image: "buildpack-deps:bookworm",
      volumes: [".:/work", "PLUGIN_DATA:/data"],
      environment: { HERMES_HOME: "/data" },
      env_file: [".env"],
      command: [
        "bash",
        "-c",
        `${hermesInstall()} && hermes plugins doctor /work/${hermesPluginDir(project)} --ci`,
      ],
    };
  }
  return { services, volumes: { PLUGIN_DATA: {} } };
}

// ---------------------------------------------------------------------------------------------
// .env.example — always: every config key, from the one credential declaration (§6).
// ---------------------------------------------------------------------------------------------

function envExample(project: Project): string {
  const properties = configProperties(project);
  const required = new Set(requiredConfig(project));
  const keys = Object.keys(properties);
  const lines = [
    "# Generated by toolfactory from dev.toolfactory/tool.json `config`. Copy to `.env` and fill in.",
  ];
  if (keys.length === 0) lines.push("# No configuration keys are declared yet.");
  for (const key of keys) {
    const property = properties[key] as Record<string, unknown>;
    const sensitive = isSensitive(property);
    const meta = (property["x-toolfactory"] ?? {}) as { url?: string };
    const description = typeof property.description === "string" ? property.description : key;
    const tags = [required.has(key) ? "required" : "optional", sensitive ? "secret" : undefined]
      .filter(Boolean)
      .join(", ");
    lines.push(
      "",
      `# ${description} (${tags})${meta.url ? ` — get one: ${meta.url}` : ""}`,
      `${envName(key)}=`,
    );
  }
  return `${lines.join("\n")}\n`;
}

// ---------------------------------------------------------------------------------------------
// renovate.json — always: config:recommended already spans npm/PyPI/Actions/Docker (C9).
// ---------------------------------------------------------------------------------------------

function renovateJson(): string {
  return json({
    $schema: "https://docs.renovatebot.com/renovate-schema.json",
    extends: ["config:recommended"],
    // Mirrors OpenClaw's own minimumReleaseAge; one PR per run rather than per dependency.
    minimumReleaseAge: "7 days",
    packageRules: [{ groupName: "all dependencies", matchPackageNames: ["*"] }],
  });
}

export const surface: Surface = {
  id: "workflows",
  plan(project) {
    const files: PlannedFile[] = [
      {
        kind: "file",
        path: ".github/workflows/ci.yml",
        content: YAML_HEADER + yml(ciDocument(project)),
      },
    ];

    const release = releaseDocument(project);
    if (release) {
      const header = [
        YAML_HEADER.trimEnd(),
        ...release.comments.map((line) => (line ? `# ${line}` : "#")),
        "",
        "",
      ].join("\n");
      files.push({
        kind: "file",
        path: ".github/workflows/release.yml",
        content: header + yml(release.doc),
      });
    }

    const compose = composeDocument(project);
    if (compose) {
      files.push({
        kind: "file",
        path: "compose.toolfactory.yaml",
        content: YAML_HEADER + yml(compose),
      });
    }

    files.push({ kind: "file", path: ".env.example", content: envExample(project) });
    files.push({ kind: "file", path: "renovate.json", content: renovateJson() });

    return files;
  },
};
