// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { getToolPluginMetadata } from "openclaw/plugin-sdk/tool-plugin";
import { describe, expect, it } from "vitest";
import entry from "./index.js";

describe("toolfactory", () => {
  it("declares tool metadata", () => {
    expect(getToolPluginMetadata(entry)?.tools.map((tool) => tool.name)).toEqual(["adopt","bootstrap-repo","build","check","coverage","doctor","eject","init","introspect","unadopt","validate"]);
  });
});
