// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { Type } from "typebox";
import { operations } from "toolfactory/dist/ops.js";

/** Fail loudly if the core package and this plugin ever disagree about the operation list. */
function operation(name: string) {
  const found = operations.find((candidate) => candidate.name === name);
  if (!found) throw new Error(`operation ${name} is missing from the core package`);
  return found;
}

export default defineToolPlugin({
  id: "toolfactory",
  name: "Toolfactory",
  description: "Build an agent tool once; ship it as Agent Skills, MCP servers, Agent Plugins / Claude / Codex / Cursor bundles, OpenClaw and Hermes plugins, CLIs, and packages, with the tests and releases to match.",
  tools: (tool) => [
    tool({
      name: "adopt",
      description: "Stop regenerating one file; it becomes the author's (recorded as manual in the lock).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "path": {
            "type": "string",
            "description": "Repo-relative path of a generated file"
          }
        },
        "required": [
          "path"
        ]
      }),
      execute: async (params, config) =>
        operation("adopt").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "build",
      description: "Generate every selected surface in-tree from the identity file and the operation snapshot, and refresh the lock.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("build").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "check",
      description: "Fail if the operation snapshot or any generated file drifted from the code (the CI drift gate).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("check").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "coverage",
      description: "The operation × surface verdict matrix: native, bridged, degraded, or excluded, with reasons.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("coverage").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "doctor",
      description: "Report which upstream CLIs this machine can delegate to (git, gh, npm, uv, claude, openclaw, clawhub, hermes, uvx, agentskills, MCP Inspector, docker).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {}
      }),
      execute: async (params, config) =>
        operation("doctor").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "eject",
      description: "Adopt every file a surface owns, so the author takes it over entirely.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "surface": {
            "type": "string",
            "enum": [
              "skill",
              "agent-plugins",
              "claude",
              "codex",
              "cursor",
              "mcp",
              "mcp-registry",
              "cli",
              "npm",
              "pypi",
              "openclaw-native",
              "hermes-native",
              "clawhub",
              "web",
              "dsh",
              "workflows"
            ]
          }
        },
        "required": [
          "surface"
        ]
      }),
      execute: async (params, config) =>
        operation("eject").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "init",
      description: "Create a new tool: dev.toolfactory/tool.json, the authored identity file, the kernel scaffold for the chosen language, and the first build of every selected surface.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "name": {
            "type": "string",
            "description": "Tool name: lowercase letters, digits, hyphens, dots (Agent Plugins rule)"
          },
          "binding": {
            "type": "string",
            "enum": [
              "typescript",
              "python"
            ],
            "description": "Language of the core logic: typescript or python"
          },
          "surfaces": {
            "minItems": 1,
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "skill",
                "agent-plugins",
                "claude",
                "codex",
                "cursor",
                "mcp",
                "mcp-registry",
                "cli",
                "npm",
                "pypi",
                "openclaw-native",
                "hermes-native",
                "clawhub",
                "web",
                "dsh",
                "workflows"
              ]
            },
            "description": "Surfaces to generate"
          },
          "description": {
            "description": "One-line description",
            "type": "string"
          },
          "license": {
            "description": "SPDX license identifier",
            "type": "string"
          },
          "repository": {
            "description": "Source repository URL (GitHub URL enables the MCP Registry name)",
            "type": "string"
          },
          "author": {
            "description": "Author name",
            "type": "string"
          }
        },
        "required": [
          "name",
          "binding",
          "surfaces"
        ]
      }),
      execute: async (params, config) =>
        operation("init").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "introspect",
      description: "Spawn the kernel MCP server, list its tools, and snapshot them to dev.toolfactory/ops.json.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("introspect").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "unadopt",
      description: "Return an adopted file to toolfactory and regenerate it.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "path": {
            "type": "string",
            "description": "Repo-relative path of an adopted file"
          }
        },
        "required": [
          "path"
        ]
      }),
      execute: async (params, config) =>
        operation("unadopt").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
    tool({
      name: "validate",
      description: "Run each selected surface's own upstream validator (agentskills, claude plugin validate, MCP Inspector, openclaw, hermes, npm pack, uv build).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "surface": {
            "description": "Only this surface",
            "type": "string",
            "enum": [
              "skill",
              "agent-plugins",
              "claude",
              "codex",
              "cursor",
              "mcp",
              "mcp-registry",
              "cli",
              "npm",
              "pypi",
              "openclaw-native",
              "hermes-native",
              "clawhub",
              "web",
              "dsh",
              "workflows"
            ]
          }
        }
      }),
      execute: async (params, config) =>
        operation("validate").handler(params as never, {
          config: config as Record<string, string | undefined>,
        }),
    }),
  ],
});
