// tf:entry
// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { join } from "node:path";
import { defineToolPlugin } from "openclaw/plugin-sdk/tool-plugin";
import { resolveStateDir } from "openclaw/plugin-sdk/state-paths";
import { Type } from "typebox";
import { operations } from "toolfactory/dist/ops.js";
import { handler } from "toolfactory/dist/toolfactory/mcp.js";
import type { OpenClawPluginApi } from "openclaw/plugin-sdk/plugin-entry";

/**
 * Where this tool may keep its own state: OpenClaw's state directory, one folder per plugin.
 * Lazy, so that importing this module resolves no path and touches no disk — every host loader
 * and `plugin-inspector check --runtime` import the entry long before any tool runs.
 */
const dataDir = () => join(resolveStateDir(), "plugin-data", "toolfactory");

/** Fail loudly if the core package and this plugin ever disagree about the operation list. */
function operation(name: string) {
  const found = operations.find((candidate) => candidate.name === name);
  if (!found) throw new Error(`operation ${name} is missing from the core package`);
  return found;
}

const entry = defineToolPlugin({
  id: "toolfactory",
  name: "Toolfactory",
  description: "Build an agent tool once; ship it as Agent Skills, MCP servers, Agent Plugins / Claude / Codex / Cursor bundles, OpenClaw and Hermes plugins, CLIs, and packages, with the tests and releases to match.",
  activation: {
    "onStartup": true
  },
  tools: (tool) => [
    tool({
      name: "adopt",
      description: "Stop regenerating one file; it becomes the author's (recorded as manual in the lock).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "path": {
            "type": "string",
            "description": "Repo-relative path of a generated file"
          }
        },
        "required": [
          "path"
        ]
      }),
      execute: async (params, config) =>
        operation("adopt").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "bootstrap-repo",
      description: "Prepare the GitHub repository from the local .env: the `live-tests` environment with its required reviewers and the sensitive config keys inside it, the release registries' tokens at repository scope, GitHub Pages with source = Actions, and npm's trusted publisher. Values go to `gh` on stdin and are never returned.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "reviewers": {
            "default": [],
            "description": "GitHub logins that must approve a live run",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "dryRun": {
            "default": false,
            "description": "Print the gh invocations instead of running them",
            "type": "boolean"
          }
        }
      }),
      execute: async (params, config) =>
        operation("bootstrap-repo").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "build",
      description: "Generate every selected surface in-tree from the identity file and the operation snapshot, and refresh the lock.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("build").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "check",
      description: "Fail if the operation snapshot or any generated file drifted from the code (the CI drift gate).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("check").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "coverage",
      description: "The operation × surface verdict matrix: native, bridged, degraded, or excluded, with reasons.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("coverage").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "doctor",
      description: "Report which upstream CLIs this machine can delegate to (git, gh, npm, uv, claude, openclaw, clawhub, hermes, uvx, agentskills, MCP Inspector, docker).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {}
      }),
      execute: async (params, config) =>
        operation("doctor").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "eject",
      description: "Adopt every file a surface owns, so the author takes it over entirely.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "surface": {
            "type": "string",
            "enum": [
              "skill",
              "agent-plugins",
              "claude",
              "codex",
              "cursor",
              "mcp",
              "mcp-registry",
              "cli",
              "npm",
              "pypi",
              "openclaw-native",
              "hermes-native",
              "clawhub",
              "web",
              "dsh",
              "workflows",
              "agents",
              "readme",
              "gemini",
              "mcpb",
              "browser-extension"
            ]
          }
        },
        "required": [
          "surface"
        ]
      }),
      execute: async (params, config) =>
        operation("eject").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "gate",
      description: "Run the gate here, in order: build, the drift check, every selected surface's upstream validator, the author's checks and tests, and the credential-free host end-to-end. The same step list the generated ci.yml renders, so a project with no CI has the identical gate.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("gate").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "init",
      description: "Create a new tool: dev.toolfactory/tool.json, the authored identity file, the kernel scaffold for the chosen language, and the first build of every selected surface.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "name": {
            "type": "string",
            "description": "Tool name: lowercase letters, digits, hyphens, dots (Agent Plugins rule)"
          },
          "binding": {
            "type": "string",
            "enum": [
              "typescript",
              "python"
            ],
            "description": "Language of the core logic: typescript or python"
          },
          "surfaces": {
            "minItems": 1,
            "type": "array",
            "items": {
              "type": "string",
              "enum": [
                "skill",
                "agent-plugins",
                "claude",
                "codex",
                "cursor",
                "mcp",
                "mcp-registry",
                "cli",
                "npm",
                "pypi",
                "openclaw-native",
                "hermes-native",
                "clawhub",
                "web",
                "dsh",
                "workflows",
                "agents",
                "readme",
                "gemini",
                "mcpb",
                "browser-extension"
              ]
            },
            "description": "Surfaces to generate"
          },
          "description": {
            "description": "One-line description",
            "type": "string"
          },
          "license": {
            "description": "SPDX license identifier",
            "type": "string"
          },
          "repository": {
            "description": "Source repository URL (GitHub URL enables the MCP Registry name)",
            "type": "string"
          },
          "author": {
            "description": "Author name",
            "type": "string"
          },
          "keywords": {
            "description": "Activation triggers for hosts that key off them (Kiro Powers, Agent Plugins); defaults to [name]",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "git": {
            "default": true,
            "description": "git init when the directory is not a repository yet, and make the first commit",
            "type": "boolean"
          },
          "setup": {
            "default": true,
            "description": "Run .agents/setup: render the harness adapters, install the git hooks, install dependencies",
            "type": "boolean"
          },
          "repo": {
            "description": "owner/name of a GitHub repository to create with gh and push to",
            "type": "string"
          },
          "public": {
            "default": false,
            "description": "Create that repository public, not private",
            "type": "boolean"
          },
          "dryRun": {
            "default": false,
            "description": "Print the gh invocations instead of running them",
            "type": "boolean"
          },
          "reviewers": {
            "default": [],
            "description": "GitHub logins that must approve a live run, when the repository gets a live tier",
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "name",
          "binding",
          "surfaces"
        ]
      }),
      execute: async (params, config) =>
        operation("init").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "introspect",
      description: "Spawn the kernel MCP server, list its tools, and snapshot them to dev.toolfactory/ops.json.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("introspect").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "package",
      description: "Build every release asset into dist/release/ — npm tarball, Python distributions, OpenClaw plugin tarball, plugin bundle zip, web build, coverage — by the same steps the release workflow's package job runs. Publishing stays a CI concern.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("package").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "secrets",
      description: "Every credential this project's surfaces need — the tool's own sensitive config keys and the release registries' tokens — with where each one is set, whether it is present locally and on GitHub, and (check) whether the registry accepts it. Never a value.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "action": {
            "default": "status",
            "description": "status: the inventory. check: run each registry's own credential probe.",
            "type": "string",
            "enum": [
              "status",
              "check"
            ]
          },
          "key": {
            "description": "Only this secret",
            "type": "string"
          }
        }
      }),
      execute: async (params, config) =>
        operation("secrets").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "unadopt",
      description: "Return an adopted file to toolfactory and regenerate it.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "path": {
            "type": "string",
            "description": "Repo-relative path of an adopted file"
          }
        },
        "required": [
          "path"
        ]
      }),
      execute: async (params, config) =>
        operation("unadopt").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "unpublish",
      description: "Retract what a deselected surface used to publish. Git is the ledger: the previous tag's dev.toolfactory/tool.json says what was selected then, and every registry row that lost its surface is checked for the version that tag published and then retracted with the registry's own CLI — or reported with the exact page, where there is no API.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "ref": {
            "default": "HEAD",
            "description": "Diff against the tag before this ref (the release passes the tag being cut)",
            "type": "string"
          },
          "dryRun": {
            "default": false,
            "description": "List the retractions instead of running them",
            "type": "boolean"
          },
          "hard": {
            "default": false,
            "description": "Use the destructive retraction where one exists (npm unpublish --force)",
            "type": "boolean"
          }
        }
      }),
      execute: async (params, config) =>
        operation("unpublish").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "validate",
      description: "Run each selected surface's own upstream validator (agentskills, claude plugin validate, MCP Inspector, openclaw, hermes, npm pack, uv build).",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {
          "root": {
            "default": ".",
            "description": "Project root (directory containing dev.toolfactory/)",
            "type": "string"
          },
          "surface": {
            "description": "Only this surface",
            "type": "string",
            "enum": [
              "skill",
              "agent-plugins",
              "claude",
              "codex",
              "cursor",
              "mcp",
              "mcp-registry",
              "cli",
              "npm",
              "pypi",
              "openclaw-native",
              "hermes-native",
              "clawhub",
              "web",
              "dsh",
              "workflows",
              "agents",
              "readme",
              "gemini",
              "mcpb",
              "browser-extension"
            ]
          }
        }
      }),
      execute: async (params, config) =>
        operation("validate").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
    tool({
      name: "web",
      description: "Open this tool's web app: serves the operations page and the MCP endpoint on a free local port, opens a browser there, and returns the URL.",
      parameters: Type.Unsafe({
        "type": "object",
        "properties": {}
      }),
      execute: async (params, config) =>
        operation("web").handler(params as never, {
          config: config as Record<string, string | undefined>,
          dataDir: dataDir(),
        }),
    }),
  ],
});

/**
 * The web app, as a tab in the Control UI: one prefix route the gateway authenticates, handled
 * by the core package's own exported router — so `<prefix>/mcp` is answered in-process by the
 * same operations and everything else is the built page — and one descriptor that makes the
 * dashboard render it, instead of a URL an operator has to go and find.
 */
const WEB_PATH = "/plugins/toolfactory/web";

const registerTools = entry.register;
entry.register = (api: OpenClawPluginApi) => {
  registerTools(api);
  api.registerHttpRoute({
    path: WEB_PATH,
    match: "prefix",
    // A Control UI tab may only point at a gateway-authenticated route, and the operator's
    // gateway session is the authentication — the page needs no pairing token of its own.
    auth: "gateway",
    // `env: false`: the Secrets panel writes the developer's `.env` in their checkout, and
    // this plugin runs in the gateway's working directory, not theirs.
    handler: handler({ path: `${WEB_PATH}/mcp`, prefix: WEB_PATH, env: false }),
  });
  const descriptor = {
    id: "toolfactory-web",
    surface: "tab" as const,
    label: "Toolfactory",
    path: `${WEB_PATH}/`,
  };
  // `api.session.controls` is the current facade and the top-level registrar its deprecated
  // alias; the plugin inspector's mock SDK has only the latter, so take whichever is there.
  const controls = api.session?.controls;
  if (controls) controls.registerControlUiDescriptor(descriptor);
  else api.registerControlUiDescriptor(descriptor);
};

// /tf:entry

export default entry;
