// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import { useEffect, useState } from "react"
import { MoonIcon, SunIcon } from "lucide-react"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card"
import { Empty, EmptyDescription, EmptyHeader, EmptyTitle } from "@/components/ui/empty"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group"
import {
  initialValues,
  SchemaFields,
  toArguments,
  type FieldValue,
  type FormValues,
  type JsonSchema,
} from "@/schema-form"
import page from "./ops.json"

interface Operation {
  name: string
  description?: string
  inputSchema: JsonSchema
}
interface Page {
  tool: { name: string; version?: string; description?: string }
  cliAvailable: boolean
  defaultEndpoint: string
  mcpProtocolVersion: string
  operations: Operation[]
  excluded: { name: string; reason?: string }[]
}
/** TypeScript widens ops.json into a union of literal schemas; the page reads it as one shape. */
const DATA = page as unknown as Page

interface Outcome {
  cli: string | null
  request: unknown
  result?: unknown
  error?: string
}

function mcpRequest(operation: Operation, args: Record<string, unknown>) {
  return {
    jsonrpc: "2.0",
    id: Date.now(),
    method: "tools/call",
    params: {
      name: operation.name,
      arguments: args,
      _meta: {
        "io.modelcontextprotocol/protocolVersion": DATA.mcpProtocolVersion,
        "io.modelcontextprotocol/clientCapabilities": {},
        "io.modelcontextprotocol/clientInfo": {
          name: `${DATA.tool.name}-web`,
          version: DATA.tool.version ?? "0.0.0",
        },
      },
    },
  }
}

/**
 * 2026-07-28 streamable HTTP: no handshake, so protocol version, method and client identity
 * ride on the request itself, and a single tools/call answers with plain JSON or an SSE frame.
 */
async function call(
  endpoint: string,
  request: { method: string; params: { name: string } },
): Promise<unknown> {
  const response = await fetch(endpoint, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Accept: "application/json, text/event-stream",
      "MCP-Protocol-Version": DATA.mcpProtocolVersion,
      "Mcp-Method": request.method,
      "Mcp-Name": request.params.name,
    },
    body: JSON.stringify(request),
  })
  const text = await response.text()
  const framed = text.split("\n").find((line) => line.startsWith("data:"))
  let body: { error?: unknown; result?: { structuredContent?: unknown } }
  try {
    body = JSON.parse(framed ? framed.slice(5).trim() : text)
  } catch {
    throw new Error(`HTTP ${response.status}: ${text.slice(0, 500)}`)
  }
  if (body.error) throw new Error(JSON.stringify(body.error))
  return body.result?.structuredContent ?? body.result
}

function Preview({ outcome }: { outcome: Outcome }) {
  const tabs = [
    outcome.cli === null ? null : { value: "cli", label: "CLI", body: outcome.cli, failed: false },
    {
      value: "mcp",
      label: "MCP tools/call",
      body: JSON.stringify(outcome.request, null, 2),
      failed: false,
    },
    {
      value: "result",
      label: outcome.error ? "Error" : "Result",
      body: outcome.error ?? JSON.stringify(outcome.result, null, 2),
      failed: Boolean(outcome.error),
    },
  ].filter((tab) => tab !== null)
  return (
    <Tabs defaultValue={tabs[0].value} className="w-full">
      <TabsList variant="line">
        {tabs.map((tab) => (
          <TabsTrigger key={tab.value} value={tab.value}>
            {tab.label}
          </TabsTrigger>
        ))}
      </TabsList>
      {tabs.map((tab) => (
        <TabsContent key={tab.value} value={tab.value}>
          <pre
            data-slot={tab.value}
            data-failed={tab.failed}
            className="overflow-x-auto rounded-lg border bg-muted p-3 font-mono text-xs whitespace-pre-wrap data-[failed=true]:border-destructive data-[failed=true]:text-destructive"
          >
            {tab.body}
          </pre>
        </TabsContent>
      ))}
    </Tabs>
  )
}

function OperationCard({ operation, endpoint }: { operation: Operation; endpoint: string }) {
  const [values, setValues] = useState<FormValues>(() => initialValues(operation.inputSchema))
  const [outcome, setOutcome] = useState<Outcome | null>(null)
  const [busy, setBusy] = useState(false)
  const change = (name: string, value: FieldValue) =>
    setValues((current) => ({ ...current, [name]: value }))

  async function submit(event: React.FormEvent) {
    event.preventDefault()
    setBusy(true)
    try {
      const args = toArguments(operation.inputSchema, values)
      const request = mcpRequest(operation, args)
      const cli = DATA.cliAvailable
        ? `${DATA.tool.name} ${operation.name} --json '${JSON.stringify(args)}'`
        : null
      const target = endpoint.trim()
      if (!target) {
        setOutcome({ cli, request })
      } else {
        try {
          setOutcome({ cli, request, result: await call(target, request) })
        } catch (error) {
          setOutcome({ cli, request, error: error instanceof Error ? error.message : String(error) })
        }
      }
    } catch (error) {
      setOutcome({
        cli: null,
        request: null,
        error: error instanceof Error ? error.message : String(error),
      })
    }
    setBusy(false)
  }

  return (
    <Card>
      <form onSubmit={submit}>
        <CardHeader>
          <CardTitle>{operation.name}</CardTitle>
          {operation.description ? (
            <CardDescription>{operation.description}</CardDescription>
          ) : null}
        </CardHeader>
        <CardContent className="flex flex-col gap-6">
          <SchemaFields
            schema={operation.inputSchema}
            values={values}
            onChange={change}
            idPrefix={operation.name}
          />
          <Button type="submit" disabled={busy} className="w-fit">
            Run
          </Button>
          {outcome ? <Preview outcome={outcome} /> : null}
        </CardContent>
      </form>
    </Card>
  )
}

export default function App() {
  const [dark, setDark] = useState(() => document.documentElement.classList.contains("dark"))
  const [endpoint, setEndpoint] = useState(DATA.defaultEndpoint)
  const [active, setActive] = useState(DATA.operations[0]?.name ?? "")
  const activeOperation = DATA.operations.find((operation) => operation.name === active)
  useEffect(() => {
    document.documentElement.classList.toggle("dark", dark)
  }, [dark])

  return (
    <div className="min-h-svh bg-background text-foreground">
      <header className="border-b">
        <div className="mx-auto flex max-w-5xl flex-col gap-4 px-6 py-6">
          <div className="flex items-center gap-3">
            <h1 className="text-xl font-semibold">{DATA.tool.name}</h1>
            {DATA.tool.version ? <Badge variant="secondary">{DATA.tool.version}</Badge> : null}
            <Button
              variant="ghost"
              size="icon"
              className="ml-auto"
              aria-label="Toggle theme"
              onClick={() => setDark(!dark)}
            >
              {dark ? <SunIcon /> : <MoonIcon />}
            </Button>
          </div>
          {DATA.tool.description ? (
            <p className="text-sm text-muted-foreground">{DATA.tool.description}</p>
          ) : null}
          <Field>
            <FieldLabel htmlFor="endpoint">MCP endpoint</FieldLabel>
            <Input
              id="endpoint"
              value={endpoint}
              placeholder={DATA.defaultEndpoint}
              onChange={(event) => setEndpoint(event.target.value)}
            />
          </Field>
        </div>
      </header>

      <main className="mx-auto flex max-w-5xl flex-col gap-6 px-6 py-6">
        {activeOperation ? (
          <div className="flex flex-col gap-6 md:flex-row">
            <ToggleGroup
              orientation="vertical"
              className="md:w-44"
              value={[activeOperation.name]}
              onValueChange={(names) => names[0] && setActive(String(names[0]))}
            >
              {DATA.operations.map((operation) => (
                <ToggleGroupItem key={operation.name} value={operation.name} className="justify-start">
                  {operation.name}
                </ToggleGroupItem>
              ))}
            </ToggleGroup>
            <div className="min-w-0 flex-1">
              <OperationCard
                key={activeOperation.name}
                operation={activeOperation}
                endpoint={endpoint}
              />
            </div>
          </div>
        ) : (
          <Empty>
            <EmptyHeader>
              <EmptyTitle>No operations on this surface</EmptyTitle>
              <EmptyDescription>
                Every operation needs a host capability a web page cannot provide.
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        )}

        {DATA.excluded.length > 0 ? (
          <Alert>
            <AlertTitle>
              {DATA.excluded.length} operation(s) are not reachable over MCP
            </AlertTitle>
            <AlertDescription>
              <div className="flex flex-wrap gap-2">
                {DATA.excluded.map((operation) => (
                  <Badge key={operation.name} variant="outline">
                    {operation.name} — {operation.reason ?? "excluded"}
                  </Badge>
                ))}
              </div>
            </AlertDescription>
          </Alert>
        ) : null}
      </main>
    </div>
  )
}
