// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
/**
 * Playwright smoke for the generated page: the first operation's form renders its fields,
 * submitting previews the call, and an endpoint that is not there shows an error instead of
 * breaking the page. Run `npm --prefix web run build` first; this serves `web/dist`.
 */
import { readFile } from "node:fs/promises"
import { createServer } from "node:http"
import { extname, join, normalize } from "node:path"
import { fileURLToPath } from "node:url"
import { chromium } from "playwright"

const dist = fileURLToPath(new URL("./dist/", import.meta.url))
const page = JSON.parse(await readFile(new URL("./src/ops.json", import.meta.url), "utf8"))
const TYPES = {
  ".html": "text/html",
  ".js": "text/javascript",
  ".css": "text/css",
  ".json": "application/json",
  ".svg": "image/svg+xml",
  ".woff2": "font/woff2",
}

const server = createServer(async (request, response) => {
  const path = new URL(request.url, "http://localhost").pathname
  const file = join(dist, normalize(path === "/" ? "index.html" : path).replace(/^(\.\.[/\\])+/, ""))
  try {
    const body = await readFile(file)
    response.writeHead(200, { "content-type": TYPES[extname(file)] ?? "application/octet-stream" })
    response.end(body)
  } catch {
    // Everything outside dist — including the /mcp endpoint — is deliberately unreachable here.
    response.writeHead(404, { "content-type": "text/plain" }).end("no endpoint")
  }
})
await new Promise((resolve) => server.listen(0, "127.0.0.1", resolve))
const origin = `http://127.0.0.1:${server.address().port}`

const operation = page.operations[0]
if (!operation) {
  console.log("PASS no operations reach this surface; nothing to smoke")
  server.close()
  process.exit(0)
}

const browser = await chromium.launch()
try {
  const tab = await browser.newPage()
  const failures = []
  tab.on("pageerror", (error) => failures.push(error.message))
  await tab.goto(origin)

  await tab.getByRole("button", { name: operation.name, exact: true }).click()
  const expected = Object.keys(operation.inputSchema.properties ?? {})
  for (const name of expected) {
    await tab.locator(`[id="${operation.name}-${name}"]`).waitFor({ state: "visible" })
  }
  console.log(`PASS ${operation.name} renders ${expected.length} field(s): ${expected.join(", ")}`)

  // Fill the first plain-string property so the previews carry a real argument.
  const filled = expected.find((name) => {
    const property = operation.inputSchema.properties[name]
    return property.type === "string" && !property.enum
  })
  if (filled) await tab.locator(`[id="${operation.name}-${filled}"]`).fill("smoke")

  await tab.getByRole("button", { name: "Run" }).click()

  if (page.cliAvailable) {
    const cli = tab.locator('pre[data-slot="cli"]')
    await cli.waitFor({ state: "visible" })
    const text = (await cli.textContent()).trim()
    if (filled && !text.includes(`"${filled}":"smoke"`)) {
      throw new Error(`cli preview lost the ${filled} argument: ${text}`)
    }
    console.log(`PASS cli preview: ${text}`)
  }

  await tab.getByRole("tab", { name: "Error" }).click()
  const error = tab.locator('pre[data-failed="true"]')
  await error.waitFor({ state: "visible" })
  console.log(`PASS unreachable endpoint: ${(await error.textContent()).trim()}`)

  if (failures.length) throw new Error(`page raised: ${failures.join("; ")}`)
  console.log("PASS no uncaught page errors")
} finally {
  await browser.close()
  server.close()
}
