// Generated by toolfactory. Do not edit; run `toolfactory build` to regenerate.
import path from "path"
import tailwindcss from "@tailwindcss/vite"
import react from "@vitejs/plugin-react"
import { defineConfig } from "vite"

// Where `<tool> mcp --http` listens. The dev server proxies /mcp there so the page POSTs
// same-origin (no CORS), and changeOrigin rewrites Host so the kernel's loopback guard passes.
const mcp = new URL(process.env.VITE_MCP_URL ?? "http://localhost:3000/mcp")

// https://vite.dev/config/
export default defineConfig({
  // A GitHub Pages project page is not served from the domain root; the release workflow sets
  // PAGES_BASE=/<repo>/ for that build only, so `npm run dev` and every other build stay at "/".
  base: process.env.PAGES_BASE ?? "/",
  plugins: [react(), tailwindcss()],
  resolve: {
    alias: {
      "@": path.resolve(import.meta.dirname, "./src"),
    },
  },
  server: {
    proxy: {
      "/mcp": { target: mcp.origin, changeOrigin: true, rewrite: () => mcp.pathname },
    },
  },
})
